// Code generated by Icestudio 0.7.0

`default_nettype none

//---- Top entity
module main #(
 parameter vaf2e90 = 3,
 parameter vbdfd7f = 5,
 parameter v343c9c = 1,
 parameter va55992 = "va55992.list"
) (
 input vedfc81,
 input vclk,
 output [7:0] v1606a3
);
 localparam p3 = vbdfd7f;
 localparam p4 = vaf2e90;
 localparam p14 = v343c9c;
 localparam p20 = va55992;
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:6] w5;
 wire [0:6] w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire [0:7] w13;
 wire [0:3] w15;
 wire [0:3] w16;
 wire [0:7] w17;
 wire [0:7] w18;
 wire [0:7] w19;
 wire w21;
 wire w22;
 wire [0:7] w23;
 wire [0:7] w24;
 wire [0:7] w25;
 wire [0:3] w26;
 wire [0:2] w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 wire w34;
 wire w35;
 wire w36;
 wire w37;
 wire [0:7] w38;
 wire [0:7] w39;
 wire [0:7] w40;
 wire [0:7] w41;
 wire [0:7] w42;
 wire [0:7] w43;
 wire [0:7] w44;
 wire [0:7] w45;
 wire [0:7] w46;
 wire [0:7] w47;
 wire [0:7] w48;
 wire [0:7] w49;
 wire [0:7] w50;
 wire [0:7] w51;
 wire [0:7] w52;
 wire [0:7] w53;
 wire [0:7] w54;
 wire [0:7] w55;
 wire [0:7] w56;
 wire [0:7] w57;
 wire [0:7] w58;
 wire [0:3] w59;
 wire [0:3] w60;
 wire [0:7] w61;
 assign v1606a3 = w25;
 assign w28 = vedfc81;
 assign w29 = vclk;
 assign w30 = vclk;
 assign w31 = vclk;
 assign w32 = vclk;
 assign w33 = vclk;
 assign w34 = vclk;
 assign w35 = vclk;
 assign w36 = vclk;
 assign w37 = vclk;
 assign w9 = w7;
 assign w10 = w8;
 assign w12 = w7;
 assign w12 = w9;
 assign w19 = w18;
 assign w24 = w18;
 assign w24 = w19;
 assign w30 = w29;
 assign w31 = w29;
 assign w31 = w30;
 assign w32 = w29;
 assign w32 = w30;
 assign w32 = w31;
 assign w33 = w29;
 assign w33 = w30;
 assign w33 = w31;
 assign w33 = w32;
 assign w34 = w29;
 assign w34 = w30;
 assign w34 = w31;
 assign w34 = w32;
 assign w34 = w33;
 assign w35 = w29;
 assign w35 = w30;
 assign w35 = w31;
 assign w35 = w32;
 assign w35 = w33;
 assign w35 = w34;
 assign w36 = w29;
 assign w36 = w30;
 assign w36 = w31;
 assign w36 = w32;
 assign w36 = w33;
 assign w36 = w34;
 assign w36 = w35;
 assign w37 = w29;
 assign w37 = w30;
 assign w37 = w31;
 assign w37 = w32;
 assign w37 = w33;
 assign w37 = w34;
 assign w37 = w35;
 assign w37 = w36;
 assign w39 = w38;
 assign w40 = w38;
 assign w40 = w39;
 assign w41 = w38;
 assign w41 = w39;
 assign w41 = w40;
 assign w42 = w38;
 assign w42 = w39;
 assign w42 = w40;
 assign w42 = w41;
 assign w43 = w38;
 assign w43 = w39;
 assign w43 = w40;
 assign w43 = w41;
 assign w43 = w42;
 assign w44 = w38;
 assign w44 = w39;
 assign w44 = w40;
 assign w44 = w41;
 assign w44 = w42;
 assign w44 = w43;
 assign w45 = w38;
 assign w45 = w39;
 assign w45 = w40;
 assign w45 = w41;
 assign w45 = w42;
 assign w45 = w43;
 assign w45 = w44;
 assign w46 = w38;
 assign w46 = w39;
 assign w46 = w40;
 assign w46 = w41;
 assign w46 = w42;
 assign w46 = w43;
 assign w46 = w44;
 assign w46 = w45;
 assign w48 = w47;
 assign w49 = w47;
 assign w49 = w48;
 assign w50 = w47;
 assign w50 = w48;
 assign w50 = w49;
 assign w51 = w47;
 assign w51 = w48;
 assign w51 = w49;
 assign w51 = w50;
 assign w52 = w47;
 assign w52 = w48;
 assign w52 = w49;
 assign w52 = w50;
 assign w52 = w51;
 v36136f v9c0583 (
  .v5be714(w39),
  .v593755(w48),
  .vd006e6(w58)
 );
 v323be2 v8d26ea (
  .v3515d4(w0),
  .v9bea93(w47)
 );
 v7d7474 v463ed3 (
  .ve41da3(w0),
  .v9c083a(w1)
 );
 v36136f v5162af (
  .v593755(w1),
  .v5be714(w38),
  .vd006e6(w57)
 );
 v49d51e v079baa (
  .vcd2a33(w18),
  .v3f3f35(w19),
  .vbdd51f(w24),
  .v3fb88b(w25),
  .v71c62f(w53),
  .va541fd(w54),
  .v9b8a50(w55),
  .v30db33(w56),
  .v062092(w57),
  .v3d1227(w58),
  .ve81325(w60),
  .v21e136(w61)
 );
 v85651a v4cbc10 (
  .vea7b5b(w41),
  .vc96239(w50),
  .v274c22(w56)
 );
 v323be2 v8aaa88 (
  .v9bea93(w2),
  .v3515d4(w55)
 );
 v85651a va97cda (
  .v274c22(w2),
  .vea7b5b(w40),
  .vc96239(w49)
 );
 v5ad97e #(
  .vc5c8ea(p3)
 ) vccafb8 (
  .v26dbdb(w38)
 );
 v5ad97e #(
  .vc5c8ea(p4)
 ) vbd7a11 (
  .v26dbdb(w47)
 );
 vaf6fc9 vc28ca2 (
  .vb61f66(w5),
  .va191ad(w53)
 );
 vc80943 v1c5272 (
  .v1ec852(w5),
  .v595263(w43)
 );
 v6348d5 vfe0c23 (
  .vcff9d0(w6),
  .v869a97(w54)
 );
 vc80943 vf02328 (
  .v1ec852(w6),
  .v595263(w42)
 );
 v27fd6d v969833 (
  .v18e78c(w8),
  .v9892c7(w45),
  .v9f69ad(w52)
 );
 va21ae0 v27b412 (
  .v18e78c(w7),
  .v4145bb(w44),
  .v40cb98(w51)
 );
 v24496a v19d644 (
  .v0e28cb(w7),
  .v3ca442(w8),
  .vcbab45(w11)
 );
 v528969 v3d234d (
  .v0e28cb(w11),
  .v3ca442(w12)
 );
 v528969 v189513 (
  .v0e28cb(w9),
  .v3ca442(w10)
 );
 v73403c vc8ac64 (
  .v595263(w13),
  .v85accc(w59),
  .vf9119c(w60)
 );
 v917222 vc452f0 (
  .va191ad(w13),
  .v766044(w15),
  .v285646(w26)
 );
 v9274d3 #(
  .vc5c8ea(p14)
 ) v4b7799 (
  .v00a92d(w15)
 );
 v36136f v8a3dd4 (
  .v593755(w17),
  .v5be714(w46),
  .vd006e6(w61)
 );
 v917222 va00ecb (
  .v285646(w16),
  .va191ad(w17),
  .v766044(w59)
 );
 va0b8df v86e452 (
  .va50a91(w16)
 );
 v3bf99b v879e1d (
  .vb096dc(w18)
 );
 v05e8eb #(
  .v5a4ee6(p20)
 ) v73cb61 (
  .v23dc54(w21),
  .va136b0(w22),
  .v157610(w23),
  .v922e3d(w29)
 );
 v21cfcc vb81b31 (
  .v9fb85f(w21)
 );
 v725b7e v428a79 (
  .v9fb85f(w22)
 );
 v3bf99b vf6a646 (
  .vb096dc(w23)
 );
 v7b7bde vd77bf9 (
  .v8b7d6a(w26),
  .vc2f87e(w27),
  .vff92c6(w28)
 );
 vecef7f v5bab94 (
  .va66214(w27)
 );
 v89d234 ve5fc17 (
  .v41eb95(w30)
 );
 v89d234 v690dc1 (
  .v41eb95(w31)
 );
 v89d234 v5fff13 (
  .v41eb95(w32)
 );
 v89d234 v7077a1 (
  .v41eb95(w33)
 );
 v89d234 v99b333 (
  .v41eb95(w34)
 );
 v89d234 v310ac4 (
  .v41eb95(w35)
 );
 v89d234 v52ae66 (
  .v41eb95(w36)
 );
 v89d234 v8fbe3d (
  .v41eb95(w37)
 );
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v36136f (
 input [7:0] v5be714,
 input [7:0] v593755,
 output v654087,
 output [7:0] vd006e6
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 assign v654087 = w0;
 assign w1 = v593755;
 assign vd006e6 = w2;
 assign w3 = v5be714;
 v36136f_va0c26a va0c26a (
  .c(w0),
  .b(w1),
  .s(w2),
  .a(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- sum-2p-8bits-carry  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sumador  de 8 bits, con acarreo
/*-------------------------------------------------*/

module v36136f_va0c26a (
 input [7:0] a,
 input [7:0] b,
 output c,
 output [7:0] s
);
 wire [8:0] temp;
 assign temp = {1'b0, a} + {1'b0, b};
 assign s = temp[7:0];
 assign c = temp[8];
 //--test
endmodule
//---- Top entity
module v323be2 (
 input [7:0] v9bea93,
 output [7:0] v3515d4
);
 wire [0:7] w0;
 wire [0:7] w1;
 assign w0 = v9bea93;
 assign v3515d4 = w1;
 v323be2_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOT-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta NOT para bus de 8 bits
/*-------------------------------------------------*/

module v323be2_vd54ca1 (
 input [7:0] a,
 output [7:0] c
);
 //-- Puerta NOT
 
 //-- module (input wire a, output wire c);
 
 
 assign c = ~a;
 
 
 //-- endmodule
 
endmodule
//---- Top entity
module v7d7474 #(
 parameter v8d305c = 1
) (
 input [7:0] ve41da3,
 output [7:0] v9c083a
);
 localparam p0 = v8d305c;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w1 = ve41da3;
 assign v9c083a = w2;
 v7d7474_va0c26a #(
  .k(p0)
 ) va0c26a (
  .a(w1),
  .s(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- sum-1op-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sumador de un operando de 8 bits con una constante pasada como parámetro (No hay accarreo)
/*-------------------------------------------------*/

module v7d7474_va0c26a #(
 parameter k = 0
) (
 input [7:0] a,
 output [7:0] s
);
 assign s = a + k;
endmodule
//---- Top entity
module v49d51e (
 input [7:0] v732d31,
 input [7:0] vb4ed69,
 input [7:0] vd48707,
 input [7:0] vb6bab2,
 input [7:0] v3f3f35,
 input [7:0] vcd2a33,
 input [7:0] v31c944,
 input [7:0] v06410a,
 input [7:0] v71c62f,
 input [7:0] va541fd,
 input [7:0] v9b8a50,
 input [7:0] v30db33,
 input [7:0] vbdd51f,
 input [7:0] v21e136,
 input [7:0] v062092,
 input [7:0] v3d1227,
 input [3:0] ve81325,
 output [7:0] v3fb88b
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:7] w5;
 wire [0:7] w6;
 wire [0:7] w7;
 wire [0:7] w8;
 wire [0:7] w9;
 wire [0:7] w10;
 wire [0:7] w11;
 wire [0:7] w12;
 wire [0:7] w13;
 wire [0:7] w14;
 wire [0:7] w15;
 wire [0:7] w16;
 wire [0:3] w17;
 assign v3fb88b = w0;
 assign w1 = v062092;
 assign w2 = v3d1227;
 assign w3 = v21e136;
 assign w4 = vbdd51f;
 assign w5 = v30db33;
 assign w6 = v71c62f;
 assign w7 = va541fd;
 assign w8 = v9b8a50;
 assign w9 = v06410a;
 assign w10 = v31c944;
 assign w11 = vcd2a33;
 assign w12 = v3f3f35;
 assign w13 = vb6bab2;
 assign w14 = vd48707;
 assign w15 = vb4ed69;
 assign w16 = v732d31;
 assign w17 = ve81325;
 v49d51e_ve4e0df ve4e0df (
  .o(w0),
  .i1(w1),
  .i0(w2),
  .i2(w3),
  .i3(w4),
  .i4(w5),
  .i7(w6),
  .i6(w7),
  .i5(w8),
  .i8(w9),
  .i9(w10),
  .i10(w11),
  .i11(w12),
  .i12(w13),
  .i13(w14),
  .i14(w15),
  .i15(w16),
  .s(w17)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux-16-1- 8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 16 a 1 de 8 bits
/*-------------------------------------------------*/

module v49d51e_ve4e0df (
 input [7:0] i15,
 input [7:0] i14,
 input [7:0] i13,
 input [7:0] i12,
 input [7:0] i11,
 input [7:0] i10,
 input [7:0] i9,
 input [7:0] i8,
 input [7:0] i7,
 input [7:0] i6,
 input [7:0] i5,
 input [7:0] i4,
 input [7:0] i3,
 input [7:0] i2,
 input [7:0] i1,
 input [7:0] i0,
 input [3:0] s,
 output [7:0] o
);
 //-- Multiplexor de 16 a 1, 
 //-- de 8 bits
 
 assign o = (s == 4'h0) ? i0 :
            (s == 4'h1) ? i1 :
            (s == 4'h2) ? i2 : 
            (s == 4'h3) ? i3 :
            (s == 4'h4) ? i4 :
            (s == 4'h5) ? i5 :
            (s == 4'h6) ? i6 :
            (s == 4'h7) ? i7 :
            (s == 4'h8) ? i8 :
            (s == 4'h9) ? i9 :
            (s == 4'ha) ? i10 : 
            (s == 4'hb) ? i11 :
            (s == 4'hc) ? i12 :
            (s == 4'hd) ? i13 :
            (s == 4'he) ? i14 :
            (s == 4'hf) ? i15 :
            4'h0;
            
 
 
endmodule
//---- Top entity
module v85651a (
 input [7:0] vea7b5b,
 input [7:0] vc96239,
 output [7:0] v274c22
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w0 = vea7b5b;
 assign v274c22 = w1;
 assign w2 = vc96239;
 v85651a_vce9fab vce9fab (
  .a(w0),
  .o(w1),
  .b(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND-8  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- AND bit a bit entre dos buses de 8 bits
/*-------------------------------------------------*/

module v85651a_vce9fab (
 input [7:0] a,
 input [7:0] b,
 output [7:0] o
);
 assign o = a & b;
 
endmodule
//---- Top entity
module v5ad97e #(
 parameter vc5c8ea = 0
) (
 output [7:0] v26dbdb
);
 localparam p0 = vc5c8ea;
 wire [0:7] w1;
 assign v26dbdb = w1;
 v5ad97e_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Constante-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor genérico constante, de 8 bits. Su valor se introduce como parámetro. Por defecto vale 0
/*-------------------------------------------------*/

module v5ad97e_v465065 #(
 parameter VALUE = 0
) (
 output [7:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module vaf6fc9 (
 input v4ef985,
 input [6:0] vb61f66,
 output [7:0] va191ad
);
 wire [0:6] w0;
 wire w1;
 wire [0:7] w2;
 assign w0 = vb61f66;
 assign w1 = v4ef985;
 assign va191ad = w2;
 vaf6fc9_v9a2a06 v9a2a06 (
  .i0(w0),
  .i1(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 1 cable y un bus de 7-bits a bus de 8-bits
/*-------------------------------------------------*/

module vaf6fc9_v9a2a06 (
 input i1,
 input [6:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vc80943 (
 input [7:0] v595263,
 output v57076f,
 output [6:0] v1ec852
);
 wire [0:7] w0;
 wire w1;
 wire [0:6] w2;
 assign w0 = v595263;
 assign v57076f = w1;
 assign v1ec852 = w2;
 vc80943_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus-1-7  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 8-bits en 2 buses de 1 y 7 bits
/*-------------------------------------------------*/

module vc80943_v9a2a06 (
 input [7:0] i,
 output o1,
 output [6:0] o0
);
 assign o1 = i[7];
 assign o0 = i[6:0];
endmodule
//---- Top entity
module v6348d5 (
 input [6:0] vcff9d0,
 input v428b2b,
 output [7:0] v869a97
);
 wire [0:6] w0;
 wire w1;
 wire [0:7] w2;
 assign w0 = vcff9d0;
 assign w1 = v428b2b;
 assign v869a97 = w2;
 v6348d5_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de un bus de 7 bits y un cable a bus de 8-bits
/*-------------------------------------------------*/

module v6348d5_v9a2a06 (
 input [6:0] i1,
 input i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v27fd6d (
 input [7:0] v9892c7,
 input [7:0] v9f69ad,
 output v18e78c
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign v18e78c = w0;
 assign w1 = v9f69ad;
 assign w2 = v9892c7;
 v27fd6d_vd75681 vd75681 (
  .eq(w0),
  .b(w1),
  .a(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Menor-que-2-op  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comparador menor que, de dos operandos de 8 bits
/*-------------------------------------------------*/

module v27fd6d_vd75681 (
 input [7:0] a,
 input [7:0] b,
 output eq
);
 assign eq = (a < b);
endmodule
//---- Top entity
module va21ae0 (
 input [7:0] v4145bb,
 input [7:0] v40cb98,
 output v18e78c
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign v18e78c = w0;
 assign w1 = v40cb98;
 assign w2 = v4145bb;
 va21ae0_vd75681 vd75681 (
  .eq(w0),
  .b(w1),
  .a(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Comparador de dos operandos  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comparador de dos operandos de 8 bits
/*-------------------------------------------------*/

module va21ae0_vd75681 (
 input [7:0] a,
 input [7:0] b,
 output eq
);
 assign eq = (a == b);
endmodule
//---- Top entity
module v24496a (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v24496a_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOR  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- NOR logic gate
/*-------------------------------------------------*/

module v24496a_vf4938a (
 input a,
 input b,
 output c
);
 // NOR logic gate
 
 assign c = ~(a | b);
endmodule
//---- Top entity
module v528969 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v528969_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- OR  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- OR logic gate
/*-------------------------------------------------*/

module v528969_vf4938a (
 input a,
 input b,
 output c
);
 // OR logic gate
 
 assign c = a | b;
endmodule
//---- Top entity
module v73403c (
 input [7:0] v595263,
 output [3:0] vf9119c,
 output [3:0] v85accc
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 assign vf9119c = w0;
 assign v85accc = w1;
 assign w2 = v595263;
 v73403c_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 8-bits en buses de 4 bits
/*-------------------------------------------------*/

module v73403c_v9a2a06 (
 input [7:0] i,
 output [3:0] o1,
 output [3:0] o0
);
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module v917222 (
 input [3:0] v285646,
 input [3:0] v766044,
 output [7:0] va191ad
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 assign w0 = v766044;
 assign w1 = v285646;
 assign va191ad = w2;
 v917222_v9a2a06 v9a2a06 (
  .i0(w0),
  .i1(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 2 buses de 4-bits a bus de 8-bits
/*-------------------------------------------------*/

module v917222_v9a2a06 (
 input [3:0] i1,
 input [3:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v9274d3 #(
 parameter vc5c8ea = 0
) (
 output [3:0] v00a92d
);
 localparam p1 = vc5c8ea;
 wire [0:3] w0;
 assign v00a92d = w0;
 v9274d3_v465065 #(
  .VALUE(p1)
 ) v465065 (
  .k(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- Constante-4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor genérico constante, de 4 bits. Su valor se introduce como parámetro. Por defecto vale 0
/*-------------------------------------------------*/

module v9274d3_v465065 #(
 parameter VALUE = 0
) (
 output [3:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module va0b8df #(
 parameter vfffc23 = 0
) (
 output [3:0] va50a91
);
 localparam p0 = vfffc23;
 wire [0:3] w1;
 assign va50a91 = w1;
 v9274d3 #(
  .vc5c8ea(p0)
 ) v8800c6 (
  .v00a92d(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_0_4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 0 para bus de 4 bits
/*-------------------------------------------------*/
//---- Top entity
module v3bf99b #(
 parameter vfffc23 = 0
) (
 output [7:0] vb096dc
);
 localparam p0 = vfffc23;
 wire [0:7] w1;
 assign vb096dc = w1;
 v5ad97e #(
  .vc5c8ea(p0)
 ) v68b2cc (
  .v26dbdb(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_0_8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 0 para bus de 8 bits
/*-------------------------------------------------*/
//---- Top entity
module v05e8eb #(
 parameter v5a4ee6 = "v5a4ee6.list"
) (
 input v922e3d,
 input [7:0] v157610,
 input [7:0] vcc2c4f,
 input v23dc54,
 input va136b0,
 output [7:0] vba32a6
);
 localparam p5 = v5a4ee6;
 wire [0:7] w0;
 wire [0:7] w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:7] w6;
 assign vba32a6 = w0;
 assign w1 = vcc2c4f;
 assign w2 = v922e3d;
 assign w3 = va136b0;
 assign w4 = v23dc54;
 assign w6 = v157610;
 v05e8eb_vbaa912 #(
  .ROMF(p5)
 ) vbaa912 (
  .data_out(w0),
  .data_in(w1),
  .clk(w2),
  .cs(w3),
  .wr(w4),
  .addr(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- Memory-256B  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 256 bytes memory
/*-------------------------------------------------*/

module v05e8eb_vbaa912 #(
 parameter ROMF = 0
) (
 input clk,
 input [7:0] addr,
 input [7:0] data_in,
 input wr,
 input cs,
 output [7:0] data_out
);
 //-- Anchura del bus de direcciones
 localparam ADDR_WIDTH = 8;
 
 //-- Tamano de la memoria
 localparam TAM = 1 << ADDR_WIDTH;
 
 //-- NO inicializar!
 //-- Si se inicializa a 0 o cualquier otro
 //-- valor no se infiere una RAM
 reg data_out;
 
 //-- Array para la memoria
 reg [7:0] mem_8 [0:TAM-1];
 
 //-- Puerto de lectura
 //-- Para que se infiera una RAM
 //-- debe ser una lectura sincrona
 always @(posedge clk)
 begin
     //-- Puerto de lectura
     if (cs & !wr) data_out <= mem_8[addr];
     
     //-- Puerto de escritura
     if (cs & wr) mem_8[addr] <= data_in;
 end
 
 
 //-- Inicializacion de la memoria
 initial begin
   
   if (ROMF)
     $readmemh(ROMF, mem_8, 0, TAM-1);
   
 end
 
 
 
 
endmodule
//---- Top entity
module v21cfcc (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v21cfcc_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 0  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 0
/*-------------------------------------------------*/

module v21cfcc_vb2eccd (
 output q
);
 //-- Bit constante a 0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module v725b7e (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v725b7e_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 1
/*-------------------------------------------------*/

module v725b7e_vb2eccd (
 output q
);
 //-- Bit constante a 1
 assign q = 1'b1;
 
 
endmodule
//---- Top entity
module v7b7bde (
 input [2:0] vc2f87e,
 input vff92c6,
 output [3:0] v8b7d6a
);
 wire [0:3] w0;
 wire [0:2] w1;
 wire w2;
 assign v8b7d6a = w0;
 assign w1 = vc2f87e;
 assign w2 = vff92c6;
 v7b7bde_v9a2a06 v9a2a06 (
  .o(w0),
  .i1(w1),
  .i0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus-3-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de buses de 3 y 1-bits a a bus de 4-bits
/*-------------------------------------------------*/

module v7b7bde_v9a2a06 (
 input [2:0] i1,
 input i0,
 output [3:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vecef7f #(
 parameter vfffc23 = 0
) (
 output [2:0] va66214
);
 localparam p0 = vfffc23;
 wire [0:2] w1;
 assign va66214 = w1;
 vbe878c #(
  .vc5c8ea(p0)
 ) v7f3234 (
  .v8cf592(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_0_3bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 0 para bus de 3 bits
/*-------------------------------------------------*/
//---- Top entity
module vbe878c #(
 parameter vc5c8ea = 0
) (
 output [2:0] v8cf592
);
 localparam p0 = vc5c8ea;
 wire [0:2] w1;
 assign v8cf592 = w1;
 vbe878c_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Constante-3bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor genérico constante, de 3 bits. Su valor se introduce como parámetro. Por defecto vale 0
/*-------------------------------------------------*/

module vbe878c_v465065 #(
 parameter VALUE = 0
) (
 output [2:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module v89d234 #(
 parameter v422d28 = 0
) (
 input v41eb95,
 input [7:0] v39f831,
 input vf892a0,
 output [7:0] vb1c024
);
 localparam p0 = v422d28;
 wire [0:7] w1;
 wire [0:7] w2;
 wire w3;
 wire w4;
 assign vb1c024 = w1;
 assign w2 = v39f831;
 assign w3 = vf892a0;
 assign w4 = v41eb95;
 v89d234_v9148cb #(
  .INI(p0)
 ) v9148cb (
  .q(w1),
  .d(w2),
  .load(w3),
  .clk(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Registro  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Registro de 8 bits
/*-------------------------------------------------*/

module v89d234_v9148cb #(
 parameter INI = 0
) (
 input clk,
 input [7:0] d,
 input load,
 output [7:0] q
);
 localparam N = 8;
 
 reg [N-1:0] q = INI;
 
 always @(posedge clk)
   if (load)
     q <= d;
endmodule
