// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main #(
 parameter v8adaf5 = "I",
 parameter v0875c1 = "0",
 parameter v9c814a = "a",
 parameter vf8402d = "q",
 parameter v62c0b1 = "$",
 parameter ved3522 = "J",
 parameter v95da66 = "1",
 parameter v39115b = "b",
 parameter v0ddf49 = "r",
 parameter v21495b = "%",
 parameter v63471f = "K",
 parameter vc953fc = "2",
 parameter vb05424 = "c",
 parameter v6bd99b = "s",
 parameter v8a9a31 = "&",
 parameter vcdd60f = "a",
 parameter v3b4148 = "L",
 parameter v1fc0e0 = "3",
 parameter v92927e = "d",
 parameter vc5a51e = "t",
 parameter vc6a49e = "(",
 parameter vcce894 = "b",
 parameter v6fc121 = "M",
 parameter v7ddd93 = "4",
 parameter vc6edbd = "e",
 parameter v294d9d = "u",
 parameter vf87f7e = ")",
 parameter va2d5d7 = "c",
 parameter v776a63 = "N",
 parameter vf7a0ae = "5",
 parameter ve83e9c = "f",
 parameter vc9cfd0 = "v",
 parameter v8d553a = "*",
 parameter v931ab5 = "d",
 parameter v6a1dfc = "O",
 parameter vefb4cf = "6",
 parameter vf1452c = "g",
 parameter ve3f110 = "w",
 parameter v58d031 = "+",
 parameter v433452 = "P",
 parameter vee1805 = "7",
 parameter v07c18f = "h",
 parameter vbd1898 = "x",
 parameter v08f408 = ",",
 parameter va6f62c = "e",
 parameter v5e2e46 = "Q",
 parameter v4ec583 = "8",
 parameter v734929 = "i",
 parameter vbe37a1 = "A",
 parameter v1e8ba0 = "-",
 parameter v7a056c = "f",
 parameter va47aa1 = "R",
 parameter v2d1ede = "9",
 parameter vd7bf58 = "j",
 parameter vee96ee = "B",
 parameter v7f2fe0 = ".",
 parameter va2f5d0 = "g",
 parameter vd4011e = "S",
 parameter vc3cdd7 = "y",
 parameter v1ff17c = "k",
 parameter vab65f2 = "C",
 parameter v7f75ca = "/",
 parameter vb294cb = "h",
 parameter v00f73e = "T",
 parameter v0f8279 = "z",
 parameter v14bca1 = "l",
 parameter v095d00 = "D",
 parameter va64e5f = ":",
 parameter v9c958f = "U",
 parameter v3b5fca = "Y",
 parameter v3c07df = "m",
 parameter v73ec36 = "E",
 parameter v4fbbbe = ";",
 parameter v68b2af = "V",
 parameter v0c4825 = "Z",
 parameter v3318b2 = "n",
 parameter vc10849 = "F",
 parameter v060d2b = "<",
 parameter vd355d6 = "W",
 parameter v13f65a = "!",
 parameter v1d1e0a = "o",
 parameter v664405 = "G",
 parameter v399ee9 = "=",
 parameter v285ae3 = "X",
 parameter v56d6da = "#",
 parameter vc3bbe3 = "p",
 parameter ve7782e = "H",
 parameter vfad6d4 = ">"
) (
 input v0874a9,
 input v6b9071,
 input [7:0] vbe72c7,
 input [7:0] v790816,
 input [7:0] vaa06ba,
 input [7:0] v502295,
 input [7:0] vb11937,
 input [7:0] vc3aa93,
 input [7:0] v034e1f,
 input [7:0] v505830,
 input [7:0] v4d9712,
 input [7:0] vb239bb,
 output v7a5bc2,
 output [7:0] vaa3650,
 output [0:7] vinit
);
 localparam p2 = va6f62c;
 localparam p3 = v7a056c;
 localparam p4 = va2f5d0;
 localparam p5 = vb294cb;
 localparam p8 = vcdd60f;
 localparam p9 = vcce894;
 localparam p10 = va2d5d7;
 localparam p11 = v931ab5;
 localparam p13 = vf8402d;
 localparam p14 = v0ddf49;
 localparam p15 = v6bd99b;
 localparam p16 = vc5a51e;
 localparam p17 = v294d9d;
 localparam p18 = vc9cfd0;
 localparam p19 = ve3f110;
 localparam p20 = vbd1898;
 localparam p21 = vbe37a1;
 localparam p22 = vee96ee;
 localparam p23 = vab65f2;
 localparam p24 = v095d00;
 localparam p25 = v73ec36;
 localparam p26 = vc10849;
 localparam p27 = v664405;
 localparam p28 = ve7782e;
 localparam p30 = v8adaf5;
 localparam p31 = ved3522;
 localparam p32 = v63471f;
 localparam p33 = v3b4148;
 localparam p34 = v6fc121;
 localparam p35 = v776a63;
 localparam p36 = v6a1dfc;
 localparam p37 = v433452;
 localparam p38 = v5e2e46;
 localparam p39 = va47aa1;
 localparam p40 = vd4011e;
 localparam p41 = v00f73e;
 localparam p42 = v9c958f;
 localparam p43 = v68b2af;
 localparam p44 = vd355d6;
 localparam p45 = v285ae3;
 localparam p46 = v0875c1;
 localparam p47 = v95da66;
 localparam p48 = vc953fc;
 localparam p49 = v1fc0e0;
 localparam p50 = v7ddd93;
 localparam p51 = vf7a0ae;
 localparam p52 = vefb4cf;
 localparam p53 = vee1805;
 localparam p54 = v4ec583;
 localparam p55 = v2d1ede;
 localparam p56 = vc3cdd7;
 localparam p57 = v0f8279;
 localparam p58 = v3b5fca;
 localparam p59 = v0c4825;
 localparam p60 = v13f65a;
 localparam p61 = v56d6da;
 localparam p68 = v62c0b1;
 localparam p69 = v21495b;
 localparam p70 = v8a9a31;
 localparam p71 = vc6a49e;
 localparam p72 = vf87f7e;
 localparam p73 = v8d553a;
 localparam p74 = v58d031;
 localparam p75 = v08f408;
 localparam p76 = v1e8ba0;
 localparam p77 = v7f2fe0;
 localparam p78 = v7f75ca;
 localparam p79 = va64e5f;
 localparam p80 = v4fbbbe;
 localparam p81 = v060d2b;
 localparam p82 = v399ee9;
 localparam p83 = vfad6d4;
 wire w0;
 wire [0:10] w1;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w12;
 wire [0:17] w29;
 wire [0:17] w62;
 wire [0:17] w63;
 wire [0:15] w64;
 wire [0:15] w65;
 wire [0:15] w66;
 wire [0:15] w67;
 wire [0:17] w84;
 wire [0:17] w85;
 wire [0:15] w86;
 wire [0:7] w87;
 wire [0:7] w88;
 wire [0:7] w89;
 wire [0:7] w90;
 wire [0:7] w91;
 wire [0:7] w92;
 wire [0:7] w93;
 wire [0:7] w94;
 wire [0:7] w95;
 wire [0:7] w96;
 wire [0:7] w97;
 wire w98;
 wire w99;
 wire w100;
 wire w101;
 wire w102;
 wire w103;
 wire w104;
 assign w0 = v6b9071;
 assign v7a5bc2 = w12;
 assign w87 = vbe72c7;
 assign w88 = v790816;
 assign w89 = vaa06ba;
 assign w90 = v502295;
 assign w91 = vb11937;
 assign w92 = vc3aa93;
 assign w93 = v034e1f;
 assign w94 = v505830;
 assign w95 = v4d9712;
 assign w96 = vb239bb;
 assign vaa3650 = w97;
 assign w98 = v0874a9;
 assign w99 = v0874a9;
 assign w100 = v0874a9;
 assign w101 = v0874a9;
 assign w102 = v0874a9;
 assign w103 = v0874a9;
 assign w104 = v0874a9;
 assign w99 = w98;
 assign w100 = w98;
 assign w100 = w99;
 assign w101 = w98;
 assign w101 = w99;
 assign w101 = w100;
 assign w102 = w98;
 assign w102 = w99;
 assign w102 = w100;
 assign w102 = w101;
 assign w103 = w98;
 assign w103 = w99;
 assign w103 = w100;
 assign w103 = w101;
 assign w103 = w102;
 assign w104 = w98;
 assign w104 = w99;
 assign w104 = w100;
 assign w104 = w101;
 assign w104 = w102;
 assign w104 = w103;
 v4c663f #(
  .v7ab8da(p8),
  .vf10655(p9),
  .v8b4198(p10),
  .v89f607(p11)
 ) v16a72c (
  .vfd7d50(w0),
  .va8b46c(w1),
  .vc9f895(w6),
  .v479d8c(w98)
 );
 v24ca99 #(
  .v7ab8da(p2),
  .vf10655(p3),
  .v8b4198(p4),
  .v89f607(p5)
 ) v5f759b (
  .vfd0650(w1),
  .vc9f895(w7),
  .v479d8c(w99)
 );
 v917222 vf1215e (
  .v285646(w6),
  .v766044(w7),
  .va191ad(w97)
 );
 v8eed06 v5cab61 (
  .va5c2ac(w12),
  .v954064(w29),
  .v4dd039(w64),
  .vb7eca5(w85),
  .v294f2a(w100)
 );
 v56b4c6 #(
  .v11a07f(p13),
  .vd1c7d9(p14),
  .v077ede(p15),
  .va86b54(p16),
  .v128381(p17),
  .vdc93ce(p18),
  .va57579(p19),
  .ve245ce(p20),
  .v3a4133(p21),
  .va79108(p22),
  .v16f1c7(p23),
  .v7afcff(p24),
  .vbbb21b(p25),
  .v6ac546(p26),
  .vadaccd(p27),
  .v455918(p28)
 ) v53f811 (
  .vb7eca5(w29),
  .v954064(w62),
  .v4dd039(w65),
  .v294f2a(w101)
 );
 v56b4c6 #(
  .v11a07f(p30),
  .vd1c7d9(p31),
  .v077ede(p32),
  .va86b54(p33),
  .v128381(p34),
  .vdc93ce(p35),
  .va57579(p36),
  .ve245ce(p37),
  .v3a4133(p38),
  .va79108(p39),
  .v16f1c7(p40),
  .v7afcff(p41),
  .vbbb21b(p42),
  .v6ac546(p43),
  .vadaccd(p44),
  .v455918(p45)
 ) ve99bca (
  .vb7eca5(w62),
  .v954064(w63),
  .v4dd039(w66),
  .v294f2a(w102)
 );
 v56b4c6 #(
  .v11a07f(p46),
  .vd1c7d9(p47),
  .v077ede(p48),
  .va86b54(p49),
  .v128381(p50),
  .vdc93ce(p51),
  .va57579(p52),
  .ve245ce(p53),
  .v3a4133(p54),
  .va79108(p55),
  .v16f1c7(p56),
  .v7afcff(p57),
  .vbbb21b(p58),
  .v6ac546(p59),
  .vadaccd(p60),
  .v455918(p61)
 ) v439b57 (
  .vb7eca5(w63),
  .v4dd039(w67),
  .v954064(w84),
  .v294f2a(w103)
 );
 v1e224f v89d40b (
  .v4d4dee(w64),
  .vd34531(w87),
  .v385b9c(w88)
 );
 v1e224f va6ccb8 (
  .v4d4dee(w65),
  .vd34531(w89),
  .v385b9c(w90)
 );
 v1e224f vab827c (
  .v4d4dee(w66),
  .vd34531(w91),
  .v385b9c(w92)
 );
 v1e224f v7b1e70 (
  .v4d4dee(w67),
  .vd34531(w93),
  .v385b9c(w94)
 );
 v56b4c6 #(
  .v11a07f(p68),
  .vd1c7d9(p69),
  .v077ede(p70),
  .va86b54(p71),
  .v128381(p72),
  .vdc93ce(p73),
  .va57579(p74),
  .ve245ce(p75),
  .v3a4133(p76),
  .va79108(p77),
  .v16f1c7(p78),
  .v7afcff(p79),
  .vbbb21b(p80),
  .v6ac546(p81),
  .vadaccd(p82),
  .v455918(p83)
 ) v8fe9c6 (
  .vb7eca5(w84),
  .v954064(w85),
  .v4dd039(w86),
  .v294f2a(w104)
 );
 v1e224f vc683b1 (
  .v4d4dee(w86),
  .vd34531(w95),
  .v385b9c(w96)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v4c663f #(
 parameter v7ab8da = "a",
 parameter vf10655 = "b",
 parameter v8b4198 = "c",
 parameter v89f607 = "d"
) (
 input v479d8c,
 input vfd7d50,
 input v5184d8,
 input v0fcc86,
 input vec5765,
 output [3:0] v4b620e,
 output [10:0] va8b46c,
 output [3:0] vc9f895,
 output [3:0] vc92856,
 output [3:0] v1d7c1a
);
 localparam p0 = v7ab8da;
 localparam p2 = v8b4198;
 localparam p4 = vf10655;
 localparam p5 = v89f607;
 wire [0:10] w1;
 wire w3;
 wire w6;
 wire w7;
 wire [0:3] w8;
 wire [0:10] w9;
 wire [0:1] w10;
 wire [0:1] w11;
 wire [0:3] w12;
 wire [0:1] w13;
 wire [0:1] w14;
 wire [0:1] w15;
 wire [0:1] w16;
 wire [0:3] w17;
 wire [0:1] w18;
 wire [0:1] w19;
 wire [0:3] w20;
 assign w3 = vfd7d50;
 assign w6 = v479d8c;
 assign w7 = v479d8c;
 assign v4b620e = w8;
 assign va8b46c = w9;
 assign vc9f895 = w12;
 assign vc92856 = w17;
 assign v1d7c1a = w20;
 assign w7 = w6;
 v7d59c6 #(
  .v7ab8da(p2),
  .vfa9d9d(p5)
 ) v554919 (
  .v0531e9(w1),
  .v479d8c(w7),
  .va8b46c(w9),
  .vfcdec9(w11),
  .ve64ec1(w13),
  .v4d6cf3(w15),
  .v07aeec(w18)
 );
 vc0b252 #(
  .v7ab8da(p0),
  .vfa9d9d(p4)
 ) vd83deb (
  .va8b46c(w1),
  .vfd7d50(w3),
  .v479d8c(w6),
  .vfcdec9(w10),
  .ve64ec1(w14),
  .v4d6cf3(w16),
  .v07aeec(w19)
 );
 v91b7ac v8c0fd0 (
  .v8b7d6a(w8),
  .v30c67a(w10),
  .vbf5c47(w11)
 );
 v91b7ac v11b579 (
  .v8b7d6a(w12),
  .vbf5c47(w13),
  .v30c67a(w14)
 );
 v91b7ac v5ded3e (
  .vbf5c47(w15),
  .v30c67a(w16),
  .v8b7d6a(w17)
 );
 v91b7ac v36cfb3 (
  .vbf5c47(w18),
  .v30c67a(w19),
  .v8b7d6a(w20)
 );
endmodule

/*-------------------------------------------------*/
/*-- Switchx4-RX CLONE  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Four Virtual Switches. Receiving unit
/*-------------------------------------------------*/
//---- Top entity
module v7d59c6 #(
 parameter v7ab8da = "a",
 parameter vfa9d9d = "b"
) (
 input v479d8c,
 input [10:0] v0531e9,
 input v5184d8,
 input v0fcc86,
 input vec5765,
 output [1:0] vfcdec9,
 output [10:0] va8b46c,
 output [1:0] ve64ec1,
 output [1:0] v4d6cf3,
 output [1:0] v07aeec
);
 localparam p0 = v7ab8da;
 localparam p2 = vfa9d9d;
 wire [0:10] w1;
 wire [0:10] w3;
 wire w4;
 wire w5;
 wire [0:1] w6;
 wire w7;
 wire w8;
 wire [0:10] w9;
 wire [0:1] w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire [0:1] w15;
 wire w16;
 wire w17;
 wire [0:1] w18;
 assign w3 = v0531e9;
 assign w4 = v479d8c;
 assign w5 = v479d8c;
 assign vfcdec9 = w6;
 assign va8b46c = w9;
 assign ve64ec1 = w10;
 assign v4d6cf3 = w15;
 assign v07aeec = w18;
 assign w5 = w4;
 vb59e75 #(
  .v723ac3(p2)
 ) vd697c4 (
  .v051016(w1),
  .v5439ee(w5),
  .v0af42d(w8),
  .vca68f1(w9),
  .vd68cd9(w11),
  .v31581a(w13),
  .v12cda8(w17)
 );
 vd4bd04 vf18060 (
  .v67a3fc(w6),
  .vee8a83(w7),
  .v03aaf0(w8)
 );
 vd4bd04 v8fa168 (
  .v67a3fc(w10),
  .v03aaf0(w11),
  .vee8a83(w12)
 );
 vd4bd04 v0e0ad0 (
  .v03aaf0(w13),
  .vee8a83(w14),
  .v67a3fc(w15)
 );
 vd4bd04 vf9b396 (
  .vee8a83(w16),
  .v03aaf0(w17),
  .v67a3fc(w18)
 );
 vb59e75 #(
  .v723ac3(p0)
 ) v2dc197 (
  .vca68f1(w1),
  .v051016(w3),
  .v5439ee(w4),
  .v0af42d(w7),
  .vd68cd9(w12),
  .v31581a(w14),
  .v12cda8(w16)
 );
endmodule

/*-------------------------------------------------*/
/*-- Switchx2-Bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Two Virtual Switches. Bus unit
/*-------------------------------------------------*/
//---- Top entity
module vb59e75 #(
 parameter v723ac3 = "a"
) (
 input v5439ee,
 input [10:0] v051016,
 input v61f96e,
 input vfbdd9d,
 input v581a78,
 output v0af42d,
 output [10:0] vca68f1,
 output vd68cd9,
 output v31581a,
 output v12cda8
);
 localparam p0 = v723ac3;
 wire [0:7] w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:10] w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire [0:10] w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire [0:7] w25;
 wire w26;
 assign w5 = v051016;
 assign v31581a = w6;
 assign v12cda8 = w7;
 assign v0af42d = w8;
 assign w10 = v5439ee;
 assign w11 = v5439ee;
 assign w12 = v5439ee;
 assign w13 = v5439ee;
 assign w14 = v5439ee;
 assign vca68f1 = w15;
 assign w15 = v051016;
 assign vd68cd9 = w16;
 assign w9 = w8;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 assign w14 = w10;
 assign w14 = w11;
 assign w14 = w12;
 assign w14 = w13;
 assign w15 = w5;
 assign w17 = w16;
 assign w20 = w19;
 assign w22 = w21;
 assign w23 = w21;
 assign w23 = w22;
 vd48523 #(
  .vd07545(p0)
 ) v157473 (
  .vaabd0c(w1),
  .v4642b6(w2),
  .v6979aa(w14),
  .v55f634(w23),
  .v510842(w25),
  .vba398f(w26)
 );
 v041aa2 v7242b9 (
  .v510842(w1),
  .vba398f(w2),
  .v4642b6(w4),
  .v6979aa(w12),
  .v832531(w18),
  .v55f634(w22)
 );
 v45f630 v9ba3f8 (
  .vbbc50c(w3),
  .va4102a(w10),
  .ve8318d(w16),
  .vf54559(w18),
  .v9afc1f(w19)
 );
 v21cfcc ve2f9b5 (
  .v9fb85f(w3)
 );
 v1c7dae vec075a (
  .ve8318d(w8),
  .va4102a(w11),
  .vf54559(w20)
 );
 v46217c vb06e2a (
  .v68c0ef(w5),
  .v462094(w21),
  .v52bd29(w24),
  .v5b0467(w25),
  .v21f955(w26)
 );
 vd6c41f v224d00 (
  .vc76908(w4),
  .v0a3376(w13),
  .ve81fcc(w19),
  .v06e51b(w21),
  .v2308bf(w24)
 );
 ve108d0 vbff35c (
  .v8f3bff(w6),
  .v5399d1(w7),
  .v0e9572(w9),
  .vaf813b(w17)
 );
endmodule

/*-------------------------------------------------*/
/*-- Virtual-switch  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Virtual switch (1-bit). Bus block
/*-------------------------------------------------*/
//---- Top entity
module vd48523 #(
 parameter vd07545 = "s"
) (
 input v6979aa,
 input v55f634,
 input vfa2aa0,
 input [7:0] v510842,
 input vba398f,
 output v431286,
 output v804bc3,
 output v4a5941,
 output [7:0] vaabd0c,
 output v4642b6
);
 localparam p5 = vd07545;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire [0:7] w19;
 wire [0:7] w20;
 assign v804bc3 = w6;
 assign v431286 = w8;
 assign w10 = v6979aa;
 assign w11 = v6979aa;
 assign w12 = v6979aa;
 assign w13 = v55f634;
 assign w14 = v55f634;
 assign v4a5941 = w15;
 assign v4642b6 = w17;
 assign w18 = vba398f;
 assign vaabd0c = w19;
 assign w19 = v510842;
 assign w20 = v510842;
 assign w8 = w7;
 assign w9 = w7;
 assign w9 = w8;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w14 = w13;
 assign w16 = w15;
 assign w20 = w19;
 ve108d0 v99cfcc (
  .v5399d1(w0),
  .vaf813b(w9),
  .v8f3bff(w17),
  .v0e9572(w18)
 );
 vb959c2 ve67e34 (
  .ve68648(w1),
  .vb4c770(w7),
  .v581b48(w11),
  .v3c6908(w13)
 );
 ve108d0 v926805 (
  .v0e9572(w0),
  .v5399d1(w3),
  .vaf813b(w16)
 );
 vb959c2 v0f2ff8 (
  .ve68648(w2),
  .v581b48(w12),
  .v3c6908(w14),
  .vb4c770(w15)
 );
 ve108d0 v897263 (
  .v8f3bff(w1),
  .v5399d1(w2),
  .v0e9572(w3),
  .vaf813b(w4)
 );
 vca7316 #(
  .v6b316b(p5)
 ) v90e106 (
  .v18e78c(w4),
  .v40cb98(w20)
 );
 v8e2728 v664843 (
  .v2dffca(w6),
  .v10eedb(w7),
  .v0884a0(w10)
 );
endmodule

/*-------------------------------------------------*/
/*-- syntax-char  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- char syntax block
/*-------------------------------------------------*/
//---- Top entity
module ve108d0 (
 input v0e9572,
 input vaf813b,
 output v8f3bff,
 output v5399d1
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign v8f3bff = w0;
 assign v5399d1 = w1;
 assign w2 = vaf813b;
 assign w3 = v0e9572;
 ve108d0_v45bd49 v45bd49 (
  .o1(w0),
  .o0(w1),
  .sel(w2),
  .i(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Demux-1-2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Demultiplexor de 1 bit, de 1 a 2
/*-------------------------------------------------*/

module ve108d0_v45bd49 (
 input i,
 input sel,
 output o1,
 output o0
);
 assign {o1,o0} = i << sel;
 
endmodule
//---- Top entity
module vb959c2 #(
 parameter v679341 = 0
) (
 input v581b48,
 input ve68648,
 input v3c6908,
 output vb4c770
);
 localparam p4 = v679341;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w0 = v581b48;
 assign w1 = ve68648;
 assign w2 = v3c6908;
 assign vb4c770 = w3;
 vb959c2_v4e11b3 #(
  .INI(p4)
 ) v4e11b3 (
  .clk(w0),
  .set(w1),
  .rst(w2),
  .q(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Biestable-Set-Reset  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Biestable con entradas de Set y Reset síncronas, para poner y quitar notaficaciones de eventos
/*-------------------------------------------------*/

module vb959c2_v4e11b3 #(
 parameter INI = 0
) (
 input clk,
 input set,
 input rst,
 output q
);
 reg q = INI;
 
 always @(posedge clk)
   if (set)
     q <= 1'b1;
   else if (rst)
     q<=1'b0;
endmodule
//---- Top entity
module vca7316 #(
 parameter v6b316b = 0
) (
 input [7:0] v40cb98,
 output v18e78c
);
 localparam p1 = v6b316b;
 wire w0;
 wire [0:7] w2;
 assign v18e78c = w0;
 assign w2 = v40cb98;
 vca7316_vd75681 #(
  .K(p1)
 ) vd75681 (
  .eq(w0),
  .a(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Comparador  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comparador de un operando de 8 bits. Se compara si el operando es igual al parámetro
/*-------------------------------------------------*/

module vca7316_vd75681 #(
 parameter K = 0
) (
 input [7:0] a,
 output eq
);
 assign eq = (a == K);
endmodule
//---- Top entity
module v8e2728 (
 input v0884a0,
 input v10eedb,
 output v2dffca
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v10eedb;
 assign v2dffca = w1;
 assign w2 = v0884a0;
 v8e2728_v115ffb v115ffb (
  .i(w0),
  .o(w1),
  .clk(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Subida  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Detector de flanco de subida. Emite un tic cuando detecta un flanco ascendente
/*-------------------------------------------------*/

module v8e2728_v115ffb (
 input clk,
 input i,
 output o
);
 reg q = 0;
 
 always @(posedge clk)
   q <= i;
   
 assign o = (~q & i);  
endmodule
//---- Top entity
module v041aa2 #(
 parameter vd07545 = "0",
 parameter v1b494f = "1",
 parameter v4108e1 = 0
) (
 input v6979aa,
 input v55f634,
 input vfa2aa0,
 input [7:0] v510842,
 input vba398f,
 output v431286,
 output v804bc3,
 output v4a5941,
 output v832531,
 output [7:0] vaabd0c,
 output v4642b6
);
 localparam p3 = vd07545;
 localparam p5 = v1b494f;
 localparam p10 = v4108e1;
 wire w0;
 wire w1;
 wire w2;
 wire w4;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire w25;
 wire w26;
 wire w27;
 wire [0:7] w28;
 wire [0:7] w29;
 wire [0:7] w30;
 wire [0:7] w31;
 assign v804bc3 = w4;
 assign v832531 = w12;
 assign v431286 = w14;
 assign w16 = v6979aa;
 assign w17 = v6979aa;
 assign w18 = v6979aa;
 assign w19 = v6979aa;
 assign w20 = v55f634;
 assign w21 = v55f634;
 assign v4a5941 = w22;
 assign v4642b6 = w24;
 assign w25 = vba398f;
 assign w28 = v510842;
 assign w29 = v510842;
 assign w30 = v510842;
 assign w31 = v510842;
 assign vaabd0c = w31;
 assign w14 = w13;
 assign w15 = w13;
 assign w15 = w14;
 assign w17 = w16;
 assign w18 = w16;
 assign w18 = w17;
 assign w19 = w16;
 assign w19 = w17;
 assign w19 = w18;
 assign w21 = w20;
 assign w23 = w22;
 assign w27 = w26;
 assign w29 = w28;
 assign w30 = w28;
 assign w30 = w29;
 assign w31 = w28;
 assign w31 = w29;
 assign w31 = w30;
 ve108d0 v99cfcc (
  .v5399d1(w0),
  .vaf813b(w15),
  .v8f3bff(w24),
  .v0e9572(w25)
 );
 vb959c2 ve67e34 (
  .vb4c770(w13),
  .v581b48(w17),
  .v3c6908(w20),
  .ve68648(w26)
 );
 ve108d0 v926805 (
  .v0e9572(w0),
  .v5399d1(w2),
  .vaf813b(w23)
 );
 vb959c2 v0f2ff8 (
  .ve68648(w1),
  .v581b48(w19),
  .v3c6908(w21),
  .vb4c770(w22)
 );
 ve108d0 v897263 (
  .v5399d1(w1),
  .v0e9572(w2),
  .vaf813b(w8),
  .v8f3bff(w26)
 );
 vca7316 #(
  .v6b316b(p3)
 ) v90e106 (
  .v18e78c(w6),
  .v40cb98(w28)
 );
 v8e2728 v664843 (
  .v2dffca(w4),
  .v10eedb(w13),
  .v0884a0(w16)
 );
 vca7316 #(
  .v6b316b(p5)
 ) vfa5947 (
  .v18e78c(w7),
  .v40cb98(w30)
 );
 v45f630 v1fa68a (
  .vbbc50c(w9),
  .vf54559(w11),
  .ve8318d(w12),
  .va4102a(w18),
  .v9afc1f(w27)
 );
 v21cfcc vae9f57 (
  .v9fb85f(w9)
 );
 vec5121 #(
  .vaf1d6e(p10)
 ) v8b2d86 (
  .v7ff276(w11),
  .vdf5b7a(w29)
 );
 v816138 v0b9dce (
  .v0e28cb(w6),
  .v3ca442(w7),
  .vcbab45(w8)
 );
endmodule

/*-------------------------------------------------*/
/*-- syntax-bit  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- bit syntax block
/*-------------------------------------------------*/
//---- Top entity
module v45f630 #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vbbc50c,
 input vf54559,
 input v9afc1f,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 wire w4;
 wire w5;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 assign w4 = v9afc1f;
 assign w5 = vbbc50c;
 v45f630_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3),
  .load(w4),
  .rst(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- Biestable-D  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Biestable de datos (Tipo D). Cuando se recibe un tic por load se captura el dato
/*-------------------------------------------------*/

module v45f630_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input rst,
 input d,
 input load,
 output q
);
 reg q = INI;
 always @(posedge clk)
   if (rst)
     q <= INI;
   else if (load)
     q <= d;
endmodule
//---- Top entity
module v21cfcc (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v21cfcc_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 0  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 0
/*-------------------------------------------------*/

module v21cfcc_vb2eccd (
 output q
);
 //-- Bit constante a 0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module vec5121 #(
 parameter vaf1d6e = 0
) (
 input [7:0] vdf5b7a,
 output v7ff276
);
 localparam p0 = vaf1d6e;
 wire w1;
 wire [0:7] w2;
 assign v7ff276 = w1;
 assign w2 = vdf5b7a;
 vec5121_vd80544 #(
  .BIT(p0)
 ) vd80544 (
  .o(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Extract-1-bit  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Extractor de 1 bit de un bus de 8 bits
/*-------------------------------------------------*/

module vec5121_vd80544 #(
 parameter BIT = 0
) (
 input [7:0] i,
 output o
);
 assign o = i[BIT];
endmodule
//---- Top entity
module v816138 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v816138_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- OR  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta OR
/*-------------------------------------------------*/

module v816138_vf4938a (
 input a,
 input b,
 output c
);
 //-- Puerta OR
 
 //-- module and (input wire a, input wire b,
 //--             output wire c);
 
 assign c = a | b;
 
 //-- endmodule
endmodule
//---- Top entity
module v1c7dae #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v1c7dae_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Biestable-D  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Biestable de datos (Tipo D). Cuando se recibe un tic por load se captura el dato
/*-------------------------------------------------*/

module v1c7dae_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 reg q = INI;
 always @(posedge clk)
   q <= d;
endmodule
//---- Top entity
module v46217c (
 input [10:0] v68c0ef,
 output v462094,
 output v52bd29,
 output [7:0] v5b0467,
 output v21f955
);
 wire [0:10] w0;
 wire w1;
 wire w2;
 wire [0:7] w3;
 wire w4;
 assign w0 = v68c0ef;
 assign v462094 = w1;
 assign v52bd29 = w2;
 assign v5b0467 = w3;
 assign v21f955 = w4;
 v46217c_v085704 v085704 (
  .i(w0),
  .rst(w1),
  .eol(w2),
  .data(w3),
  .tic(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- VIB-split  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Virtual input bus Splitter
/*-------------------------------------------------*/

module v46217c_v085704 (
 input [10:0] i,
 output rst,
 output eol,
 output [7:0] data,
 output tic
);
 assign rst = i[10];
 assign eol = i[9];
 assign data = i[8:1];
 assign tic = i[0];
endmodule
//---- Top entity
module vd6c41f (
 input v0a3376,
 input v06e51b,
 input v88b7c2,
 input v2308bf,
 input vc76908,
 output vfdada2,
 output ve81fcc
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 assign w2 = v0a3376;
 assign vfdada2 = w3;
 assign w5 = v06e51b;
 assign w6 = v2308bf;
 assign ve81fcc = w7;
 assign w8 = vc76908;
 assign w1 = w0;
 assign w4 = w3;
 vb2090f vc7501e (
  .v3ca442(w1),
  .v0e28cb(w6),
  .vcbab45(w7)
 );
 vb959c2 vf29f4e (
  .ve68648(w0),
  .v581b48(w2),
  .vb4c770(w3),
  .v3c6908(w5)
 );
 ve108d0 v4b37b5 (
  .v5399d1(w0),
  .vaf813b(w4),
  .v0e9572(w8)
 );
endmodule

/*-------------------------------------------------*/
/*-- Syntax-EOL  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Syntax End Of Line. Last block when detecting a command
/*-------------------------------------------------*/
//---- Top entity
module vb2090f (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vb2090f_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta AND
/*-------------------------------------------------*/

module vb2090f_vf4938a (
 input a,
 input b,
 output c
);
 //-- Puerta AND
 
 //-- module and (input wire a, input wire b,
 //--             output wire c);
 
 assign c = a & b;
 
 //-- endmodule
endmodule
//---- Top entity
module vd4bd04 (
 input vee8a83,
 input v03aaf0,
 output [1:0] v67a3fc
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign v67a3fc = w2;
 vd4bd04_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 2 cables en un bus de 2-bits
/*-------------------------------------------------*/

module vd4bd04_v9a2a06 (
 input i1,
 input i0,
 output [1:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vc0b252 #(
 parameter v7ab8da = "a",
 parameter vfa9d9d = "b"
) (
 input v479d8c,
 input vfd7d50,
 input v5184d8,
 input v0fcc86,
 input vec5765,
 output [1:0] vfcdec9,
 output [10:0] va8b46c,
 output [1:0] ve64ec1,
 output [1:0] v4d6cf3,
 output [1:0] v07aeec
);
 localparam p0 = v7ab8da;
 localparam p2 = vfa9d9d;
 wire [0:10] w1;
 wire w3;
 wire w4;
 wire w5;
 wire [0:1] w6;
 wire w7;
 wire w8;
 wire [0:10] w9;
 wire [0:1] w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire [0:1] w15;
 wire w16;
 wire w17;
 wire [0:1] w18;
 assign w3 = vfd7d50;
 assign w4 = v479d8c;
 assign w5 = v479d8c;
 assign vfcdec9 = w6;
 assign va8b46c = w9;
 assign ve64ec1 = w10;
 assign v4d6cf3 = w15;
 assign v07aeec = w18;
 assign w5 = w4;
 v027b08 #(
  .vbdcb71(p0)
 ) vd940da (
  .va8b46c(w1),
  .vfd7d50(w3),
  .v479d8c(w4),
  .v41ef49(w7),
  .vb462f7(w12),
  .v7913cc(w14),
  .v8cb521(w16)
 );
 vb59e75 #(
  .v723ac3(p2)
 ) vd697c4 (
  .v051016(w1),
  .v5439ee(w5),
  .v0af42d(w8),
  .vca68f1(w9),
  .vd68cd9(w11),
  .v31581a(w13),
  .v12cda8(w17)
 );
 vd4bd04 vf18060 (
  .v67a3fc(w6),
  .vee8a83(w7),
  .v03aaf0(w8)
 );
 vd4bd04 v8fa168 (
  .v67a3fc(w10),
  .v03aaf0(w11),
  .vee8a83(w12)
 );
 vd4bd04 v0e0ad0 (
  .v03aaf0(w13),
  .vee8a83(w14),
  .v67a3fc(w15)
 );
 vd4bd04 vf9b396 (
  .vee8a83(w16),
  .v03aaf0(w17),
  .v67a3fc(w18)
 );
endmodule

/*-------------------------------------------------*/
/*-- Switchx2-RX  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Two Virtual Switches. Receiving unit
/*-------------------------------------------------*/
//---- Top entity
module v027b08 #(
 parameter vbdcb71 = "a"
) (
 input v479d8c,
 input vfd7d50,
 input v5184d8,
 input v0fcc86,
 input vec5765,
 output v41ef49,
 output [10:0] va8b46c,
 output vb462f7,
 output v7913cc,
 output v8cb521
);
 localparam p1 = vbdcb71;
 wire [0:10] w0;
 wire w2;
 wire [0:10] w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 assign v41ef49 = w2;
 assign va8b46c = w3;
 assign vb462f7 = w4;
 assign v7913cc = w5;
 assign v8cb521 = w6;
 assign w7 = vfd7d50;
 assign w8 = v479d8c;
 assign w9 = v479d8c;
 assign w9 = w8;
 v97cf0b v2efc2f (
  .v880ec9(w0),
  .vd975d5(w7),
  .v262cad(w9)
 );
 v5c14e0 #(
  .v723ac3(p1)
 ) v19ca01 (
  .v051016(w0),
  .v0af42d(w2),
  .vca68f1(w3),
  .vd68cd9(w4),
  .v31581a(w5),
  .v12cda8(w6),
  .v5439ee(w8)
 );
endmodule

/*-------------------------------------------------*/
/*-- Switchx1-RX  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Virtual Switch. Receiving unit
/*-------------------------------------------------*/
//---- Top entity
module v97cf0b #(
 parameter v318041 = "\n",
 parameter v52dfe8 = 13
) (
 input v262cad,
 input vd975d5,
 output vde015e,
 output [10:0] v880ec9
);
 localparam p0 = v318041;
 localparam p3 = v52dfe8;
 wire w1;
 wire w2;
 wire w4;
 wire w5;
 wire [0:10] w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire [0:7] w12;
 wire [0:7] w13;
 wire [0:7] w14;
 wire w15;
 wire w16;
 assign v880ec9 = w6;
 assign w7 = vd975d5;
 assign w9 = v262cad;
 assign w10 = v262cad;
 assign w10 = w9;
 assign w11 = w5;
 assign w13 = w12;
 assign w14 = w12;
 assign w14 = w13;
 assign w16 = w15;
 v1c7dae vcaaa6a (
  .vf54559(w5),
  .ve8318d(w8),
  .va4102a(w10)
 );
 vca7316 #(
  .v6b316b(p0)
 ) v18da97 (
  .v18e78c(w4),
  .v40cb98(w13)
 );
 v816138 v5db670 (
  .vcbab45(w1),
  .v3ca442(w2),
  .v0e28cb(w4)
 );
 vb2090f v2eb411 (
  .v0e28cb(w1),
  .vcbab45(w5),
  .v3ca442(w16)
 );
 vca7316 #(
  .v6b316b(p3)
 ) v459738 (
  .v18e78c(w2),
  .v40cb98(w14)
 );
 v0bc7bc v59b6c5 (
  .v6b96e9(w6),
  .v7862da(w8),
  .v15ebee(w11),
  .v20eafc(w12),
  .v527976(w15)
 );
 vb9ce14 v9f5fb6 (
  .v6a1cbe(w7),
  .v7114a9(w9),
  .v2d03ef(w12),
  .v6a2ebd(w15)
 );
endmodule

/*-------------------------------------------------*/
/*-- VIB  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Virtual Input Bus: Virtual inputs components receiver
/*-------------------------------------------------*/
//---- Top entity
module v0bc7bc (
 input v7862da,
 input v15ebee,
 input [7:0] v20eafc,
 input v527976,
 output [10:0] v6b96e9
);
 wire w0;
 wire [0:10] w1;
 wire [0:7] w2;
 wire w3;
 wire w4;
 assign w0 = v527976;
 assign v6b96e9 = w1;
 assign w2 = v20eafc;
 assign w3 = v15ebee;
 assign w4 = v7862da;
 v0bc7bc_v8ce978 v8ce978 (
  .tic(w0),
  .o(w1),
  .data(w2),
  .eol(w3),
  .rst(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- VIB-join  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Virtual input bus Joiner
/*-------------------------------------------------*/

module v0bc7bc_v8ce978 (
 input rst,
 input eol,
 input [7:0] data,
 input tic,
 output [10:0] o
);
 assign o = {rst, eol, data, tic};
endmodule
//---- Top entity
module vb9ce14 #(
 parameter v47d474 = 115200
) (
 input v7114a9,
 input v6a1cbe,
 output [7:0] v2d03ef,
 output ve77bd8,
 output v6a2ebd
);
 localparam p4 = v47d474;
 wire w0;
 wire w1;
 wire [0:7] w2;
 wire w3;
 wire w5;
 assign w0 = v7114a9;
 assign w1 = v6a1cbe;
 assign v2d03ef = w2;
 assign v6a2ebd = w3;
 assign ve77bd8 = w5;
 vb9ce14_vf55761 #(
  .BAUD(p4)
 ) vf55761 (
  .clk(w0),
  .RX(w1),
  .data(w2),
  .rcv(w3),
  .busy(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- Serial-rx  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Receptor serie asíncrono. Velocidad por defecto: 115200 baudios
/*-------------------------------------------------*/

module vb9ce14_vf55761 #(
 parameter BAUD = 0
) (
 input clk,
 input RX,
 output [7:0] data,
 output busy,
 output rcv
);
 //-- Constantes para obtener las velocidades estándares
 `define B115200 104 
 `define B57600  208
 `define B38400  313
 `define B19200  625
 `define B9600   1250
 `define B4800   2500
 `define B2400   5000
 `define B1200   10000
 `define B600    20000
 `define B300    40000
 
 //-- Constante para calcular los baudios
 localparam BAUDRATE = (BAUD==115200) ? `B115200 : //-- OK
                       (BAUD==57600)  ? `B57600  : //-- OK
                       (BAUD==38400)  ? `B38400  : //-- Ok
                       (BAUD==19200)  ? `B19200  : //-- OK
                       (BAUD==9600)   ? `B9600   : //-- OK
                       (BAUD==4800)   ? `B4800   : //-- OK 
                       (BAUD==2400)   ? `B2400   : //-- OK
                       (BAUD==1200)   ? `B1200   : //-- OK
                       (BAUD==600)    ? `B600    : //-- OK
                       (BAUD==300)    ? `B300    : //-- OK
                       `B115200 ;  //-- Por defecto 115200 baudios
 
 
 
 
 //-- Calcular el numero de bits para almacenar el divisor
 localparam N = $clog2(BAUDRATE);
 
 // Sincronizacion. Evitar 
 // problema de la metaestabilidad
 
 reg d1;
 reg din;
 
 always @(posedge clk)
  d1 <= RX;
  
 //-- Din contiene el dato serie de entrada listo para usarse   
 always @(posedge clk)
   din <= d1;
   
 //------ Detectar el bit de start: flanco de bajada en din
 
 //-- Registro temporal
 reg q_t0 = 0;
 
 always @(posedge clk)
   q_t0 <= din;
   
 //-- El cable din_fe es un "tic" que aparece cuando llega el flanco de 
 //-- bajada
 wire din_fe = (q_t0 & ~din);
 
 //-------- ESTADO DEL RECEPTOR
 
 //-- 0: Apagado. Esperando
 //-- 1: Encendido. Activo. Recibiendo dato
 reg state = 0;
 
 always @(posedge clk)
   //-- Se pasa al estado activo al detectar el flanco de bajada
   //-- del bit de start
   if (din_fe)
     state <= 1'b1;
     
   //-- Se pasa al estado inactivo al detectar la señal rst_state    
   else if (rst_state)
     state<=1'b0;
 
 //------------------ GENERADOR DE BAUDIOS -----------------------------
 //-- Se activa cuando el receptor está encendido
 
 
 //-- Calcular la mitad del divisor BAUDRATE/2
 localparam BAUD2 = (BAUDRATE >> 1);
 
 //-- Contador del sistema, para esperar un tiempo de  
 //-- medio bit (BAUD2)
 
 //-- NOTA: podria tener N-2 bits en principio
 reg [N-1: 0] div2counter = 0;
 
 //-- Se genera primero un retraso de BAUD/2
 //-- El proceso comienza cuando el estado pasa a 1
 
 always @(posedge clk)
 
   //-- Contar
   if (state) begin
     //-- Solo cuenta hasta BAUD2, luego  
     //-- se queda en ese valor hasta que
     //-- ena se desactiva
     if (div2counter < BAUD2) 
       div2counter <= div2counter + 1;
   end else
     div2counter <= 0;
 
 //-- Habilitar el generador de baudios principal
 //-- cuando termine este primer contador
 wire ena2 = (div2counter == BAUD2);
 
 
 //------ GENERADOR DE BAUDIOS PRINCIPAL
 
 //-- Contador para implementar el divisor
 //-- Es un contador modulo BAUDRATE
 reg [N-1:0] divcounter = 0;
 
 //-- Cable de reset para el contador
 wire reset;
 
 //-- Contador con reset
 always @(posedge clk)
   if (reset)
     divcounter <= 0;
   else
     divcounter <= divcounter + 1;
 
 //-- Esta señal contiene el tic
 wire ov = (divcounter == BAUDRATE-1);
 
 //-- Comparador que resetea el contador cuando se alcanza el tope
 assign reset = ov | (ena2 == 0);
 
 //-- El cable con el tic para capturar cada bit lo llamamos
 //-- bit_tic, y es la señal de overflow del contador
 wire bit_tic = ov;
 
 //-------- REGISTRO DE DESPLAZAMIENTO -----------
 //-- Es el componente que pasa los bits recibidos a paralelo
 //-- La señal de desplazamiento usada es bit_tic, pero sólo cuando  
 //-- estamos en estado de encendido (state==1)
 //-- Es un registro de 9 bits: 8 bits de datos + bit de stop
 //-- El bit de start no se almacena, es el que ha servido para
 //-- arrancar el receptor
 
 reg [8:0] sr = 0;
 
 always @(posedge clk)
   //-- Se captura el bit cuando llega y el receptor
   //-- esta activado
   if (bit_tic & state)
     sr <= {din, sr[8:1]};
     
 //-- El dato recibido se encuentran en los 8 bits menos significativos
 //-- una vez recibidos los 9 bits
 
 //-------- CONTADOR de bits recibidos
 
 //-- Internamente usamos un bit mas
 //-- (N+1) bits
 reg [4:0] cont = 0;
 
 always @(posedge clk)
 
   //-- El contador se pone a 0 si hay un overflow o 
   //-- el receptor está apagado 
   if ((state==0)| ov2)
     cont <= 0;
   else
     //-- Receptor activado: Si llega un bit se incrementa
     if (bit_tic)
       cont <= cont + 1;
       
 //-- Comprobar overflow
 wire ov2 = (cont == 9);
     
 //-- Esta señal de overflow indica el final de la recepción
 wire fin = ov2;
 
 //-- Se conecta al reset el biestable de estado
 wire rst_state = fin;
 
 //----- REGISTRO DE DATOS -------------------
 //-- Registro de 8 bits que almacena el dato final
 
 //-- Bus de salida con el dato recibido
 reg data = 0;
 
 always @(posedge clk)
 
   //-- Si se ha recibido el ultimo bit, capturamos el dato
   //-- que se encuentra en los 8 bits de menor peso del
   //-- registro de desplazamiento
   if (fin)
     data <= sr[7:0];
 
 //-- Comunicar que se ha recibido un dato
 //-- Tic de dato recibido
 reg rcv = 0;
 always @(posedge clk)
   rcv <= fin;
 
 //-- La señal de busy es directamente el estado del receptor
 assign busy = state;
 
 
endmodule
//---- Top entity
module v5c14e0 #(
 parameter v723ac3 = "a"
) (
 input v5439ee,
 input [10:0] v051016,
 input v61f96e,
 input vfbdd9d,
 input v581a78,
 output v0af42d,
 output [10:0] vca68f1,
 output vd68cd9,
 output v31581a,
 output v12cda8
);
 localparam p0 = v723ac3;
 wire [0:7] w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:10] w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire [0:10] w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire [0:7] w25;
 wire w26;
 assign w5 = v051016;
 assign v31581a = w6;
 assign v12cda8 = w7;
 assign v0af42d = w8;
 assign w10 = v5439ee;
 assign w11 = v5439ee;
 assign w12 = v5439ee;
 assign w13 = v5439ee;
 assign w14 = v5439ee;
 assign vca68f1 = w15;
 assign w15 = v051016;
 assign vd68cd9 = w16;
 assign w9 = w8;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 assign w14 = w10;
 assign w14 = w11;
 assign w14 = w12;
 assign w14 = w13;
 assign w15 = w5;
 assign w17 = w16;
 assign w20 = w19;
 assign w22 = w21;
 assign w23 = w21;
 assign w23 = w22;
 vd48523 #(
  .vd07545(p0)
 ) v157473 (
  .vaabd0c(w1),
  .v4642b6(w2),
  .v6979aa(w14),
  .v55f634(w23),
  .v510842(w25),
  .vba398f(w26)
 );
 v041aa2 v7242b9 (
  .v510842(w1),
  .vba398f(w2),
  .v4642b6(w4),
  .v6979aa(w12),
  .v832531(w18),
  .v55f634(w22)
 );
 v45f630 v9ba3f8 (
  .vbbc50c(w3),
  .va4102a(w10),
  .ve8318d(w16),
  .vf54559(w18),
  .v9afc1f(w19)
 );
 v21cfcc ve2f9b5 (
  .v9fb85f(w3)
 );
 v1c7dae vec075a (
  .ve8318d(w8),
  .va4102a(w11),
  .vf54559(w20)
 );
 v46217c vb06e2a (
  .v68c0ef(w5),
  .v462094(w21),
  .v52bd29(w24),
  .v5b0467(w25),
  .v21f955(w26)
 );
 vd6c41f v224d00 (
  .vc76908(w4),
  .v0a3376(w13),
  .ve81fcc(w19),
  .v06e51b(w21),
  .v2308bf(w24)
 );
 ve108d0 vbff35c (
  .v8f3bff(w6),
  .v5399d1(w7),
  .v0e9572(w9),
  .vaf813b(w17)
 );
endmodule

/*-------------------------------------------------*/
/*-- Virtual-switch  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Virtual switch (1-bit)
/*-------------------------------------------------*/
//---- Top entity
module v91b7ac (
 input [1:0] v30c67a,
 input [1:0] vbf5c47,
 output [3:0] v8b7d6a
);
 wire [0:1] w0;
 wire [0:1] w1;
 wire [0:3] w2;
 assign w0 = vbf5c47;
 assign w1 = v30c67a;
 assign v8b7d6a = w2;
 v91b7ac_v9a2a06 v9a2a06 (
  .i0(w0),
  .i1(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de buses de 2-bits a bus de 4-bits
/*-------------------------------------------------*/

module v91b7ac_v9a2a06 (
 input [1:0] i1,
 input [1:0] i0,
 output [3:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v24ca99 #(
 parameter v7ab8da = "a",
 parameter vf10655 = "b",
 parameter v8b4198 = "c",
 parameter v89f607 = "d"
) (
 input v479d8c,
 input [10:0] vfd0650,
 input v5184d8,
 input v0fcc86,
 input vec5765,
 output [3:0] v4b620e,
 output [10:0] va8b46c,
 output [3:0] vc9f895,
 output [3:0] vc92856,
 output [3:0] v1d7c1a
);
 localparam p0 = v7ab8da;
 localparam p1 = vf10655;
 localparam p3 = v8b4198;
 localparam p4 = v89f607;
 wire [0:10] w2;
 wire [0:3] w5;
 wire [0:10] w6;
 wire [0:3] w7;
 wire [0:3] w8;
 wire [0:3] w9;
 wire w10;
 assign w2 = vfd0650;
 assign v4b620e = w5;
 assign va8b46c = w6;
 assign vc9f895 = w7;
 assign vc92856 = w8;
 assign v1d7c1a = w9;
 assign w10 = v479d8c;
 v703c0a #(
  .v7ab8da(p0),
  .vf10655(p1),
  .v8b4198(p3),
  .v89f607(p4)
 ) v27051a (
  .vfd0650(w2),
  .v4b620e(w5),
  .va8b46c(w6),
  .vc9f895(w7),
  .vc92856(w8),
  .v1d7c1a(w9),
  .v479d8c(w10)
 );
endmodule

/*-------------------------------------------------*/
/*-- Pushbuttonx4-Bus CLONE  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Four Virtual Pushbuttons. Bus unit
/*-------------------------------------------------*/
//---- Top entity
module v703c0a #(
 parameter v7ab8da = "a",
 parameter vf10655 = "b",
 parameter v8b4198 = "c",
 parameter v89f607 = "d"
) (
 input v479d8c,
 input [10:0] vfd0650,
 input v5184d8,
 input v0fcc86,
 input vec5765,
 output [3:0] v4b620e,
 output [10:0] va8b46c,
 output [3:0] vc9f895,
 output [3:0] vc92856,
 output [3:0] v1d7c1a
);
 localparam p0 = v7ab8da;
 localparam p2 = v8b4198;
 localparam p3 = vf10655;
 localparam p4 = v89f607;
 wire [0:10] w1;
 wire [0:10] w5;
 wire w6;
 wire w7;
 wire [0:3] w8;
 wire [0:10] w9;
 wire [0:1] w10;
 wire [0:1] w11;
 wire [0:3] w12;
 wire [0:1] w13;
 wire [0:1] w14;
 wire [0:1] w15;
 wire [0:1] w16;
 wire [0:3] w17;
 wire [0:1] w18;
 wire [0:1] w19;
 wire [0:3] w20;
 assign w5 = vfd0650;
 assign w6 = v479d8c;
 assign w7 = v479d8c;
 assign v4b620e = w8;
 assign va8b46c = w9;
 assign vc9f895 = w12;
 assign vc92856 = w17;
 assign v1d7c1a = w20;
 assign w7 = w6;
 v7d59c6 #(
  .v7ab8da(p2),
  .vfa9d9d(p4)
 ) v554919 (
  .v0531e9(w1),
  .v479d8c(w7),
  .va8b46c(w9),
  .vfcdec9(w11),
  .ve64ec1(w13),
  .v4d6cf3(w15),
  .v07aeec(w18)
 );
 v91b7ac v8c0fd0 (
  .v8b7d6a(w8),
  .v30c67a(w10),
  .vbf5c47(w11)
 );
 v91b7ac v11b579 (
  .v8b7d6a(w12),
  .vbf5c47(w13),
  .v30c67a(w14)
 );
 v91b7ac v5ded3e (
  .vbf5c47(w15),
  .v30c67a(w16),
  .v8b7d6a(w17)
 );
 v91b7ac v36cfb3 (
  .vbf5c47(w18),
  .v30c67a(w19),
  .v8b7d6a(w20)
 );
 v7d59c6 #(
  .v7ab8da(p0),
  .vfa9d9d(p3)
 ) v2037c7 (
  .va8b46c(w1),
  .v0531e9(w5),
  .v479d8c(w6),
  .vfcdec9(w10),
  .ve64ec1(w14),
  .v4d6cf3(w16),
  .v07aeec(w19)
 );
endmodule

/*-------------------------------------------------*/
/*-- Switchx4-Bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Four Virtual Switches. Bus unit
/*-------------------------------------------------*/
//---- Top entity
module v917222 (
 input [3:0] v285646,
 input [3:0] v766044,
 output [7:0] va191ad
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 assign w0 = v766044;
 assign w1 = v285646;
 assign va191ad = w2;
 v917222_v9a2a06 v9a2a06 (
  .i0(w0),
  .i1(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 2 buses de 4-bits a bus de 8-bits
/*-------------------------------------------------*/

module v917222_v9a2a06 (
 input [3:0] i1,
 input [3:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v8eed06 #(
 parameter v11a07f = "a",
 parameter vd1c7d9 = "b",
 parameter v077ede = "c",
 parameter va86b54 = "d",
 parameter v128381 = "e",
 parameter vdc93ce = "f",
 parameter va57579 = "g",
 parameter ve245ce = "h",
 parameter v3a4133 = "i",
 parameter va79108 = "j",
 parameter v16f1c7 = "k",
 parameter v7afcff = "l",
 parameter vbbb21b = "m",
 parameter v6ac546 = "n",
 parameter vadaccd = "o",
 parameter v455918 = "p"
) (
 input v294f2a,
 input [17:0] vb7eca5,
 input [15:0] v4dd039,
 output va5c2ac,
 output [17:0] v954064,
 output vf4f51f
);
 localparam p0 = v3a4133;
 localparam p1 = va79108;
 localparam p2 = v16f1c7;
 localparam p3 = v7afcff;
 localparam p4 = vbbb21b;
 localparam p5 = v6ac546;
 localparam p6 = vadaccd;
 localparam p7 = v455918;
 localparam p12 = v11a07f;
 localparam p13 = vd1c7d9;
 localparam p14 = v077ede;
 localparam p15 = va86b54;
 localparam p16 = v128381;
 localparam p17 = vdc93ce;
 localparam p18 = va57579;
 localparam p19 = ve245ce;
 wire [0:7] w8;
 wire [0:7] w9;
 wire w10;
 wire [0:17] w11;
 wire [0:17] w20;
 wire w21;
 wire w22;
 wire [0:17] w23;
 wire [0:15] w24;
 assign va5c2ac = w10;
 assign v954064 = w11;
 assign w21 = v294f2a;
 assign w22 = v294f2a;
 assign w23 = vb7eca5;
 assign w24 = v4dd039;
 assign w22 = w21;
 vd6a41b #(
  .v11a07f(p0),
  .vd1c7d9(p1),
  .v077ede(p2),
  .va86b54(p3),
  .v128381(p4),
  .vdc93ce(p5),
  .va57579(p6),
  .ve245ce(p7)
 ) v4c689d (
  .v20f04d(w8),
  .va5c2ac(w10),
  .v954064(w11),
  .vb7eca5(w20),
  .v294f2a(w21)
 );
 v26f57a v9d7794 (
  .v0e9841(w8),
  .vf774e8(w9),
  .vad1323(w24)
 );
 v1a2506 #(
  .v11a07f(p12),
  .vd1c7d9(p13),
  .v077ede(p14),
  .va86b54(p15),
  .v128381(p16),
  .vdc93ce(p17),
  .va57579(p18),
  .ve245ce(p19)
 ) vaf23ea (
  .v20f04d(w9),
  .v954064(w20),
  .v294f2a(w22),
  .vb7eca5(w23)
 );
endmodule

/*-------------------------------------------------*/
/*-- LEDx16-tx  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 16 virtual LEDs. Transmision block
/*-------------------------------------------------*/
//---- Top entity
module vd6a41b #(
 parameter v11a07f = "a",
 parameter vd1c7d9 = "b",
 parameter v077ede = "c",
 parameter va86b54 = "d",
 parameter v128381 = "e",
 parameter vdc93ce = "f",
 parameter va57579 = "g",
 parameter ve245ce = "h"
) (
 input v294f2a,
 input [17:0] vb7eca5,
 input [7:0] v20f04d,
 output va5c2ac,
 output [17:0] v954064,
 output vf4f51f
);
 localparam p1 = va57579;
 localparam p2 = vdc93ce;
 localparam p3 = v128381;
 localparam p6 = va86b54;
 localparam p7 = v077ede;
 localparam p8 = vd1c7d9;
 localparam p9 = v11a07f;
 localparam p12 = ve245ce;
 wire [0:3] w0;
 wire [0:17] w4;
 wire [0:3] w5;
 wire w10;
 wire [0:17] w11;
 wire w13;
 wire w14;
 wire [0:17] w15;
 wire [0:7] w16;
 assign va5c2ac = w10;
 assign v954064 = w11;
 assign w13 = v294f2a;
 assign w14 = v294f2a;
 assign w15 = vb7eca5;
 assign w16 = v20f04d;
 assign w14 = w13;
 v73403c ved7804 (
  .v85accc(w0),
  .vf9119c(w5),
  .v595263(w16)
 );
 ve63216 #(
  .v96c5b2(p1),
  .v2583b8(p2),
  .v679028(p3),
  .v251a02(p12)
 ) ve634e3 (
  .vec6453(w0),
  .vb7eca5(w4),
  .va5c2ac(w10),
  .v954064(w11),
  .v294f2a(w13)
 );
 v4c66ed #(
  .v251a02(p6),
  .v96c5b2(p7),
  .v2583b8(p8),
  .v679028(p9)
 ) v8d7ccf (
  .v954064(w4),
  .vec6453(w5),
  .v294f2a(w14),
  .vb7eca5(w15)
 );
endmodule

/*-------------------------------------------------*/
/*-- LEDx8-tx  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Eight virtual LEDs. Transmision block
/*-------------------------------------------------*/
//---- Top entity
module v73403c (
 input [7:0] v595263,
 output [3:0] vf9119c,
 output [3:0] v85accc
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 assign vf9119c = w0;
 assign v85accc = w1;
 assign w2 = v595263;
 v73403c_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 8-bits en buses de 4 bits
/*-------------------------------------------------*/

module v73403c_v9a2a06 (
 input [7:0] i,
 output [3:0] o1,
 output [3:0] o0
);
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module ve63216 #(
 parameter v679028 = "a",
 parameter v2583b8 = "b",
 parameter v96c5b2 = "c",
 parameter v251a02 = "d"
) (
 input v294f2a,
 input [17:0] vb7eca5,
 input [3:0] vec6453,
 output va5c2ac,
 output [17:0] v954064,
 output vf4f51f
);
 localparam p0 = v679028;
 localparam p3 = v2583b8;
 localparam p10 = v96c5b2;
 localparam p11 = v251a02;
 wire w1;
 wire [0:17] w2;
 wire w4;
 wire [0:17] w5;
 wire w6;
 wire w7;
 wire [0:17] w8;
 wire w9;
 wire [0:17] w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire [0:17] w17;
 wire [0:3] w18;
 assign va5c2ac = w7;
 assign v954064 = w12;
 assign w13 = v294f2a;
 assign w14 = v294f2a;
 assign w15 = v294f2a;
 assign w16 = v294f2a;
 assign w17 = vb7eca5;
 assign w18 = vec6453;
 assign w14 = w13;
 assign w15 = w13;
 assign w15 = w14;
 assign w16 = w13;
 assign w16 = w14;
 assign w16 = w15;
 vbcf605 #(
  .v688ddd(p0)
 ) v6adc86 (
  .vea82a4(w1),
  .vb3bc3f(w2),
  .v31df97(w13),
  .v5e66c1(w17)
 );
 v45c913 v7d31b0 (
  .v5b73e8(w1),
  .vc90115(w4),
  .v2812a7(w6),
  .v593f43(w9),
  .v930b03(w18)
 );
 vbcf605 #(
  .v688ddd(p3)
 ) v8fd1cc (
  .v5e66c1(w2),
  .vea82a4(w4),
  .vb3bc3f(w5),
  .v31df97(w14)
 );
 vbcf605 #(
  .v688ddd(p10)
 ) v95860b (
  .v5e66c1(w5),
  .vea82a4(w6),
  .vb3bc3f(w8),
  .v31df97(w15)
 );
 v686f58 #(
  .v19c0b3(p11)
 ) vaf6824 (
  .ved8d63(w7),
  .v9339c3(w8),
  .v3b85d9(w9),
  .v921679(w12),
  .v061a1d(w16)
 );
endmodule

/*-------------------------------------------------*/
/*-- LEDx4-tx  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Four virtual LEDs. Transmision block
/*-------------------------------------------------*/
//---- Top entity
module vbcf605 #(
 parameter v688ddd = "a"
) (
 input v31df97,
 input [17:0] v5e66c1,
 input vea82a4,
 output vad6642,
 output [17:0] vb3bc3f,
 output v1eaa61
);
 localparam p1 = v688ddd;
 wire w0;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire [0:7] w9;
 wire [0:7] w10;
 wire w11;
 wire w12;
 wire [0:17] w13;
 wire w14;
 wire w15;
 wire w16;
 wire [0:17] w17;
 wire [0:17] w18;
 wire [0:17] w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire w25;
 wire w26;
 wire w27;
 wire w28;
 wire w29;
 assign w14 = v31df97;
 assign w15 = v31df97;
 assign w16 = v31df97;
 assign w17 = v5e66c1;
 assign w18 = v5e66c1;
 assign vb3bc3f = w19;
 assign w21 = vea82a4;
 assign w22 = vea82a4;
 assign w23 = vea82a4;
 assign w12 = w11;
 assign w15 = w14;
 assign w16 = w14;
 assign w16 = w15;
 assign w18 = w17;
 assign w20 = w2;
 assign w22 = w21;
 assign w23 = w21;
 assign w23 = w22;
 assign w25 = w24;
 assign w26 = w24;
 assign w26 = w25;
 v42ebf7 vc14e30 (
  .va4102a(w14),
  .vf54559(w22),
  .v9afc1f(w26),
  .ve8318d(w28)
 );
 vb70dd9 v0e9c91 (
  .vcbab45(w6),
  .v0e28cb(w23),
  .v3ca442(w28)
 );
 v35f267 v5ebea7 (
  .vcbab45(w0),
  .v0e28cb(w12)
 );
 vb2090f v1c3103 (
  .v3ca442(w0),
  .vcbab45(w4),
  .v0e28cb(w5)
 );
 v5ad97e #(
  .vc5c8ea(p1)
 ) vfc38ff (
  .v26dbdb(w10)
 );
 v8e2728 vef5ded (
  .v10eedb(w2),
  .v0884a0(w16),
  .v2dffca(w24)
 );
 v35f267 ve4e366 (
  .vcbab45(w3),
  .v0e28cb(w27)
 );
 vb2090f v9003ad (
  .vcbab45(w2),
  .v0e28cb(w3),
  .v3ca442(w4)
 );
 vb959c2 v95b55f (
  .vb4c770(w7),
  .v3c6908(w8),
  .v581b48(w15),
  .ve68648(w25)
 );
 v816138 vc1bbbb (
  .vcbab45(w5),
  .v3ca442(w6),
  .v0e28cb(w29)
 );
 v35f267 vf4593c (
  .v0e28cb(w7),
  .vcbab45(w29)
 );
 v21cfcc v7527aa (
  .v9fb85f(w8)
 );
 v6348d5 v27a822 (
  .v869a97(w9),
  .v428b2b(w21)
 );
 vd2823e v947079 (
  .v462094(w11),
  .v66bc08(w18),
  .v21f955(w27)
 );
 vabe1dc vef0a35 (
  .v20eafc(w9),
  .ve811db(w10),
  .v7862da(w11),
  .v6902e8(w13),
  .v527976(w24)
 );
 v57e7b3 v58f17a (
  .v079db2(w13),
  .v46bdab(w17),
  .v24206e(w19),
  .v50d6c6(w20)
 );
endmodule

/*-------------------------------------------------*/
/*-- LEDx1-BUS  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- One Virtual LED with bus expansion
/*-------------------------------------------------*/
//---- Top entity
module v42ebf7 #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 input v9afc1f,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 wire w4;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 assign w4 = v9afc1f;
 v42ebf7_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3),
  .load(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Biestable-D  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Biestable de datos (Tipo D). Cuando se recibe un tic por load se captura el dato
/*-------------------------------------------------*/

module v42ebf7_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 input load,
 output q
);
 reg q = INI;
 always @(posedge clk)
   if (load)
     q <= d;
endmodule
//---- Top entity
module vb70dd9 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vb70dd9_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- XOR  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta XOR
/*-------------------------------------------------*/

module vb70dd9_vf4938a (
 input a,
 input b,
 output c
);
 //-- Puerta XOR
 
 //-- module xor (input wire a, input wire b,
 //--             output wire c);
 
 assign c = a ^ b;
 
 //-- endmodule
endmodule
//---- Top entity
module v35f267 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v35f267_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOT  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta NOT
/*-------------------------------------------------*/

module v35f267_vd54ca1 (
 input a,
 output c
);
 //-- Puerta NOT
 
 //-- module (input wire a, output wire c);
 
 
 assign c = ~a;
 
 
 //-- endmodule
 
endmodule
//---- Top entity
module v5ad97e #(
 parameter vc5c8ea = 0
) (
 output [7:0] v26dbdb
);
 localparam p0 = vc5c8ea;
 wire [0:7] w1;
 assign v26dbdb = w1;
 v5ad97e_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Constante-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor genérico constante, de 8 bits. Su valor se introduce como parámetro. Por defecto vale 0
/*-------------------------------------------------*/

module v5ad97e_v465065 #(
 parameter VALUE = 0
) (
 output [7:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module v6348d5 (
 input [6:0] vcff9d0,
 input v428b2b,
 output [7:0] v869a97
);
 wire [0:6] w0;
 wire w1;
 wire [0:7] w2;
 assign w0 = vcff9d0;
 assign w1 = v428b2b;
 assign v869a97 = w2;
 v6348d5_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de un bus de 7 bits y un cable a bus de 8-bits
/*-------------------------------------------------*/

module v6348d5_v9a2a06 (
 input [6:0] i1,
 input i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vd2823e (
 input [17:0] v66bc08,
 output v462094,
 output [7:0] vbc8593,
 output [7:0] v5b0467,
 output v21f955
);
 wire [0:7] w0;
 wire w1;
 wire [0:7] w2;
 wire [0:17] w3;
 wire w4;
 assign v5b0467 = w0;
 assign v462094 = w1;
 assign vbc8593 = w2;
 assign w3 = v66bc08;
 assign v21f955 = w4;
 vd2823e_v085704 v085704 (
  .data(w0),
  .busy(w1),
  .var(w2),
  .i(w3),
  .req(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- VOB-split  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Virtual output bus Splitter
/*-------------------------------------------------*/

module vd2823e_v085704 (
 input [17:0] i,
 output busy,
 output [7:0] var,
 output [7:0] data,
 output req
);
 assign busy = i[17];
 assign var = i[16:9];
 assign data = i[8:1];
 assign req = i[0];
endmodule
//---- Top entity
module vabe1dc (
 input v7862da,
 input [7:0] ve811db,
 input [7:0] v20eafc,
 input v527976,
 output [17:0] v6902e8
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire w2;
 wire w3;
 wire [0:17] w4;
 assign w0 = v20eafc;
 assign w1 = ve811db;
 assign w2 = v7862da;
 assign w3 = v527976;
 assign v6902e8 = w4;
 vabe1dc_v8ce978 v8ce978 (
  .data(w0),
  .var(w1),
  .busy(w2),
  .req(w3),
  .o(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- VOB-join  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Virtual output bus Joiner
/*-------------------------------------------------*/

module vabe1dc_v8ce978 (
 input busy,
 input [7:0] var,
 input [7:0] data,
 input req,
 output [17:0] o
);
 assign o = {busy, var, data, req};
endmodule
//---- Top entity
module v57e7b3 (
 input [17:0] v079db2,
 input [17:0] v46bdab,
 input v50d6c6,
 output [17:0] v24206e
);
 wire w0;
 wire [0:17] w1;
 wire [0:17] w2;
 wire [0:17] w3;
 assign w0 = v50d6c6;
 assign w1 = v46bdab;
 assign w2 = v079db2;
 assign v24206e = w3;
 v57e7b3_ve4e0df ve4e0df (
  .sel(w0),
  .i0(w1),
  .i1(w2),
  .o(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux 2 a 1 de 18 bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 2 a 1 de 18 bits
/*-------------------------------------------------*/

module v57e7b3_ve4e0df (
 input [17:0] i1,
 input [17:0] i0,
 input sel,
 output [17:0] o
);
 //-- Multiplexor de 2 a 1, 
 //-- de 18 bits
 
 reg [17:0] o;
 
 always @(*) begin
     case(sel)
         0: o = i0;
         1: o = i1;
         default: o = i0;
     endcase
 end
 
 
endmodule
//---- Top entity
module v45c913 (
 input [3:0] v930b03,
 output v5b73e8,
 output vc90115,
 output v2812a7,
 output v593f43
);
 wire [0:3] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v930b03;
 assign v2812a7 = w1;
 assign v593f43 = w2;
 assign vc90115 = w3;
 assign v5b73e8 = w4;
 v45c913_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2),
  .o2(w3),
  .o3(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 4-bits en 4 cables
/*-------------------------------------------------*/

module v45c913_v9a2a06 (
 input [3:0] i,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v686f58 #(
 parameter v19c0b3 = "a"
) (
 input v061a1d,
 input [17:0] v9339c3,
 input v3b85d9,
 output ved8d63,
 output [17:0] v921679,
 output ve9c758
);
 localparam p1 = v19c0b3;
 wire [0:17] w0;
 wire w2;
 wire w3;
 wire w4;
 wire [0:17] w5;
 wire [0:17] w6;
 wire w7;
 assign w2 = v061a1d;
 assign w3 = v061a1d;
 assign ved8d63 = w4;
 assign w5 = v9339c3;
 assign v921679 = w6;
 assign w7 = v3b85d9;
 assign w3 = w2;
 v8d472a vfb1867 (
  .v156ca6(w0),
  .vaa269c(w3),
  .ve70a40(w4),
  .v850be6(w6)
 );
 vbcf605 #(
  .v688ddd(p1)
 ) vdc07ae (
  .vb3bc3f(w0),
  .v31df97(w2),
  .v5e66c1(w5),
  .vea82a4(w7)
 );
endmodule

/*-------------------------------------------------*/
/*-- LEDx1-BUS  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- One Virtual LED with bus expansion
/*-------------------------------------------------*/
//---- Top entity
module v8d472a #(
 parameter v884a28 = 0
) (
 input vaa269c,
 input [17:0] v156ca6,
 output ve70a40,
 output [17:0] v850be6
);
 localparam p5 = v884a28;
 wire [0:9] w0;
 wire w1;
 wire w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:7] w6;
 wire w7;
 wire w8;
 wire w9;
 wire [0:17] w10;
 wire [0:9] w11;
 wire [0:17] w12;
 wire w13;
 wire [0:7] w14;
 wire w15;
 assign w7 = vaa269c;
 assign w8 = vaa269c;
 assign ve70a40 = w9;
 assign v850be6 = w10;
 assign w12 = v156ca6;
 assign w4 = w3;
 assign w8 = w7;
 v42d62e v094f48 (
  .v7704cd(w0),
  .vc080f3(w1),
  .v618174(w7),
  .vc43eff(w11),
  .v8d9058(w13),
  .v5e553e(w14),
  .vf4228a(w15)
 );
 vcb2baf vc29db2 (
  .v0132b5(w0),
  .v5d99f8(w8),
  .v6bd138(w9),
  .vea0053(w11)
 );
 vabe1dc v434536 (
  .v7862da(w1),
  .v527976(w2),
  .ve811db(w3),
  .v20eafc(w4),
  .v6902e8(w10)
 );
 v21cfcc ve6d1b4 (
  .v9fb85f(w2)
 );
 v3bf99b v5af912 (
  .vb096dc(w3)
 );
 vd2823e va333a8 (
  .v5b0467(w6),
  .v66bc08(w12),
  .v21f955(w13),
  .vbc8593(w14)
 );
 vec5121 #(
  .vaf1d6e(p5)
 ) v7250b0 (
  .vdf5b7a(w6),
  .v7ff276(w15)
 );
endmodule

/*-------------------------------------------------*/
/*-- VOB  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Virtual Output Bus
/*-------------------------------------------------*/
//---- Top entity
module v42d62e (
 input v618174,
 input [9:0] vc43eff,
 input v8d9058,
 input [7:0] v5e553e,
 input vf4228a,
 output vf61c63,
 output [9:0] v7704cd,
 output v0122ea,
 output v53ae3b,
 output vc080f3
);
 wire [0:9] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire [0:9] w9;
 wire [0:9] w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire [0:7] w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire [0:7] w21;
 assign w2 = v8d9058;
 assign w3 = v618174;
 assign w4 = v618174;
 assign w5 = v618174;
 assign w6 = v618174;
 assign w7 = v618174;
 assign w8 = v618174;
 assign w9 = vc43eff;
 assign v7704cd = w10;
 assign v0122ea = w13;
 assign w16 = v8d9058;
 assign w17 = v8d9058;
 assign w18 = v8d9058;
 assign w19 = vf4228a;
 assign vc080f3 = w20;
 assign w21 = v5e553e;
 assign w4 = w3;
 assign w5 = w3;
 assign w5 = w4;
 assign w6 = w3;
 assign w6 = w4;
 assign w6 = w5;
 assign w7 = w3;
 assign w7 = w4;
 assign w7 = w5;
 assign w7 = w6;
 assign w8 = w3;
 assign w8 = w4;
 assign w8 = w5;
 assign w8 = w6;
 assign w8 = w7;
 assign w16 = w2;
 assign w17 = w2;
 assign w17 = w16;
 assign w18 = w2;
 assign w18 = w16;
 assign w18 = w17;
 vcda9cd veb2549 (
  .v8497d9(w0),
  .v5000a0(w1),
  .v27dec4(w4),
  .vdc9592(w10),
  .v5a4147(w12),
  .v012beb(w14)
 );
 vae7cd7 v0b426e (
  .v97ade7(w0),
  .vdc231f(w1),
  .vbd1086(w3),
  .v120ed0(w9),
  .v902803(w11),
  .vc33bc9(w15)
 );
 v89d234 v663d13 (
  .v41eb95(w7),
  .vb1c024(w15),
  .vf892a0(w17),
  .v39f831(w21)
 );
 v1c7dae v419021 (
  .vf54559(w2),
  .va4102a(w5),
  .ve8318d(w11)
 );
 v42ebf7 v9d91ab (
  .va4102a(w6),
  .ve8318d(w14),
  .v9afc1f(w16),
  .vf54559(w19)
 );
 v438ded v7e2565 (
  .v68780b(w8),
  .vb414d8(w12),
  .vd82121(w13),
  .v143ae2(w18),
  .v078fce(w20)
 );
endmodule

/*-------------------------------------------------*/
/*-- PrintLn-BitVar  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Print a Bit variable + LF
/*-------------------------------------------------*/
//---- Top entity
module vcda9cd #(
 parameter vb1badc = "1",
 parameter ve8af6c = "0"
) (
 input v27dec4,
 input [9:0] v8497d9,
 input v5000a0,
 input v012beb,
 output v12a425,
 output [9:0] vdc9592,
 output v5a4147,
 output vac598a
);
 localparam p2 = vb1badc;
 localparam p3 = ve8af6c;
 wire [0:7] w0;
 wire w1;
 wire [0:9] w4;
 wire [0:9] w5;
 wire [0:9] w6;
 wire w7;
 wire w8;
 wire [0:9] w9;
 wire [0:9] w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 assign vdc9592 = w5;
 assign w7 = v27dec4;
 assign w8 = v27dec4;
 assign w9 = v8497d9;
 assign w10 = v8497d9;
 assign w11 = v5000a0;
 assign v5a4147 = w12;
 assign w15 = v012beb;
 assign vac598a = w17;
 assign w8 = w7;
 assign w10 = w9;
 assign w17 = w16;
 va0b5a4 v9467ab (
  .vb096dc(w0)
 );
 v816138 v8f1065 (
  .v0e28cb(w13),
  .v3ca442(w14),
  .vcbab45(w16)
 );
 vd18c06 #(
  .v1dc711(p2),
  .vfaa62e(p3)
 ) v23b762 (
  .vdc231f(w1),
  .vcc8343(w4),
  .vbd1086(w7),
  .v768809(w9),
  .v902803(w11),
  .v27e8ef(w13),
  .vc4a5a7(w15)
 );
 vae7cd7 vb42b7c (
  .vc33bc9(w0),
  .v902803(w1),
  .v120ed0(w4),
  .v97ade7(w6),
  .vbd1086(w8),
  .vdc231f(w12),
  .v27e8ef(w14)
 );
 v3e1356 vbcfbc3 (
  .vd25e4b(w5),
  .v3e30ba(w6),
  .v10ee83(w10),
  .v50d6c6(w16)
 );
endmodule

/*-------------------------------------------------*/
/*-- PrintLn-bit  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Print a bit plus a new line
/*-------------------------------------------------*/
//---- Top entity
module va0b5a4 #(
 parameter vfffc23 = "\n"
) (
 output [7:0] vb096dc
);
 localparam p0 = vfffc23;
 wire [0:7] w1;
 assign vb096dc = w1;
 v5ad97e #(
  .vc5c8ea(p0)
 ) v68b2cc (
  .v26dbdb(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_ASCII-LF  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Código ASCII del carácter LF
/*-------------------------------------------------*/
//---- Top entity
module vd18c06 #(
 parameter v1dc711 = "1",
 parameter vfaa62e = "0"
) (
 input vbd1086,
 input [9:0] v768809,
 input v902803,
 input vc4a5a7,
 output v211a87,
 output [9:0] vcc8343,
 output vdc231f,
 output v27e8ef
);
 localparam p1 = v1dc711;
 localparam p2 = vfaa62e;
 wire [0:7] w0;
 wire [0:7] w3;
 wire w4;
 wire w5;
 wire [0:9] w6;
 wire [0:9] w7;
 wire [0:9] w8;
 wire w9;
 wire w10;
 wire [0:9] w11;
 wire w12;
 wire [0:7] w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 assign vcc8343 = w6;
 assign w8 = v768809;
 assign w9 = vbd1086;
 assign w10 = vbd1086;
 assign w11 = v768809;
 assign v27e8ef = w17;
 assign w18 = v902803;
 assign w19 = vc4a5a7;
 assign vdc231f = w20;
 assign w10 = w9;
 assign w11 = w8;
 assign w16 = w15;
 assign w17 = w15;
 assign w17 = w16;
 vb2090f v81bc38 (
  .vcbab45(w5),
  .v3ca442(w12),
  .v0e28cb(w16)
 );
 v359a55 v9a50e1 (
  .v02d898(w0),
  .vd6b984(w3),
  .v50d6c6(w4),
  .vf24dba(w13)
 );
 v5ad97e #(
  .vc5c8ea(p1)
 ) v79981a (
  .v26dbdb(w0)
 );
 v5ad97e #(
  .vc5c8ea(p2)
 ) v6bef96 (
  .v26dbdb(w3)
 );
 v1c7dae v89ee72 (
  .ve8318d(w4),
  .va4102a(w10),
  .vf54559(w19)
 );
 v438ded v877641 (
  .vb414d8(w5),
  .v68780b(w9),
  .vf2d070(w14),
  .v078fce(w15),
  .v143ae2(w18),
  .vd82121(w20)
 );
 v3e1356 v636844 (
  .vd25e4b(w6),
  .v3e30ba(w7),
  .v10ee83(w11),
  .v50d6c6(w15)
 );
 vdfb235 v407d5e (
  .v96fa77(w7),
  .v20eafc(w13),
  .v527976(w14)
 );
 v46cae7 va57649 (
  .v60bfad(w8),
  .v76156c(w12)
 );
endmodule

/*-------------------------------------------------*/
/*-- putc-bit-stdout  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*--  Transmit one bit as a character. STDOUT-bus
/*-------------------------------------------------*/
//---- Top entity
module v359a55 (
 input [7:0] v02d898,
 input [7:0] vd6b984,
 input v50d6c6,
 output [7:0] vf24dba
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 assign w0 = v50d6c6;
 assign w1 = vd6b984;
 assign w2 = v02d898;
 assign vf24dba = w3;
 v359a55_ve4e0df ve4e0df (
  .sel(w0),
  .i0(w1),
  .i1(w2),
  .o(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux 2 a 1 de 8 bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 2 a 1 de 8 bits
/*-------------------------------------------------*/

module v359a55_ve4e0df (
 input [7:0] i1,
 input [7:0] i0,
 input sel,
 output [7:0] o
);
 //-- Multiplexor de 2 a 1, 
 //-- de 8 bits
 
 reg [7:0] o;
 
 always @(*) begin
     case(sel)
         0: o = i0;
         1: o = i1;
         default: o = i0;
     endcase
 end
 
 
endmodule
//---- Top entity
module v438ded (
 input v68780b,
 input v143ae2,
 input vb414d8,
 output v078fce,
 output v3525a9,
 output vf2d070,
 output vd82121
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 assign v078fce = w1;
 assign v3525a9 = w3;
 assign w4 = v143ae2;
 assign w5 = vb414d8;
 assign vf2d070 = w6;
 assign vd82121 = w7;
 assign w8 = v68780b;
 assign w9 = v68780b;
 assign w1 = w0;
 assign w2 = w0;
 assign w2 = w1;
 assign w9 = w8;
 vb959c2 v551aec (
  .vb4c770(w0),
  .ve68648(w4),
  .v3c6908(w5),
  .v581b48(w8)
 );
 vc386a7 v838318 (
  .ve78ab8(w0),
  .v3487af(w6),
  .vb1094d(w7),
  .ved8395(w9)
 );
 v35f267 v719db6 (
  .v0e28cb(w2),
  .vcbab45(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Machine-state  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Biestable de almacenamiento del estado de la máquina
/*-------------------------------------------------*/
//---- Top entity
module vc386a7 (
 input ved8395,
 input ve78ab8,
 output v3487af,
 output vb1094d
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w0 = ved8395;
 assign w1 = ve78ab8;
 assign v3487af = w2;
 assign vb1094d = w3;
 vc386a7_v287d69 v287d69 (
  .clk(w0),
  .i(w1),
  .up(w2),
  .down(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Detector-flancos  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Detector de flancos de subida y bajada. Emite tic por las salidas correspondientes al detecta los flancos
/*-------------------------------------------------*/

module vc386a7_v287d69 (
 input clk,
 input i,
 output up,
 output down
);
 reg q = 0;
 
 always @(posedge clk)
   q <= i;
   
 assign up = (~q & i);  
 assign down = (q & ~i);  
endmodule
//---- Top entity
module v3e1356 (
 input [9:0] v3e30ba,
 input [9:0] v10ee83,
 input v50d6c6,
 output [9:0] vd25e4b
);
 wire w0;
 wire [0:9] w1;
 wire [0:9] w2;
 wire [0:9] w3;
 assign w0 = v50d6c6;
 assign vd25e4b = w1;
 assign w2 = v3e30ba;
 assign w3 = v10ee83;
 v3e1356_ve4e0df ve4e0df (
  .sel(w0),
  .o(w1),
  .i1(w2),
  .i0(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- 10bits-2-1-Mux  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 10 bits, 2-1 Multiplexor
/*-------------------------------------------------*/

module v3e1356_ve4e0df (
 input [9:0] i1,
 input [9:0] i0,
 input sel,
 output [9:0] o
);
 
 reg [9:0] o;
 
 always @(*) begin
     case(sel)
         0: o = i0;
         1: o = i1;
         default: o = i0;
     endcase
 end
 
 
endmodule
//---- Top entity
module vdfb235 (
 input [7:0] v20eafc,
 input v527976,
 output [9:0] v96fa77
);
 wire [0:7] w0;
 wire w1;
 wire [0:9] w2;
 assign w0 = v20eafc;
 assign w1 = v527976;
 assign v96fa77 = w2;
 vdfb235_v9a2a06 v9a2a06 (
  .i(w0),
  .tic(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- stdout-bus-joint2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- stdout bus joiner (data + tic)
/*-------------------------------------------------*/

module vdfb235_v9a2a06 (
 input [7:0] i,
 input tic,
 output [9:0] o
);
 assign o[9:1] = {i, tic};
endmodule
//---- Top entity
module v46cae7 (
 input [9:0] v60bfad,
 output v76156c
);
 wire w0;
 wire [0:9] w1;
 assign v76156c = w0;
 assign w1 = v60bfad;
 v46cae7_v9a2a06 v9a2a06 (
  .o(w0),
  .i(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- stdout-bus-next-out  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Extract the next signal from the stdout bus
/*-------------------------------------------------*/

module v46cae7_v9a2a06 (
 input [9:0] i,
 output o
);
 assign o = i[0];
endmodule
//---- Top entity
module vae7cd7 (
 input vbd1086,
 input [9:0] v120ed0,
 input v902803,
 input [7:0] vc33bc9,
 output vb0620c,
 output [9:0] v97ade7,
 output vdc231f,
 output v27e8ef
);
 wire w0;
 wire [0:9] w1;
 wire [0:9] w2;
 wire [0:9] w3;
 wire w4;
 wire [0:9] w5;
 wire [0:7] w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 assign w1 = v120ed0;
 assign v97ade7 = w2;
 assign w4 = vbd1086;
 assign w5 = v120ed0;
 assign w6 = vc33bc9;
 assign v27e8ef = w11;
 assign w12 = v902803;
 assign vdc231f = w13;
 assign w5 = w1;
 assign w10 = w9;
 assign w11 = w9;
 assign w11 = w10;
 vb2090f v81bc38 (
  .vcbab45(w0),
  .v3ca442(w7),
  .v0e28cb(w10)
 );
 v438ded v1cee7c (
  .vb414d8(w0),
  .v68780b(w4),
  .vf2d070(w8),
  .v078fce(w9),
  .v143ae2(w12),
  .vd82121(w13)
 );
 v46cae7 vf5fdaa (
  .v60bfad(w1),
  .v76156c(w7)
 );
 v3e1356 v784229 (
  .vd25e4b(w2),
  .v3e30ba(w3),
  .v10ee83(w5),
  .v50d6c6(w9)
 );
 vdfb235 v4f4693 (
  .v96fa77(w3),
  .v20eafc(w6),
  .v527976(w8)
 );
endmodule

/*-------------------------------------------------*/
/*-- putc-char  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Transmit one character to the STDOUT bus
/*-------------------------------------------------*/
//---- Top entity
module v89d234 #(
 parameter v422d28 = 0
) (
 input v41eb95,
 input [7:0] v39f831,
 input vf892a0,
 output [7:0] vb1c024
);
 localparam p0 = v422d28;
 wire [0:7] w1;
 wire [0:7] w2;
 wire w3;
 wire w4;
 assign vb1c024 = w1;
 assign w2 = v39f831;
 assign w3 = vf892a0;
 assign w4 = v41eb95;
 v89d234_v9148cb #(
  .INI(p0)
 ) v9148cb (
  .q(w1),
  .d(w2),
  .load(w3),
  .clk(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Registro  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Registro de 8 bits
/*-------------------------------------------------*/

module v89d234_v9148cb #(
 parameter INI = 0
) (
 input clk,
 input [7:0] d,
 input load,
 output [7:0] q
);
 localparam N = 8;
 
 reg [N-1:0] q = INI;
 
 always @(posedge clk)
   if (load)
     q <= d;
endmodule
//---- Top entity
module vcb2baf #(
 parameter v0e67a4 = 115200
) (
 input v5d99f8,
 input [9:0] v0132b5,
 input v2f1423,
 output v6bd138,
 output [9:0] vea0053,
 output v4642b6
);
 localparam p4 = v0e67a4;
 wire [0:7] w0;
 wire w1;
 wire w2;
 wire [0:9] w3;
 wire w5;
 wire w6;
 wire w7;
 wire [0:9] w8;
 assign w3 = v0132b5;
 assign w5 = v5d99f8;
 assign v6bd138 = w6;
 assign v4642b6 = w7;
 assign vea0053 = w8;
 vc6459c #(
  .ved2ada(p4)
 ) v935ca4 (
  .v19b8dd(w0),
  .v05e99b(w1),
  .v01321e(w2),
  .ve9a78f(w5),
  .v8caaa5(w6),
  .v2da441(w7)
 );
 vc955cf vb8ce18 (
  .v9aec09(w0),
  .vbd457d(w1),
  .v50e179(w3)
 );
 v113ccf v2dd285 (
  .v451d7d(w2),
  .vc18091(w8)
 );
endmodule

/*-------------------------------------------------*/
/*-- stdout-serial  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Serial transmiter for the stdout bus
/*-------------------------------------------------*/
//---- Top entity
module vc6459c #(
 parameter ved2ada = 115200
) (
 input ve9a78f,
 input [7:0] v19b8dd,
 input v05e99b,
 output v8caaa5,
 output v2da441,
 output v01321e
);
 localparam p1 = ved2ada;
 wire w0;
 wire w2;
 wire [0:7] w3;
 wire w4;
 wire w5;
 wire w6;
 assign v8caaa5 = w0;
 assign w2 = ve9a78f;
 assign w3 = v19b8dd;
 assign w4 = v05e99b;
 assign v2da441 = w5;
 assign v01321e = w6;
 vc6459c_vedebcc #(
  .BAUD(p1)
 ) vedebcc (
  .TX(w0),
  .clk(w2),
  .data(w3),
  .txmit(w4),
  .busy(w5),
  .done(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- Serial-tx  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Transmisor serie
/*-------------------------------------------------*/

module vc6459c_vedebcc #(
 parameter BAUD = 0
) (
 input clk,
 input [7:0] data,
 input txmit,
 output TX,
 output busy,
 output done
);
 //-- Constantes para obtener las velocidades estándares
 `define B115200 104 
 `define B57600  208
 `define B38400  313
 `define B19200  625
 `define B9600   1250
 `define B4800   2500
 `define B2400   5000
 `define B1200   10000
 `define B600    20000
 `define B300    40000
 
 //-- Constante para calcular los baudios
 localparam BAUDRATE = (BAUD==115200) ? `B115200 : //-- OK
                       (BAUD==57600)  ? `B57600  : //-- OK
                       (BAUD==38400)  ? `B38400  : //-- Ok
                       (BAUD==19200)  ? `B19200  : //-- OK
                       (BAUD==9600)   ? `B9600   : //-- OK
                       (BAUD==4800)   ? `B4800   : //-- OK 
                       (BAUD==2400)   ? `B2400   : //-- OK
                       (BAUD==1200)   ? `B1200   : //-- OK
                       (BAUD==600)    ? `B600    : //-- OK
                       (BAUD==300)    ? `B300    : //-- OK
                       `B115200 ;  //-- Por defecto 115200 baudios
 
 
 //---- GENERADOR DE BAUDIOS
 
 //-- Calcular el numero dde bits para almacenar el divisor
 localparam N = $clog2(BAUDRATE);
 
 //-- Contador para implementar el divisor
 //-- Es un contador modulo BAUDRATE
 reg [N-1:0] divcounter = 0;
 
 //-- Cable de reset para el contador
 //-- Comparador que resetea el contador cuando se alcanza el tope
 //-- o cuando el estado del biestable es 0 (apagado)
 wire reset = ov_gen | (state == 0);
 
 //-- Contador con reset
 always @(posedge clk)
   if (reset)
     divcounter <= 0;
   else
     divcounter <= divcounter + 1;
 
 //-- Hemos llegado al final
 wire ov_gen = (divcounter == BAUDRATE-1);
 
 
 
 //-- REGISTRO DESPLAZAMIENTO
 
 //-- Salida serie. Inicialmete a 1 (reposo) 
 reg TX = 1;
 
 //-- Registro de desplazamiento de 9 bits
 //-- Inicializado todo a 1s
 reg [8:0] q = 9'h1FF;
 
 //-- La entrada de shift es la salida del generador de baudios
 wire shift = ov_gen;
 
 always @(posedge clk)
   if (txmit_tic)
   //-- Carga del registro
     q <= {data, 1'b0};
     
   else if (shift)
     //-- Desplazamiento. Rellenar con 1 (bit de stop)
     q <= {1'b1, q[8:1]};
     
 //-- Sacar el bit de menor peso por serial-out    
 wire so;
 assign so = q[0];
 
 //-- La salida tx la registramos
 always @(posedge clk)
   TX <= so;
   
 //-- La señal de entrada txmit se pasa por un 
 //-- detector de flancos de subida para generar un tic
 reg q_re = 0;
 wire txmit_tic;
 
 always @(posedge clk)
   q_re <= txmit;
   
 assign txmit_tic = (~q_re & txmit);  
 
 
 
 //-- Estado de transmisor
 //-- 0: Parado
 //-- 1: Ocupado (transmitiendo)
 reg state = 0;
   
 always @(posedge clk)
   //-- Empieza la transmision: ocupado
   if (txmit)
     state <= 1'b1;
     
   //-- Acaba la transmision: libre    
   else if (ov)
     state <= 1'b0;
 
 //-- Contador de bits enviados
 reg [3:0] bits = 0;
 always @(posedge clk)
   //-- Si la cuenta ha terminado... volver a 0
   if (ov)
     bits <= 2'b00;
   else
     if (shift)
       bits <= bits + 1;
 
 //-- Comprobar si se ha transmitido el último bit (overflow)
 //-- 1 bit de start + 8 bits de datos + 1 bit de stop
 wire ov = (bits == 10);
 
 //-- La señal de ocupado es el estado del transmisor
 assign busy = state;
 
 //-- La señal de done es la de overflow pero retrasada un
 //-- periodo de reloj del sistema y que el biestable 
 //-- llegue al estado de parado antes de que se 
 //-- empiece otra transmision
 
 reg done=0;
 
 always @(posedge clk)
   done <= ov;
 
endmodule
//---- Top entity
module vc955cf (
 input [9:0] v50e179,
 output [7:0] v9aec09,
 output vbd457d
);
 wire [0:7] w0;
 wire w1;
 wire [0:9] w2;
 assign v9aec09 = w0;
 assign vbd457d = w1;
 assign w2 = v50e179;
 vc955cf_v9a2a06 v9a2a06 (
  .data(w0),
  .tic(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- stdout-bus-split2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- stdout bus splitter into data and tic signals
/*-------------------------------------------------*/

module vc955cf_v9a2a06 (
 input [9:0] i,
 output [7:0] data,
 output tic
);
 assign data = i[9:2];
 assign tic = i[1];
endmodule
//---- Top entity
module v113ccf (
 input v451d7d,
 output [9:0] vc18091
);
 wire w0;
 wire [0:9] w1;
 assign w0 = v451d7d;
 assign vc18091 = w1;
 v113ccf_v9a2a06 v9a2a06 (
  .next(w0),
  .o(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- stdout-bus-next-in  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Convert the 1-bit next signal into a 10-bit stdout bus
/*-------------------------------------------------*/

module v113ccf_v9a2a06 (
 input next,
 output [9:0] o
);
 assign o[0] = next;
endmodule
//---- Top entity
module v3bf99b #(
 parameter vfffc23 = 0
) (
 output [7:0] vb096dc
);
 localparam p0 = vfffc23;
 wire [0:7] w1;
 assign vb096dc = w1;
 v5ad97e #(
  .vc5c8ea(p0)
 ) v68b2cc (
  .v26dbdb(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_0_8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 0 para bus de 8 bits
/*-------------------------------------------------*/
//---- Top entity
module v4c66ed #(
 parameter v679028 = "a",
 parameter v2583b8 = "b",
 parameter v96c5b2 = "c",
 parameter v251a02 = "d"
) (
 input v294f2a,
 input [17:0] vb7eca5,
 input [3:0] vec6453,
 output va5c2ac,
 output [17:0] v954064,
 output vf4f51f
);
 localparam p0 = v679028;
 localparam p3 = v2583b8;
 localparam p9 = v96c5b2;
 localparam p10 = v251a02;
 wire w1;
 wire [0:17] w2;
 wire w4;
 wire [0:17] w5;
 wire w6;
 wire [0:17] w7;
 wire w8;
 wire [0:17] w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire [0:17] w16;
 wire [0:3] w17;
 assign v954064 = w11;
 assign w12 = v294f2a;
 assign w13 = v294f2a;
 assign w14 = v294f2a;
 assign w15 = v294f2a;
 assign w16 = vb7eca5;
 assign w17 = vec6453;
 assign w13 = w12;
 assign w14 = w12;
 assign w14 = w13;
 assign w15 = w12;
 assign w15 = w13;
 assign w15 = w14;
 vbcf605 #(
  .v688ddd(p0)
 ) v6adc86 (
  .vea82a4(w1),
  .vb3bc3f(w2),
  .v31df97(w12),
  .v5e66c1(w16)
 );
 v45c913 v7d31b0 (
  .v5b73e8(w1),
  .vc90115(w4),
  .v2812a7(w6),
  .v593f43(w8),
  .v930b03(w17)
 );
 vbcf605 #(
  .v688ddd(p3)
 ) v8fd1cc (
  .v5e66c1(w2),
  .vea82a4(w4),
  .vb3bc3f(w5),
  .v31df97(w13)
 );
 vbcf605 #(
  .v688ddd(p9)
 ) v95860b (
  .v5e66c1(w5),
  .vea82a4(w6),
  .vb3bc3f(w7),
  .v31df97(w14)
 );
 vbcf605 #(
  .v688ddd(p10)
 ) v9ce3f8 (
  .v5e66c1(w7),
  .vea82a4(w8),
  .vb3bc3f(w11),
  .v31df97(w15)
 );
endmodule

/*-------------------------------------------------*/
/*-- LEDx4-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Four virtual LEDs. Bus block
/*-------------------------------------------------*/
//---- Top entity
module v26f57a (
 input [15:0] vad1323,
 output [7:0] vf774e8,
 output [7:0] v0e9841
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:15] w2;
 assign v0e9841 = w0;
 assign vf774e8 = w1;
 assign w2 = vad1323;
 v26f57a_v9a2a06 v9a2a06 (
  .o0(w0),
  .o1(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 16-bits en buses de 8 bits
/*-------------------------------------------------*/

module v26f57a_v9a2a06 (
 input [15:0] i,
 output [7:0] o1,
 output [7:0] o0
);
 assign o1 = i[15:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module v1a2506 #(
 parameter v11a07f = "a",
 parameter vd1c7d9 = "b",
 parameter v077ede = "c",
 parameter va86b54 = "d",
 parameter v128381 = "e",
 parameter vdc93ce = "f",
 parameter va57579 = "g",
 parameter ve245ce = "h"
) (
 input v294f2a,
 input [17:0] vb7eca5,
 input [7:0] v20f04d,
 output va5c2ac,
 output [17:0] v954064,
 output vf4f51f
);
 localparam p1 = va57579;
 localparam p2 = vdc93ce;
 localparam p3 = v128381;
 localparam p6 = va86b54;
 localparam p7 = v077ede;
 localparam p8 = vd1c7d9;
 localparam p9 = v11a07f;
 localparam p11 = ve245ce;
 wire [0:3] w0;
 wire [0:17] w4;
 wire [0:3] w5;
 wire [0:17] w10;
 wire w12;
 wire w13;
 wire [0:17] w14;
 wire [0:7] w15;
 assign v954064 = w10;
 assign w12 = v294f2a;
 assign w13 = v294f2a;
 assign w14 = vb7eca5;
 assign w15 = v20f04d;
 assign w13 = w12;
 v73403c ved7804 (
  .v85accc(w0),
  .vf9119c(w5),
  .v595263(w15)
 );
 v4c66ed #(
  .v251a02(p6),
  .v96c5b2(p7),
  .v2583b8(p8),
  .v679028(p9)
 ) v8d7ccf (
  .v954064(w4),
  .vec6453(w5),
  .v294f2a(w13),
  .vb7eca5(w14)
 );
 v4c66ed #(
  .v96c5b2(p1),
  .v2583b8(p2),
  .v679028(p3),
  .v251a02(p11)
 ) v3f3286 (
  .vec6453(w0),
  .vb7eca5(w4),
  .v954064(w10),
  .v294f2a(w12)
 );
endmodule

/*-------------------------------------------------*/
/*-- LEDx8-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Eight virtual LEDs. Bus block
/*-------------------------------------------------*/
//---- Top entity
module v56b4c6 #(
 parameter v11a07f = "a",
 parameter vd1c7d9 = "b",
 parameter v077ede = "c",
 parameter va86b54 = "d",
 parameter v128381 = "e",
 parameter vdc93ce = "f",
 parameter va57579 = "g",
 parameter ve245ce = "h",
 parameter v3a4133 = "i",
 parameter va79108 = "j",
 parameter v16f1c7 = "k",
 parameter v7afcff = "l",
 parameter vbbb21b = "m",
 parameter v6ac546 = "n",
 parameter vadaccd = "o",
 parameter v455918 = "p"
) (
 input v294f2a,
 input [17:0] vb7eca5,
 input [15:0] v4dd039,
 output va5c2ac,
 output [17:0] v954064,
 output vf4f51f
);
 localparam p0 = v3a4133;
 localparam p1 = va79108;
 localparam p2 = v16f1c7;
 localparam p3 = v7afcff;
 localparam p4 = vbbb21b;
 localparam p5 = v6ac546;
 localparam p6 = vadaccd;
 localparam p7 = v455918;
 localparam p11 = v11a07f;
 localparam p12 = vd1c7d9;
 localparam p13 = v077ede;
 localparam p14 = va86b54;
 localparam p15 = v128381;
 localparam p16 = vdc93ce;
 localparam p17 = va57579;
 localparam p18 = ve245ce;
 wire [0:7] w8;
 wire [0:7] w9;
 wire [0:17] w10;
 wire [0:17] w19;
 wire w20;
 wire w21;
 wire [0:17] w22;
 wire [0:15] w23;
 assign v954064 = w10;
 assign w20 = v294f2a;
 assign w21 = v294f2a;
 assign w22 = vb7eca5;
 assign w23 = v4dd039;
 assign w21 = w20;
 v26f57a v9d7794 (
  .v0e9841(w8),
  .vf774e8(w9),
  .vad1323(w23)
 );
 v1a2506 #(
  .v11a07f(p11),
  .vd1c7d9(p12),
  .v077ede(p13),
  .va86b54(p14),
  .v128381(p15),
  .vdc93ce(p16),
  .va57579(p17),
  .ve245ce(p18)
 ) vaf23ea (
  .v20f04d(w9),
  .v954064(w19),
  .v294f2a(w21),
  .vb7eca5(w22)
 );
 v1a2506 #(
  .v11a07f(p0),
  .vd1c7d9(p1),
  .v077ede(p2),
  .va86b54(p3),
  .v128381(p4),
  .vdc93ce(p5),
  .va57579(p6),
  .ve245ce(p7)
 ) v5776e9 (
  .v20f04d(w8),
  .v954064(w10),
  .vb7eca5(w19),
  .v294f2a(w20)
 );
endmodule

/*-------------------------------------------------*/
/*-- LEDx16-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 16 virtual LEDs. Bus block
/*-------------------------------------------------*/
//---- Top entity
module v1e224f (
 input [7:0] v385b9c,
 input [7:0] vd34531,
 output [15:0] v4d4dee
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:15] w2;
 assign w0 = vd34531;
 assign w1 = v385b9c;
 assign v4d4dee = w2;
 v1e224f_v9a2a06 v9a2a06 (
  .i0(w0),
  .i1(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 2 buses de 8-bits a bus de 16-bits
/*-------------------------------------------------*/

module v1e224f_v9a2a06 (
 input [7:0] i1,
 input [7:0] i0,
 output [15:0] o
);
 assign o = {i1, i0};
 
endmodule
