// Code generated by Icestudio 0.7.0

`default_nettype none

//---- Top entity
module main (
 input [7:0] vbfdb97,
 input [7:0] vc2ef4f,
 input v78b22f,
 output [31:0] v961ee9,
 output [31:0] vd115bb,
 output [7:0] v84ec18,
 output [0:7] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire [0:5] w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire [0:3] w15;
 wire [0:3] w16;
 wire [0:1] w17;
 wire [0:1] w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire [0:3] w25;
 wire [0:3] w26;
 wire [0:7] w27;
 wire [0:7] w28;
 wire [0:7] w29;
 wire w30;
 wire w31;
 wire [0:7] w32;
 wire [0:7] w33;
 wire [0:7] w34;
 wire [0:7] w35;
 wire [0:7] w36;
 wire [0:31] w37;
 wire [0:31] w38;
 wire [0:7] w39;
 wire [0:7] w40;
 wire [0:7] w41;
 wire [0:7] w42;
 wire [0:7] w43;
 wire w44;
 wire w45;
 wire [0:7] w46;
 wire [0:7] w47;
 wire [0:7] w48;
 wire [0:7] w49;
 wire [0:7] w50;
 wire [0:7] w51;
 wire [0:7] w52;
 wire [0:7] w53;
 assign w3 = v78b22f;
 assign w4 = v78b22f;
 assign w5 = v78b22f;
 assign w6 = v78b22f;
 assign w7 = v78b22f;
 assign w8 = v78b22f;
 assign w9 = v78b22f;
 assign w27 = vc2ef4f;
 assign v961ee9 = w37;
 assign vd115bb = w38;
 assign v84ec18 = w43;
 assign w44 = v78b22f;
 assign w46 = vbfdb97;
 assign w47 = vbfdb97;
 assign w48 = vbfdb97;
 assign w49 = vbfdb97;
 assign w50 = vbfdb97;
 assign w51 = vbfdb97;
 assign w52 = vbfdb97;
 assign w53 = vbfdb97;
 assign w4 = w3;
 assign w5 = w3;
 assign w5 = w4;
 assign w6 = w3;
 assign w6 = w4;
 assign w6 = w5;
 assign w7 = w3;
 assign w7 = w4;
 assign w7 = w5;
 assign w7 = w6;
 assign w8 = w3;
 assign w8 = w4;
 assign w8 = w5;
 assign w8 = w6;
 assign w8 = w7;
 assign w9 = w3;
 assign w9 = w4;
 assign w9 = w5;
 assign w9 = w6;
 assign w9 = w7;
 assign w9 = w8;
 assign w40 = w29;
 assign w43 = w29;
 assign w43 = w40;
 assign w44 = w3;
 assign w44 = w4;
 assign w44 = w5;
 assign w44 = w6;
 assign w44 = w7;
 assign w44 = w8;
 assign w44 = w9;
 assign w47 = w46;
 assign w48 = w46;
 assign w48 = w47;
 assign w49 = w46;
 assign w49 = w47;
 assign w49 = w48;
 assign w50 = w46;
 assign w50 = w47;
 assign w50 = w48;
 assign w50 = w49;
 assign w51 = w46;
 assign w51 = w47;
 assign w51 = w48;
 assign w51 = w49;
 assign w51 = w50;
 assign w52 = w46;
 assign w52 = w47;
 assign w52 = w48;
 assign w52 = w49;
 assign w52 = w50;
 assign w52 = w51;
 assign w53 = w46;
 assign w53 = w47;
 assign w53 = w48;
 assign w53 = w49;
 assign w53 = w50;
 assign w53 = w51;
 assign w53 = w52;
 v89d234 v00cf70 (
  .v41eb95(w3),
  .vf892a0(w21),
  .vb1c024(w33),
  .v39f831(w46)
 );
 v89d234 v52e8e8 (
  .v41eb95(w4),
  .vf892a0(w22),
  .vb1c024(w34),
  .v39f831(w47)
 );
 v89d234 v3a923a (
  .v41eb95(w5),
  .vf892a0(w23),
  .vb1c024(w35),
  .v39f831(w48)
 );
 v89d234 v5a42b0 (
  .v41eb95(w6),
  .vf892a0(w24),
  .vb1c024(w36),
  .v39f831(w49)
 );
 v89d234 vc3d5eb (
  .vf892a0(w0),
  .v41eb95(w7),
  .vb1c024(w39),
  .v39f831(w50)
 );
 v89d234 v3b4bcb (
  .vb1c024(w29),
  .vf892a0(w30),
  .v39f831(w32),
  .v41eb95(w45)
 );
 v89d234 vdb2ed9 (
  .vf892a0(w1),
  .v41eb95(w8),
  .vb1c024(w41),
  .v39f831(w52)
 );
 v89d234 ve77b64 (
  .vf892a0(w2),
  .v41eb95(w9),
  .vb1c024(w42),
  .v39f831(w53)
 );
 v45c913 v46cbae (
  .v593f43(w0),
  .vc90115(w1),
  .v5b73e8(w2),
  .v930b03(w26),
  .v2812a7(w31)
 );
 v7404e6 v9184a8 (
  .v4ce39b(w10),
  .v595263(w27)
 );
 vd4bd04 v776aa2 (
  .v03aaf0(w11),
  .vee8a83(w12),
  .v67a3fc(w18)
 );
 vd4bd04 v474d28 (
  .v03aaf0(w13),
  .vee8a83(w14),
  .v67a3fc(w17)
 );
 vfd8998 v289c22 (
  .vbb390a(w10),
  .v45ab8c(w11),
  .vb85197(w12),
  .v8f149e(w13),
  .v7c37b3(w14),
  .ve0c1b4(w19),
  .v2c9812(w20)
 );
 v1c4cc4 va801cf (
  .v9c304b(w16),
  .v827425(w17)
 );
 v13d09a ve0ffcc (
  .vd317b3(w16),
  .v76af38(w20),
  .ve2642f(w26)
 );
 v1c4cc4 va6e1f2 (
  .v9c304b(w15),
  .v827425(w18)
 );
 v13d09a v81f649 (
  .vd317b3(w15),
  .v76af38(w19),
  .ve2642f(w25)
 );
 v45c913 v3f14be (
  .v593f43(w21),
  .v2812a7(w22),
  .vc90115(w23),
  .v5b73e8(w24),
  .v930b03(w25)
 );
 v359a55 ve3d83e (
  .vd6b984(w28),
  .v50d6c6(w31),
  .vf24dba(w32),
  .v02d898(w51)
 );
 v7d7474 v973e98 (
  .v9c083a(w28),
  .ve41da3(w29)
 );
 v725b7e v1dca89 (
  .v9fb85f(w30)
 );
 vb6ddba vc7c352 (
  .v9999de(w33),
  .v63d71a(w34),
  .v32ad8d(w35),
  .v7a6a68(w36),
  .v2eef2f(w37)
 );
 vb6ddba v72b1e4 (
  .v2eef2f(w38),
  .v9999de(w39),
  .v63d71a(w40),
  .v32ad8d(w41),
  .v7a6a68(w42)
 );
 v96f098 v81616d (
  .v0e28cb(w44),
  .vcbab45(w45)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*-- reg1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v89d234 #(
 parameter v422d28 = 0
) (
 input v41eb95,
 input [7:0] v39f831,
 input vf892a0,
 output [7:0] vb1c024
);
 localparam p0 = v422d28;
 wire [0:7] w1;
 wire [0:7] w2;
 wire w3;
 wire w4;
 assign vb1c024 = w1;
 assign w2 = v39f831;
 assign w3 = vf892a0;
 assign w4 = v41eb95;
 v89d234_v9148cb #(
  .INI(p0)
 ) v9148cb (
  .q(w1),
  .d(w2),
  .load(w3),
  .clk(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Registro  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Registro de 8 bits
/*-------------------------------------------------*/

module v89d234_v9148cb #(
 parameter INI = 0
) (
 input clk,
 input [7:0] d,
 input load,
 output [7:0] q
);
 localparam N = 8;
 
 reg [N-1:0] q = INI;
 
 always @(posedge clk)
   if (load)
     q <= d;
endmodule
//---- Top entity
module v45c913 (
 input [3:0] v930b03,
 output v5b73e8,
 output vc90115,
 output v2812a7,
 output v593f43
);
 wire [0:3] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v930b03;
 assign v2812a7 = w1;
 assign v593f43 = w2;
 assign vc90115 = w3;
 assign v5b73e8 = w4;
 v45c913_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2),
  .o2(w3),
  .o3(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 4-bits en 4 cables
/*-------------------------------------------------*/

module v45c913_v9a2a06 (
 input [3:0] i,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v7404e6 (
 input [7:0] v595263,
 output [1:0] vd7d1f4,
 output [5:0] v4ce39b
);
 wire [0:7] w0;
 wire [0:1] w1;
 wire [0:5] w2;
 assign w0 = v595263;
 assign vd7d1f4 = w1;
 assign v4ce39b = w2;
 v7404e6_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus-2-6  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 8-bits en 2 buses de 2 y 6 bits
/*-------------------------------------------------*/

module v7404e6_v9a2a06 (
 input [7:0] i,
 output [1:0] o1,
 output [5:0] o0
);
 assign o1 = i[7:6];
 assign o0 = i[5:0];
endmodule
//---- Top entity
module vd4bd04 (
 input vee8a83,
 input v03aaf0,
 output [1:0] v67a3fc
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign v67a3fc = w2;
 vd4bd04_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 2 cables en un bus de 2-bits
/*-------------------------------------------------*/

module vd4bd04_v9a2a06 (
 input i1,
 input i0,
 output [1:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vfd8998 (
 input [5:0] vbb390a,
 output v2c9812,
 output ve0c1b4,
 output v7c37b3,
 output v8f149e,
 output vb85197,
 output v45ab8c
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:5] w6;
 assign v2c9812 = w0;
 assign ve0c1b4 = w1;
 assign v7c37b3 = w2;
 assign v8f149e = w3;
 assign vb85197 = w4;
 assign v45ab8c = w5;
 assign w6 = vbb390a;
 vfd8998_v9a2a06 v9a2a06 (
  .o5(w0),
  .o4(w1),
  .o3(w2),
  .o2(w3),
  .o1(w4),
  .o0(w5),
  .i(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 6-bits en 6 cables
/*-------------------------------------------------*/

module vfd8998_v9a2a06 (
 input [5:0] i,
 output o5,
 output o4,
 output o3,
 output o2,
 output o1,
 output o0
);
 
 
 assign o5 = i[5];
 assign o4 = i[4];
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v1c4cc4 (
 input [1:0] v827425,
 output [3:0] v9c304b
);
 wire [0:1] w0;
 wire [0:3] w1;
 assign w0 = v827425;
 assign v9c304b = w1;
 v1c4cc4_v3d7f3a v3d7f3a (
  .y(w0),
  .i(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Decodificador-2-4-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Decodificador de 2 a 4, con salida en bus
/*-------------------------------------------------*/

module v1c4cc4_v3d7f3a (
 input [1:0] y,
 output [3:0] i
);
 assign i = 1 << y;
                        
 
endmodule
//---- Top entity
module v13d09a (
 input [3:0] vd317b3,
 input v76af38,
 output [3:0] ve2642f
);
 wire w0;
 wire [0:3] w1;
 wire [0:3] w2;
 assign w0 = v76af38;
 assign w1 = vd317b3;
 assign ve2642f = w2;
 v13d09a_vce9fab vce9fab (
  .b(w0),
  .a(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND-4-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta AND de dos operandos, de 1 y 4 bits
/*-------------------------------------------------*/

module v13d09a_vce9fab (
 input [3:0] a,
 input b,
 output [3:0] o
);
 assign o[3] = a[3] & b;
 assign o[2] = a[2] & b;
 assign o[1] = a[1] & b;
 assign o[0] = a[0] & b;
endmodule
//---- Top entity
module v359a55 (
 input [7:0] v02d898,
 input [7:0] vd6b984,
 input v50d6c6,
 output [7:0] vf24dba
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 assign w0 = v50d6c6;
 assign w1 = vd6b984;
 assign w2 = v02d898;
 assign vf24dba = w3;
 v359a55_ve4e0df ve4e0df (
  .sel(w0),
  .i0(w1),
  .i1(w2),
  .o(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux 2 a 1 de 8 bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 2 a 1 de 8 bits
/*-------------------------------------------------*/

module v359a55_ve4e0df (
 input [7:0] i1,
 input [7:0] i0,
 input sel,
 output [7:0] o
);
 //-- Multiplexor de 2 a 1, 
 //-- de 8 bits
 
 reg [7:0] o;
 
 always @(*) begin
     case(sel)
         0: o = i0;
         1: o = i1;
         default: o = i0;
     endcase
 end
 
 
endmodule
//---- Top entity
module v7d7474 #(
 parameter v8d305c = 1
) (
 input [7:0] ve41da3,
 output [7:0] v9c083a
);
 localparam p0 = v8d305c;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w1 = ve41da3;
 assign v9c083a = w2;
 v7d7474_va0c26a #(
  .k(p0)
 ) va0c26a (
  .a(w1),
  .s(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- sum-1op-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sumador de un operando de 8 bits con una constante pasada como parámetro (No hay accarreo)
/*-------------------------------------------------*/

module v7d7474_va0c26a #(
 parameter k = 0
) (
 input [7:0] a,
 output [7:0] s
);
 assign s = a + k;
endmodule
//---- Top entity
module v725b7e (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v725b7e_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 1
/*-------------------------------------------------*/

module v725b7e_vb2eccd (
 output q
);
 //-- Bit constante a 1
 assign q = 1'b1;
 
 
endmodule
//---- Top entity
module vb6ddba (
 input [7:0] v7a6a68,
 input [7:0] v32ad8d,
 input [7:0] v63d71a,
 input [7:0] v9999de,
 output [31:0] v2eef2f
);
 wire [0:31] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 assign v2eef2f = w0;
 assign w1 = v9999de;
 assign w2 = v63d71a;
 assign w3 = v32ad8d;
 assign w4 = v7a6a68;
 vb6ddba_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2),
  .i2(w3),
  .i3(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 4 buses en un bus de 32-bits
/*-------------------------------------------------*/

module vb6ddba_v9a2a06 (
 input [7:0] i3,
 input [7:0] i2,
 input [7:0] i1,
 input [7:0] i0,
 output [31:0] o
);
 assign o = {i3,i2, i1, i0};
 
endmodule
//---- Top entity
module v96f098 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v96f098_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOT  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- NOT logic gate
/*-------------------------------------------------*/

module v96f098_vd54ca1 (
 input a,
 output c
);
 // NOT logic gate
 
 assign c = ~ a;
endmodule
