// Code generated by Icestudio 0.7.0

`default_nettype none

//---- Top entity
module main #(
 parameter v4d604b = 3,
 parameter v43db9e = 15,
 parameter v27a8d5 = "v27a8d5.list",
 parameter v55e5ec = 132,
 parameter vdc9752 = 0
) (
 input v4a48f8,
 input vclk,
 output [7:0] vc9977b
);
 localparam p0 = v43db9e;
 localparam p1 = v4d604b;
 localparam p9 = v27a8d5;
 localparam p13 = v55e5ec;
 localparam p14 = vdc9752;
 wire w2;
 wire w3;
 wire [0:7] w4;
 wire [0:1] w5;
 wire w6;
 wire w7;
 wire [0:7] w8;
 wire w10;
 wire w11;
 wire w12;
 wire [0:7] w15;
 wire [0:7] w16;
 wire [0:7] w17;
 wire [0:7] w18;
 wire [0:7] w19;
 wire [0:7] w20;
 wire [0:7] w21;
 wire [0:7] w22;
 wire [0:7] w23;
 wire [0:7] w24;
 wire [0:7] w25;
 wire [0:7] w26;
 wire [0:7] w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 assign w10 = v4a48f8;
 assign vc9977b = w27;
 assign w28 = vclk;
 assign w29 = vclk;
 assign w21 = w8;
 assign w27 = w16;
 assign w29 = w28;
 assign w31 = w30;
 assign w32 = w30;
 assign w32 = w31;
 v5ad97e #(
  .vc5c8ea(p0)
 ) v093dff (
 
 );
 v5ad97e #(
  .vc5c8ea(p1)
 ) v17dbc5 (
 
 );
 v05e8eb v45c5c8 (
  .v23dc54(w6),
  .va136b0(w7),
  .v922e3d(w32)
 );
 v05e8eb #(
  .v5a4ee6(p9)
 ) vcf223b (
  .v23dc54(w2),
  .va136b0(w3),
  .vcc2c4f(w4),
  .v157610(w8),
  .vba32a6(w24),
  .v922e3d(w31)
 );
 v21cfcc v2579ea (
  .v9fb85f(w2)
 );
 v725b7e v5d9e3c (
  .v9fb85f(w3)
 );
 v3bf99b vb80b32 (
  .vb096dc(w4)
 );
 v7404e6 v0ef5e7 (
  .vd7d1f4(w5)
 );
 vfc9dac v3c0180 (
  .v8b19dd(w5),
  .v3f8943(w6),
  .v64d863(w7)
 );
 vd553c7 vd65c2d (
  .vfeda54(w8),
  .v78b22f(w12),
  .v66a578(w16),
  .va4d6fb(w17),
  .vba6d41(w18),
  .v78372c(w19),
  .v95e7d9(w20),
  .vbab6c8(w22),
  .vccf36f(w23),
  .vbfdb97(w25),
  .vc2ef4f(w26)
 );
 vcfd9ba vbc7573 (
  .v6a82dd(w10),
  .vd4e5d7(w11),
  .v444878(w28)
 );
 v1b3913 v33f77a (
  .ve78ab8(w11),
  .ved8395(w29),
  .v3487af(w30)
 );
 v35f267 v0d6f16 (
  .vcbab45(w12),
  .v0e28cb(w30)
 );
 v5ad97e #(
  .vc5c8ea(p13)
 ) ve0f922 (
  .v26dbdb(w15)
 );
 v5ad97e #(
  .vc5c8ea(p14)
 ) v6bdada (
 
 );
 v0bd3c1 v7ff1f3 (
  .vfc5572(w15)
 );
 v0bd3c1 vb50c19 (
  .vc75b49(w16),
  .ve0ce24(w17),
  .v3610ac(w18),
  .v55960f(w19),
  .v72c72a(w20),
  .v49e9c8(w21),
  .v8a86c8(w22),
  .v604fda(w23),
  .vfc5572(w24),
  .ve6d7e4(w25),
  .vfd9d0f(w26)
 );
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v5ad97e #(
 parameter vc5c8ea = 0
) (
 output [7:0] v26dbdb
);
 localparam p0 = vc5c8ea;
 wire [0:7] w1;
 assign v26dbdb = w1;
 v5ad97e_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Constante-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor genérico constante, de 8 bits. Su valor se introduce como parámetro. Por defecto vale 0
/*-------------------------------------------------*/

module v5ad97e_v465065 #(
 parameter VALUE = 0
) (
 output [7:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module v05e8eb #(
 parameter v5a4ee6 = "v5a4ee6.list"
) (
 input v922e3d,
 input [7:0] v157610,
 input [7:0] vcc2c4f,
 input v23dc54,
 input va136b0,
 output [7:0] vba32a6
);
 localparam p5 = v5a4ee6;
 wire [0:7] w0;
 wire [0:7] w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:7] w6;
 assign vba32a6 = w0;
 assign w1 = vcc2c4f;
 assign w2 = v922e3d;
 assign w3 = va136b0;
 assign w4 = v23dc54;
 assign w6 = v157610;
 v05e8eb_vbaa912 #(
  .ROMF(p5)
 ) vbaa912 (
  .data_out(w0),
  .data_in(w1),
  .clk(w2),
  .cs(w3),
  .wr(w4),
  .addr(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- Memory-256B  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 256 bytes memory
/*-------------------------------------------------*/

module v05e8eb_vbaa912 #(
 parameter ROMF = 0
) (
 input clk,
 input [7:0] addr,
 input [7:0] data_in,
 input wr,
 input cs,
 output [7:0] data_out
);
 //-- Anchura del bus de direcciones
 localparam ADDR_WIDTH = 8;
 
 //-- Tamano de la memoria
 localparam TAM = 1 << ADDR_WIDTH;
 
 //-- NO inicializar!
 //-- Si se inicializa a 0 o cualquier otro
 //-- valor no se infiere una RAM
 reg data_out;
 
 //-- Array para la memoria
 reg [7:0] mem_8 [0:TAM-1];
 
 //-- Puerto de lectura
 //-- Para que se infiera una RAM
 //-- debe ser una lectura sincrona
 always @(posedge clk)
 begin
     //-- Puerto de lectura
     if (cs & !wr) data_out <= mem_8[addr];
     
     //-- Puerto de escritura
     if (cs & wr) mem_8[addr] <= data_in;
 end
 
 
 //-- Inicializacion de la memoria
 initial begin
   
   if (ROMF)
     $readmemh(ROMF, mem_8, 0, TAM-1);
   
 end
 
 
 
 
endmodule
//---- Top entity
module v21cfcc (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v21cfcc_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 0  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 0
/*-------------------------------------------------*/

module v21cfcc_vb2eccd (
 output q
);
 //-- Bit constante a 0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module v725b7e (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v725b7e_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 1
/*-------------------------------------------------*/

module v725b7e_vb2eccd (
 output q
);
 //-- Bit constante a 1
 assign q = 1'b1;
 
 
endmodule
//---- Top entity
module v3bf99b #(
 parameter vfffc23 = 0
) (
 output [7:0] vb096dc
);
 localparam p0 = vfffc23;
 wire [0:7] w1;
 assign vb096dc = w1;
 v5ad97e #(
  .vc5c8ea(p0)
 ) v68b2cc (
  .v26dbdb(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_0_8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 0 para bus de 8 bits
/*-------------------------------------------------*/
//---- Top entity
module v7404e6 (
 input [7:0] v595263,
 output [1:0] vd7d1f4,
 output [5:0] v4ce39b
);
 wire [0:7] w0;
 wire [0:1] w1;
 wire [0:5] w2;
 assign w0 = v595263;
 assign vd7d1f4 = w1;
 assign v4ce39b = w2;
 v7404e6_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus-2-6  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 8-bits en 2 buses de 2 y 6 bits
/*-------------------------------------------------*/

module v7404e6_v9a2a06 (
 input [7:0] i,
 output [1:0] o1,
 output [5:0] o0
);
 assign o1 = i[7:6];
 assign o0 = i[5:0];
endmodule
//---- Top entity
module vfc9dac (
 input [1:0] v8b19dd,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign w2 = v8b19dd;
 vfc9dac_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 2-bits en dos cables
/*-------------------------------------------------*/

module vfc9dac_v9a2a06 (
 input [1:0] i,
 output o1,
 output o0
);
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module vd553c7 (
 input [7:0] vbfdb97,
 input [7:0] vc2ef4f,
 input v78b22f,
 output [7:0] v66a578,
 output [7:0] va4d6fb,
 output [7:0] vba6d41,
 output [7:0] v78372c,
 output [7:0] v95e7d9,
 output [7:0] vfeda54,
 output [7:0] vbab6c8,
 output [7:0] vccf36f
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:7] w5;
 wire [0:7] w6;
 wire [0:7] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire [0:5] w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire [0:3] w24;
 wire [0:3] w25;
 wire [0:1] w26;
 wire [0:1] w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 wire [0:3] w34;
 wire [0:3] w35;
 wire [0:7] w36;
 wire [0:7] w37;
 wire [0:7] w38;
 wire w39;
 wire w40;
 wire [0:7] w41;
 wire [0:7] w42;
 wire [0:7] w43;
 wire [0:7] w44;
 wire [0:7] w45;
 wire [0:7] w46;
 wire [0:7] w47;
 wire [0:7] w48;
 wire [0:7] w49;
 assign v95e7d9 = w0;
 assign vfeda54 = w1;
 assign vbab6c8 = w2;
 assign vccf36f = w3;
 assign va4d6fb = w4;
 assign vba6d41 = w5;
 assign v78372c = w6;
 assign v66a578 = w7;
 assign w11 = v78b22f;
 assign w12 = v78b22f;
 assign w13 = v78b22f;
 assign w14 = v78b22f;
 assign w15 = v78b22f;
 assign w16 = v78b22f;
 assign w17 = v78b22f;
 assign w18 = v78b22f;
 assign w36 = vc2ef4f;
 assign w42 = vbfdb97;
 assign w43 = vbfdb97;
 assign w44 = vbfdb97;
 assign w45 = vbfdb97;
 assign w46 = vbfdb97;
 assign w47 = vbfdb97;
 assign w48 = vbfdb97;
 assign w49 = vbfdb97;
 assign w12 = w11;
 assign w13 = w11;
 assign w13 = w12;
 assign w14 = w11;
 assign w14 = w12;
 assign w14 = w13;
 assign w15 = w11;
 assign w15 = w12;
 assign w15 = w13;
 assign w15 = w14;
 assign w16 = w11;
 assign w16 = w12;
 assign w16 = w13;
 assign w16 = w14;
 assign w16 = w15;
 assign w17 = w11;
 assign w17 = w12;
 assign w17 = w13;
 assign w17 = w14;
 assign w17 = w15;
 assign w17 = w16;
 assign w18 = w11;
 assign w18 = w12;
 assign w18 = w13;
 assign w18 = w14;
 assign w18 = w15;
 assign w18 = w16;
 assign w18 = w17;
 assign w38 = w1;
 assign w43 = w42;
 assign w44 = w42;
 assign w44 = w43;
 assign w45 = w42;
 assign w45 = w43;
 assign w45 = w44;
 assign w46 = w42;
 assign w46 = w43;
 assign w46 = w44;
 assign w46 = w45;
 assign w47 = w42;
 assign w47 = w43;
 assign w47 = w44;
 assign w47 = w45;
 assign w47 = w46;
 assign w48 = w42;
 assign w48 = w43;
 assign w48 = w44;
 assign w48 = w45;
 assign w48 = w46;
 assign w48 = w47;
 assign w49 = w42;
 assign w49 = w43;
 assign w49 = w44;
 assign w49 = w45;
 assign w49 = w46;
 assign w49 = w47;
 assign w49 = w48;
 v89d234 v00cf70 (
  .vb1c024(w7),
  .v41eb95(w11),
  .vf892a0(w30),
  .v39f831(w42)
 );
 v89d234 v52e8e8 (
  .vb1c024(w4),
  .v41eb95(w12),
  .vf892a0(w31),
  .v39f831(w43)
 );
 v89d234 v3a923a (
  .vb1c024(w5),
  .v41eb95(w13),
  .vf892a0(w32),
  .v39f831(w44)
 );
 v89d234 v5a42b0 (
  .vb1c024(w6),
  .v41eb95(w14),
  .vf892a0(w33),
  .v39f831(w45)
 );
 v89d234 vc3d5eb (
  .vb1c024(w0),
  .vf892a0(w8),
  .v41eb95(w15),
  .v39f831(w46)
 );
 v89d234 v3b4bcb (
  .vb1c024(w1),
  .v41eb95(w16),
  .vf892a0(w39),
  .v39f831(w41)
 );
 v89d234 vdb2ed9 (
  .vb1c024(w2),
  .vf892a0(w9),
  .v41eb95(w17),
  .v39f831(w48)
 );
 v89d234 ve77b64 (
  .vb1c024(w3),
  .vf892a0(w10),
  .v41eb95(w18),
  .v39f831(w49)
 );
 v45c913 v46cbae (
  .v593f43(w8),
  .vc90115(w9),
  .v5b73e8(w10),
  .v930b03(w35),
  .v2812a7(w40)
 );
 v7404e6 v9184a8 (
  .v4ce39b(w19),
  .v595263(w36)
 );
 vd4bd04 v776aa2 (
  .v03aaf0(w20),
  .vee8a83(w21),
  .v67a3fc(w27)
 );
 vd4bd04 v474d28 (
  .v03aaf0(w22),
  .vee8a83(w23),
  .v67a3fc(w26)
 );
 vfd8998 v289c22 (
  .vbb390a(w19),
  .v45ab8c(w20),
  .vb85197(w21),
  .v8f149e(w22),
  .v7c37b3(w23),
  .ve0c1b4(w28),
  .v2c9812(w29)
 );
 v1c4cc4 va801cf (
  .v9c304b(w25),
  .v827425(w26)
 );
 v13d09a ve0ffcc (
  .vd317b3(w25),
  .v76af38(w29),
  .ve2642f(w35)
 );
 v1c4cc4 va6e1f2 (
  .v9c304b(w24),
  .v827425(w27)
 );
 v13d09a v81f649 (
  .vd317b3(w24),
  .v76af38(w28),
  .ve2642f(w34)
 );
 v45c913 v3f14be (
  .v593f43(w30),
  .v2812a7(w31),
  .vc90115(w32),
  .v5b73e8(w33),
  .v930b03(w34)
 );
 v359a55 ve3d83e (
  .vd6b984(w37),
  .v50d6c6(w40),
  .vf24dba(w41),
  .v02d898(w47)
 );
 v7d7474 v973e98 (
  .v9c083a(w37),
  .ve41da3(w38)
 );
 v725b7e v1dca89 (
  .v9fb85f(w39)
 );
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v89d234 #(
 parameter v422d28 = 0
) (
 input v41eb95,
 input [7:0] v39f831,
 input vf892a0,
 output [7:0] vb1c024
);
 localparam p0 = v422d28;
 wire [0:7] w1;
 wire [0:7] w2;
 wire w3;
 wire w4;
 assign vb1c024 = w1;
 assign w2 = v39f831;
 assign w3 = vf892a0;
 assign w4 = v41eb95;
 v89d234_v9148cb #(
  .INI(p0)
 ) v9148cb (
  .q(w1),
  .d(w2),
  .load(w3),
  .clk(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Registro  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Registro de 8 bits
/*-------------------------------------------------*/

module v89d234_v9148cb #(
 parameter INI = 0
) (
 input clk,
 input [7:0] d,
 input load,
 output [7:0] q
);
 localparam N = 8;
 
 reg [N-1:0] q = INI;
 
 always @(posedge clk)
   if (load)
     q <= d;
endmodule
//---- Top entity
module v45c913 (
 input [3:0] v930b03,
 output v5b73e8,
 output vc90115,
 output v2812a7,
 output v593f43
);
 wire [0:3] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v930b03;
 assign v2812a7 = w1;
 assign v593f43 = w2;
 assign vc90115 = w3;
 assign v5b73e8 = w4;
 v45c913_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2),
  .o2(w3),
  .o3(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 4-bits en 4 cables
/*-------------------------------------------------*/

module v45c913_v9a2a06 (
 input [3:0] i,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module vd4bd04 (
 input vee8a83,
 input v03aaf0,
 output [1:0] v67a3fc
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign v67a3fc = w2;
 vd4bd04_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 2 cables en un bus de 2-bits
/*-------------------------------------------------*/

module vd4bd04_v9a2a06 (
 input i1,
 input i0,
 output [1:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vfd8998 (
 input [5:0] vbb390a,
 output v2c9812,
 output ve0c1b4,
 output v7c37b3,
 output v8f149e,
 output vb85197,
 output v45ab8c
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:5] w6;
 assign v2c9812 = w0;
 assign ve0c1b4 = w1;
 assign v7c37b3 = w2;
 assign v8f149e = w3;
 assign vb85197 = w4;
 assign v45ab8c = w5;
 assign w6 = vbb390a;
 vfd8998_v9a2a06 v9a2a06 (
  .o5(w0),
  .o4(w1),
  .o3(w2),
  .o2(w3),
  .o1(w4),
  .o0(w5),
  .i(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 6-bits en 6 cables
/*-------------------------------------------------*/

module vfd8998_v9a2a06 (
 input [5:0] i,
 output o5,
 output o4,
 output o3,
 output o2,
 output o1,
 output o0
);
 
 
 assign o5 = i[5];
 assign o4 = i[4];
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v1c4cc4 (
 input [1:0] v827425,
 output [3:0] v9c304b
);
 wire [0:1] w0;
 wire [0:3] w1;
 assign w0 = v827425;
 assign v9c304b = w1;
 v1c4cc4_v3d7f3a v3d7f3a (
  .y(w0),
  .i(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Decodificador-2-4-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Decodificador de 2 a 4, con salida en bus
/*-------------------------------------------------*/

module v1c4cc4_v3d7f3a (
 input [1:0] y,
 output [3:0] i
);
 assign i = 1 << y;
                        
 
endmodule
//---- Top entity
module v13d09a (
 input [3:0] vd317b3,
 input v76af38,
 output [3:0] ve2642f
);
 wire w0;
 wire [0:3] w1;
 wire [0:3] w2;
 assign w0 = v76af38;
 assign w1 = vd317b3;
 assign ve2642f = w2;
 v13d09a_vce9fab vce9fab (
  .b(w0),
  .a(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND-4-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta AND de dos operandos, de 1 y 4 bits
/*-------------------------------------------------*/

module v13d09a_vce9fab (
 input [3:0] a,
 input b,
 output [3:0] o
);
 assign o[3] = a[3] & b;
 assign o[2] = a[2] & b;
 assign o[1] = a[1] & b;
 assign o[0] = a[0] & b;
endmodule
//---- Top entity
module v359a55 (
 input [7:0] v02d898,
 input [7:0] vd6b984,
 input v50d6c6,
 output [7:0] vf24dba
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 assign w0 = v50d6c6;
 assign w1 = vd6b984;
 assign w2 = v02d898;
 assign vf24dba = w3;
 v359a55_ve4e0df ve4e0df (
  .sel(w0),
  .i0(w1),
  .i1(w2),
  .o(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux 2 a 1 de 8 bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 2 a 1 de 8 bits
/*-------------------------------------------------*/

module v359a55_ve4e0df (
 input [7:0] i1,
 input [7:0] i0,
 input sel,
 output [7:0] o
);
 //-- Multiplexor de 2 a 1, 
 //-- de 8 bits
 
 reg [7:0] o;
 
 always @(*) begin
     case(sel)
         0: o = i0;
         1: o = i1;
         default: o = i0;
     endcase
 end
 
 
endmodule
//---- Top entity
module v7d7474 #(
 parameter v8d305c = 1
) (
 input [7:0] ve41da3,
 output [7:0] v9c083a
);
 localparam p0 = v8d305c;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w1 = ve41da3;
 assign v9c083a = w2;
 v7d7474_va0c26a #(
  .k(p0)
 ) va0c26a (
  .a(w1),
  .s(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- sum-1op-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sumador de un operando de 8 bits con una constante pasada como parámetro (No hay accarreo)
/*-------------------------------------------------*/

module v7d7474_va0c26a #(
 parameter k = 0
) (
 input [7:0] a,
 output [7:0] s
);
 assign s = a + k;
endmodule
//---- Top entity
module vcfd9ba (
 input v444878,
 input v6a82dd,
 output vd4e5d7
);
 wire w0;
 wire w1;
 wire w2;
 assign vd4e5d7 = w0;
 assign w1 = v444878;
 assign w2 = v6a82dd;
 vcfd9ba_va7041c va7041c (
  .out(w0),
  .clk(w1),
  .in(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Debouncer  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Remove the rebound on a mechanical switch
/*-------------------------------------------------*/

module vcfd9ba_va7041c (
 input clk,
 input in,
 output out
);
 //-- Debouncer Circuit
 //-- It produces a stable output when the
 //-- input signal is bouncing
 
 reg btn_prev = 0;
 reg btn_out_r = 0;
 
 reg [16:0] counter = 0;
 
 
 always @(posedge clk) begin
 
   //-- If btn_prev and btn_in are differents
   if (btn_prev ^ in == 1'b1) begin
     
       //-- Reset the counter
       counter <= 0;
       
       //-- Capture the button status
       btn_prev <= in;
   end
     
   //-- If no timeout, increase the counter
   else if (counter[16] == 1'b0)
       counter <= counter + 1;
       
   else
     //-- Set the output to the stable value
     btn_out_r <= btn_prev;
 
 end
 
 assign out = btn_out_r;
 
endmodule
//---- Top entity
module v1b3913 (
 input ved8395,
 input ve78ab8,
 output v3487af
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 assign w0 = ve78ab8;
 assign w1 = ved8395;
 assign w4 = ve78ab8;
 assign v3487af = w5;
 assign w4 = w0;
 v1c7dae vbf8366 (
  .vf54559(w0),
  .va4102a(w1),
  .ve8318d(w2)
 );
 v35f267 v5053a8 (
  .v0e28cb(w2),
  .vcbab45(w3)
 );
 vb2090f v758f4d (
  .v0e28cb(w3),
  .v3ca442(w4),
  .vcbab45(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- Subida  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Detector de flanco de subida. Emite un tic cuando detecta un flanco de subida. Versión bloques
/*-------------------------------------------------*/
//---- Top entity
module v1c7dae #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v1c7dae_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Biestable-D  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Biestable de datos (Tipo D). Cuando se recibe un tic por load se captura el dato
/*-------------------------------------------------*/

module v1c7dae_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 reg q = INI;
 always @(posedge clk)
   q <= d;
endmodule
//---- Top entity
module v35f267 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v35f267_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOT  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta NOT
/*-------------------------------------------------*/

module v35f267_vd54ca1 (
 input a,
 output c
);
 //-- Puerta NOT
 
 //-- module (input wire a, output wire c);
 
 
 assign c = ~a;
 
 
 //-- endmodule
 
endmodule
//---- Top entity
module vb2090f (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vb2090f_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta AND
/*-------------------------------------------------*/

module vb2090f_vf4938a (
 input a,
 input b,
 output c
);
 //-- Puerta AND
 
 //-- module and (input wire a, input wire b,
 //--             output wire c);
 
 assign c = a & b;
 
 //-- endmodule
endmodule
//---- Top entity
module v0bd3c1 #(
 parameter v7dcc91 = 44,
 parameter vc7e15e = 16,
 parameter vcb8c66 = 16,
 parameter v9ba8e8 = 0,
 parameter v76b36f = 36,
 parameter vb4c034 = 32,
 parameter v4ecf88 = 80,
 parameter v70f00e = 192,
 parameter v824f7d = 16
) (
 input [7:0] vc75b49,
 input [7:0] ve0ce24,
 input [7:0] v3610ac,
 input [7:0] v55960f,
 input [7:0] v72c72a,
 input [7:0] v49e9c8,
 input [7:0] v8a86c8,
 input [7:0] v604fda,
 input [7:0] vfc5572,
 input [7:0] v21ec4d,
 output [7:0] ve6d7e4,
 output [7:0] vfd9d0f,
 output [7:0] v7c37d9
);
 localparam p27 = vb4c034;
 localparam p28 = v4ecf88;
 localparam p29 = v70f00e;
 localparam p33 = v824f7d;
 localparam p42 = vcb8c66;
 localparam p47 = v7dcc91;
 localparam p48 = vc7e15e;
 localparam p51 = v76b36f;
 localparam p54 = v9ba8e8;
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:6] w3;
 wire [0:6] w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire [0:7] w11;
 wire [0:3] w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire [0:7] w21;
 wire [0:7] w22;
 wire [0:7] w23;
 wire [0:1] w24;
 wire [0:7] w25;
 wire [0:7] w26;
 wire [0:7] w30;
 wire [0:7] w31;
 wire [0:7] w32;
 wire [0:7] w34;
 wire [0:7] w35;
 wire [0:7] w36;
 wire [0:7] w37;
 wire [0:7] w38;
 wire [0:7] w39;
 wire [0:7] w40;
 wire [0:7] w41;
 wire [0:1] w43;
 wire [0:7] w44;
 wire [0:7] w45;
 wire w46;
 wire [0:7] w49;
 wire [0:7] w50;
 wire [0:7] w52;
 wire [0:7] w53;
 wire w55;
 wire [0:7] w56;
 wire [0:2] w57;
 wire [0:7] w58;
 wire [0:7] w59;
 wire [0:7] w60;
 wire [0:7] w61;
 wire [0:7] w62;
 wire [0:7] w63;
 wire [0:7] w64;
 wire [0:7] w65;
 wire [0:7] w66;
 wire [0:7] w67;
 wire [0:7] w68;
 wire [0:7] w69;
 wire [0:7] w70;
 wire [0:7] w71;
 wire [0:7] w72;
 wire [0:7] w73;
 wire [0:7] w74;
 wire [0:7] w75;
 wire [0:7] w76;
 wire [0:7] w77;
 wire [0:7] w78;
 wire [0:7] w79;
 wire [0:7] w80;
 wire [0:7] w81;
 wire [0:7] w82;
 wire [0:7] w83;
 wire [0:7] w84;
 wire [0:7] w85;
 wire [0:7] w86;
 wire [0:7] w87;
 wire [0:7] w88;
 wire [0:7] w89;
 wire [0:7] w90;
 wire [0:7] w91;
 wire [0:7] w92;
 wire [0:7] w93;
 wire [0:7] w94;
 wire [0:3] w95;
 wire [0:3] w96;
 wire [0:3] w97;
 wire [0:3] w98;
 wire [0:3] w99;
 wire [0:3] w100;
 wire [0:7] w101;
 wire [0:7] w102;
 wire [0:7] w103;
 assign w22 = vfc5572;
 assign ve6d7e4 = w23;
 assign vfd9d0f = w58;
 assign w59 = v3610ac;
 assign w60 = v3610ac;
 assign w61 = v3610ac;
 assign w62 = v3610ac;
 assign w63 = v3610ac;
 assign w64 = v3610ac;
 assign w65 = v3610ac;
 assign w66 = v3610ac;
 assign w67 = v21ec4d;
 assign w68 = ve0ce24;
 assign w69 = ve0ce24;
 assign w70 = ve0ce24;
 assign w71 = ve0ce24;
 assign w72 = ve0ce24;
 assign w73 = ve0ce24;
 assign v7c37d9 = w73;
 assign w74 = ve0ce24;
 assign w75 = ve0ce24;
 assign w76 = ve0ce24;
 assign w77 = ve0ce24;
 assign w78 = ve0ce24;
 assign w79 = ve0ce24;
 assign w80 = ve0ce24;
 assign w82 = vc75b49;
 assign w87 = v55960f;
 assign w90 = v72c72a;
 assign w92 = v8a86c8;
 assign w8 = w5;
 assign w9 = w5;
 assign w9 = w8;
 assign w10 = w6;
 assign w13 = w6;
 assign w13 = w10;
 assign w15 = w5;
 assign w15 = w8;
 assign w15 = w9;
 assign w17 = w7;
 assign w19 = w18;
 assign w20 = w18;
 assign w20 = w19;
 assign w25 = w21;
 assign w32 = w26;
 assign w35 = w34;
 assign w36 = w34;
 assign w36 = w35;
 assign w37 = w34;
 assign w37 = w35;
 assign w37 = w36;
 assign w38 = w34;
 assign w38 = w35;
 assign w38 = w36;
 assign w38 = w37;
 assign w39 = w34;
 assign w39 = w35;
 assign w39 = w36;
 assign w39 = w37;
 assign w39 = w38;
 assign w40 = w34;
 assign w40 = w35;
 assign w40 = w36;
 assign w40 = w37;
 assign w40 = w38;
 assign w40 = w39;
 assign w41 = w34;
 assign w41 = w35;
 assign w41 = w36;
 assign w41 = w37;
 assign w41 = w38;
 assign w41 = w39;
 assign w41 = w40;
 assign w60 = w59;
 assign w61 = w59;
 assign w61 = w60;
 assign w62 = w59;
 assign w62 = w60;
 assign w62 = w61;
 assign w63 = w59;
 assign w63 = w60;
 assign w63 = w61;
 assign w63 = w62;
 assign w64 = w59;
 assign w64 = w60;
 assign w64 = w61;
 assign w64 = w62;
 assign w64 = w63;
 assign w65 = w59;
 assign w65 = w60;
 assign w65 = w61;
 assign w65 = w62;
 assign w65 = w63;
 assign w65 = w64;
 assign w66 = w59;
 assign w66 = w60;
 assign w66 = w61;
 assign w66 = w62;
 assign w66 = w63;
 assign w66 = w64;
 assign w66 = w65;
 assign w69 = w68;
 assign w70 = w68;
 assign w70 = w69;
 assign w71 = w68;
 assign w71 = w69;
 assign w71 = w70;
 assign w72 = w68;
 assign w72 = w69;
 assign w72 = w70;
 assign w72 = w71;
 assign w73 = w68;
 assign w73 = w69;
 assign w73 = w70;
 assign w73 = w71;
 assign w73 = w72;
 assign w74 = w68;
 assign w74 = w69;
 assign w74 = w70;
 assign w74 = w71;
 assign w74 = w72;
 assign w74 = w73;
 assign w75 = w68;
 assign w75 = w69;
 assign w75 = w70;
 assign w75 = w71;
 assign w75 = w72;
 assign w75 = w73;
 assign w75 = w74;
 assign w76 = w68;
 assign w76 = w69;
 assign w76 = w70;
 assign w76 = w71;
 assign w76 = w72;
 assign w76 = w73;
 assign w76 = w74;
 assign w76 = w75;
 assign w77 = w68;
 assign w77 = w69;
 assign w77 = w70;
 assign w77 = w71;
 assign w77 = w72;
 assign w77 = w73;
 assign w77 = w74;
 assign w77 = w75;
 assign w77 = w76;
 assign w78 = w68;
 assign w78 = w69;
 assign w78 = w70;
 assign w78 = w71;
 assign w78 = w72;
 assign w78 = w73;
 assign w78 = w74;
 assign w78 = w75;
 assign w78 = w76;
 assign w78 = w77;
 assign w79 = w68;
 assign w79 = w69;
 assign w79 = w70;
 assign w79 = w71;
 assign w79 = w72;
 assign w79 = w73;
 assign w79 = w74;
 assign w79 = w75;
 assign w79 = w76;
 assign w79 = w77;
 assign w79 = w78;
 assign w80 = w68;
 assign w80 = w69;
 assign w80 = w70;
 assign w80 = w71;
 assign w80 = w72;
 assign w80 = w73;
 assign w80 = w74;
 assign w80 = w75;
 assign w80 = w76;
 assign w80 = w77;
 assign w80 = w78;
 assign w80 = w79;
 assign w96 = w95;
 assign w98 = w97;
 assign w99 = w97;
 assign w99 = w98;
 assign w100 = w97;
 assign w100 = w98;
 assign w100 = w99;
 v36136f v2c9959 (
  .v593755(w61),
  .v5be714(w70),
  .vd006e6(w94)
 );
 v323be2 v8bf8fe (
  .v3515d4(w0),
  .v9bea93(w60)
 );
 v7d7474 vb06c37 (
  .ve41da3(w0),
  .v9c083a(w1)
 );
 v36136f vf52c15 (
  .v593755(w1),
  .v5be714(w69),
  .vd006e6(w93)
 );
 v85651a vc31643 (
  .vc96239(w63),
  .vea7b5b(w74),
  .v274c22(w89)
 );
 v323be2 v760dc4 (
  .v9bea93(w2),
  .v3515d4(w88)
 );
 v85651a vd0cd61 (
  .v274c22(w2),
  .vc96239(w62),
  .vea7b5b(w72)
 );
 vaf6fc9 v7d8ceb (
  .vb61f66(w3),
  .va191ad(w85)
 );
 vc80943 v15df47 (
  .v1ec852(w3),
  .v595263(w76)
 );
 v6348d5 v2201b2 (
  .vcff9d0(w4),
  .v869a97(w86)
 );
 vc80943 va17d28 (
  .v1ec852(w4),
  .v595263(w75)
 );
 v27fd6d vb1a3a7 (
  .v18e78c(w6),
  .v9f69ad(w65),
  .v9892c7(w78)
 );
 va21ae0 v538e54 (
  .v18e78c(w5),
  .v40cb98(w64),
  .v4145bb(w77)
 );
 v24496a v75955a (
  .v0e28cb(w5),
  .v3ca442(w6),
  .vcbab45(w7)
 );
 v528969 v7d7539 (
  .v0e28cb(w7),
  .v3ca442(w8),
  .vcbab45(w16)
 );
 v528969 v7e0594 (
  .v0e28cb(w9),
  .v3ca442(w10),
  .vcbab45(w14)
 );
 v36136f v90000b (
  .v593755(w11),
  .v5be714(w71),
  .vd006e6(w91)
 );
 v917222 vd81517 (
  .va191ad(w11),
  .v285646(w12),
  .v766044(w97)
 );
 va0b8df ve9245a (
  .va50a91(w12)
 );
 v7263b9 v74e9a4 (
  .v737e15(w13),
  .vf0dd0a(w14),
  .v15c355(w15),
  .v1b2099(w16),
  .ve5ee9d(w17),
  .v7fcaae(w18),
  .v858373(w19),
  .v21d803(w20),
  .va191ad(w81)
 );
 v21cfcc v214df7 (
  .v9fb85f(w18)
 );
 v49d51e vd141a5 (
  .vbdd51f(w21),
  .v3fb88b(w23),
  .vb4ed69(w25),
  .vd48707(w59),
  .vb6bab2(w67),
  .v3f3f35(w68),
  .vcd2a33(w81),
  .v31c944(w83),
  .v06410a(w84),
  .v71c62f(w85),
  .va541fd(w86),
  .v9b8a50(w88),
  .v30db33(w89),
  .v21e136(w91),
  .v062092(w93),
  .v3d1227(w94),
  .ve81325(w95)
 );
 v3bf99b vb4fc85 (
  .vb096dc(w21)
 );
 v73403c v068e8c (
  .v595263(w22),
  .vf9119c(w95),
  .v85accc(w97)
 );
 v70125e vfcd93f (
  .ve57f84(w24),
  .v21e136(w66),
  .v062092(w79),
  .v3d1227(w82),
  .v3fb88b(w84),
  .vbdd51f(w87)
 );
 v18cbcb v5bc727 (
  .v735395(w24),
  .v0daf7d(w43),
  .v930b03(w98)
 );
 v49d51e v325b10 (
  .vcd2a33(w26),
  .vb6bab2(w30),
  .vd48707(w31),
  .vb4ed69(w32),
  .v3d1227(w34),
  .v062092(w35),
  .v21e136(w36),
  .vbdd51f(w37),
  .v30db33(w38),
  .v9b8a50(w39),
  .va541fd(w40),
  .v71c62f(w41),
  .v3fb88b(w58),
  .ve81325(w96),
  .v3f3f35(w101),
  .v31c944(w102),
  .v06410a(w103)
 );
 v5ad97e #(
  .vc5c8ea(p27)
 ) v04d8fd (
  .v26dbdb(w26)
 );
 v5ad97e #(
  .vc5c8ea(p28)
 ) v4cc0bc (
  .v26dbdb(w30)
 );
 v5ad97e #(
  .vc5c8ea(p29)
 ) vf72751 (
  .v26dbdb(w31)
 );
 v5ad97e #(
  .vc5c8ea(p33)
 ) v32e16a (
  .v26dbdb(w34)
 );
 v5ad97e #(
  .vc5c8ea(p42)
 ) v8898d4 (
  .v26dbdb(w45)
 );
 v9f8856 ve26ac1 (
  .v276bb9(w43),
  .va191ad(w44)
 );
 vd63ed5 v7cd2a6 (
  .vea7b5b(w44),
  .vc96239(w45),
  .v274c22(w103)
 );
 v147de6 v17015d (
  .v9ffacd(w46),
  .v930b03(w99)
 );
 v359a55 v44a780 (
  .v50d6c6(w46),
  .v02d898(w80),
  .vf24dba(w83),
  .vd6b984(w92)
 );
 v359a55 ve65d04 (
  .vd6b984(w49),
  .v02d898(w50),
  .vf24dba(w102)
 );
 v5ad97e #(
  .vc5c8ea(p47)
 ) v38cf94 (
  .v26dbdb(w50)
 );
 v5ad97e #(
  .vc5c8ea(p48)
 ) vca1782 (
  .v26dbdb(w49)
 );
 v5ad97e #(
  .vc5c8ea(p51)
 ) v2438f7 (
  .v26dbdb(w56)
 );
 v448035 v2610ac (
  .v84546f(w52),
  .v31c84d(w57)
 );
 v85651a vd41a3f (
  .vc96239(w52),
  .v274c22(w53),
  .vea7b5b(w90)
 );
 v10466b #(
  .v16d6b8(p54)
 ) vfb5f49 (
  .v633638(w53),
  .v18e78c(w55)
 );
 vdc50be v2ac06e (
  .v76af38(w55),
  .vea7b5b(w56),
  .v274c22(w101)
 );
 v30a3ea v00f83d (
  .vf96989(w57),
  .v930b03(w100)
 );
endmodule

/*-------------------------------------------------*/
/*-- alu1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v36136f (
 input [7:0] v5be714,
 input [7:0] v593755,
 output v654087,
 output [7:0] vd006e6
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 assign v654087 = w0;
 assign w1 = v593755;
 assign vd006e6 = w2;
 assign w3 = v5be714;
 v36136f_va0c26a va0c26a (
  .c(w0),
  .b(w1),
  .s(w2),
  .a(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- sum-2p-8bits-carry  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sumador  de 8 bits, con acarreo
/*-------------------------------------------------*/

module v36136f_va0c26a (
 input [7:0] a,
 input [7:0] b,
 output c,
 output [7:0] s
);
 wire [8:0] temp;
 assign temp = {1'b0, a} + {1'b0, b};
 assign s = temp[7:0];
 assign c = temp[8];
 //--test
endmodule
//---- Top entity
module v323be2 (
 input [7:0] v9bea93,
 output [7:0] v3515d4
);
 wire [0:7] w0;
 wire [0:7] w1;
 assign w0 = v9bea93;
 assign v3515d4 = w1;
 v323be2_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOT-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta NOT para bus de 8 bits
/*-------------------------------------------------*/

module v323be2_vd54ca1 (
 input [7:0] a,
 output [7:0] c
);
 //-- Puerta NOT
 
 //-- module (input wire a, output wire c);
 
 
 assign c = ~a;
 
 
 //-- endmodule
 
endmodule
//---- Top entity
module v85651a (
 input [7:0] vea7b5b,
 input [7:0] vc96239,
 output [7:0] v274c22
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w0 = vea7b5b;
 assign v274c22 = w1;
 assign w2 = vc96239;
 v85651a_vce9fab vce9fab (
  .a(w0),
  .o(w1),
  .b(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND-8  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- AND bit a bit entre dos buses de 8 bits
/*-------------------------------------------------*/

module v85651a_vce9fab (
 input [7:0] a,
 input [7:0] b,
 output [7:0] o
);
 assign o = a & b;
 
endmodule
//---- Top entity
module vaf6fc9 (
 input v4ef985,
 input [6:0] vb61f66,
 output [7:0] va191ad
);
 wire [0:6] w0;
 wire w1;
 wire [0:7] w2;
 assign w0 = vb61f66;
 assign w1 = v4ef985;
 assign va191ad = w2;
 vaf6fc9_v9a2a06 v9a2a06 (
  .i0(w0),
  .i1(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 1 cable y un bus de 7-bits a bus de 8-bits
/*-------------------------------------------------*/

module vaf6fc9_v9a2a06 (
 input i1,
 input [6:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vc80943 (
 input [7:0] v595263,
 output v57076f,
 output [6:0] v1ec852
);
 wire [0:7] w0;
 wire w1;
 wire [0:6] w2;
 assign w0 = v595263;
 assign v57076f = w1;
 assign v1ec852 = w2;
 vc80943_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus-1-7  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 8-bits en 2 buses de 1 y 7 bits
/*-------------------------------------------------*/

module vc80943_v9a2a06 (
 input [7:0] i,
 output o1,
 output [6:0] o0
);
 assign o1 = i[7];
 assign o0 = i[6:0];
endmodule
//---- Top entity
module v6348d5 (
 input [6:0] vcff9d0,
 input v428b2b,
 output [7:0] v869a97
);
 wire [0:6] w0;
 wire w1;
 wire [0:7] w2;
 assign w0 = vcff9d0;
 assign w1 = v428b2b;
 assign v869a97 = w2;
 v6348d5_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de un bus de 7 bits y un cable a bus de 8-bits
/*-------------------------------------------------*/

module v6348d5_v9a2a06 (
 input [6:0] i1,
 input i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v27fd6d (
 input [7:0] v9892c7,
 input [7:0] v9f69ad,
 output v18e78c
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign v18e78c = w0;
 assign w1 = v9f69ad;
 assign w2 = v9892c7;
 v27fd6d_vd75681 vd75681 (
  .eq(w0),
  .b(w1),
  .a(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Menor-que-2-op  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comparador menor que, de dos operandos de 8 bits
/*-------------------------------------------------*/

module v27fd6d_vd75681 (
 input [7:0] a,
 input [7:0] b,
 output eq
);
 assign eq = (a < b);
endmodule
//---- Top entity
module va21ae0 (
 input [7:0] v4145bb,
 input [7:0] v40cb98,
 output v18e78c
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign v18e78c = w0;
 assign w1 = v40cb98;
 assign w2 = v4145bb;
 va21ae0_vd75681 vd75681 (
  .eq(w0),
  .b(w1),
  .a(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Comparador de dos operandos  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comparador de dos operandos de 8 bits
/*-------------------------------------------------*/

module va21ae0_vd75681 (
 input [7:0] a,
 input [7:0] b,
 output eq
);
 assign eq = (a == b);
endmodule
//---- Top entity
module v24496a (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v24496a_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOR  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- NOR logic gate
/*-------------------------------------------------*/

module v24496a_vf4938a (
 input a,
 input b,
 output c
);
 // NOR logic gate
 
 assign c = ~(a | b);
endmodule
//---- Top entity
module v528969 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v528969_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- OR  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- OR logic gate
/*-------------------------------------------------*/

module v528969_vf4938a (
 input a,
 input b,
 output c
);
 // OR logic gate
 
 assign c = a | b;
endmodule
//---- Top entity
module v917222 (
 input [3:0] v285646,
 input [3:0] v766044,
 output [7:0] va191ad
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 assign w0 = v766044;
 assign w1 = v285646;
 assign va191ad = w2;
 v917222_v9a2a06 v9a2a06 (
  .i0(w0),
  .i1(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 2 buses de 4-bits a bus de 8-bits
/*-------------------------------------------------*/

module v917222_v9a2a06 (
 input [3:0] i1,
 input [3:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module va0b8df #(
 parameter vfffc23 = 0
) (
 output [3:0] va50a91
);
 localparam p0 = vfffc23;
 wire [0:3] w1;
 assign va50a91 = w1;
 v9274d3 #(
  .vc5c8ea(p0)
 ) v8800c6 (
  .v00a92d(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_0_4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 0 para bus de 4 bits
/*-------------------------------------------------*/
//---- Top entity
module v9274d3 #(
 parameter vc5c8ea = 0
) (
 output [3:0] v00a92d
);
 localparam p1 = vc5c8ea;
 wire [0:3] w0;
 assign v00a92d = w0;
 v9274d3_v465065 #(
  .VALUE(p1)
 ) v465065 (
  .k(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- Constante-4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor genérico constante, de 4 bits. Su valor se introduce como parámetro. Por defecto vale 0
/*-------------------------------------------------*/

module v9274d3_v465065 #(
 parameter VALUE = 0
) (
 output [3:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module v7263b9 (
 input v7fcaae,
 input v858373,
 input v21d803,
 input ve5ee9d,
 input v1b2099,
 input v15c355,
 input vf0dd0a,
 input v737e15,
 output [7:0] va191ad
);
 wire [0:7] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 assign va191ad = w0;
 assign w1 = v7fcaae;
 assign w2 = v858373;
 assign w3 = v21d803;
 assign w4 = ve5ee9d;
 assign w5 = v1b2099;
 assign w6 = v15c355;
 assign w7 = vf0dd0a;
 assign w8 = v737e15;
 v7263b9_v9a2a06 v9a2a06 (
  .o(w0),
  .i7(w1),
  .i6(w2),
  .i5(w3),
  .i4(w4),
  .i3(w5),
  .i2(w6),
  .i1(w7),
  .i0(w8)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 8 cables de 1-bit a bus de 8-bits
/*-------------------------------------------------*/

module v7263b9_v9a2a06 (
 input i7,
 input i6,
 input i5,
 input i4,
 input i3,
 input i2,
 input i1,
 input i0,
 output [7:0] o
);
 assign o = {i7, i6, i5, i4, i3, i2, i1, i0};
 
endmodule
//---- Top entity
module v49d51e (
 input [7:0] v732d31,
 input [7:0] vb4ed69,
 input [7:0] vd48707,
 input [7:0] vb6bab2,
 input [7:0] v3f3f35,
 input [7:0] vcd2a33,
 input [7:0] v31c944,
 input [7:0] v06410a,
 input [7:0] v71c62f,
 input [7:0] va541fd,
 input [7:0] v9b8a50,
 input [7:0] v30db33,
 input [7:0] vbdd51f,
 input [7:0] v21e136,
 input [7:0] v062092,
 input [7:0] v3d1227,
 input [3:0] ve81325,
 output [7:0] v3fb88b
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:7] w5;
 wire [0:7] w6;
 wire [0:7] w7;
 wire [0:7] w8;
 wire [0:7] w9;
 wire [0:7] w10;
 wire [0:7] w11;
 wire [0:7] w12;
 wire [0:7] w13;
 wire [0:7] w14;
 wire [0:7] w15;
 wire [0:7] w16;
 wire [0:3] w17;
 assign v3fb88b = w0;
 assign w1 = v062092;
 assign w2 = v3d1227;
 assign w3 = v21e136;
 assign w4 = vbdd51f;
 assign w5 = v30db33;
 assign w6 = v71c62f;
 assign w7 = va541fd;
 assign w8 = v9b8a50;
 assign w9 = v06410a;
 assign w10 = v31c944;
 assign w11 = vcd2a33;
 assign w12 = v3f3f35;
 assign w13 = vb6bab2;
 assign w14 = vd48707;
 assign w15 = vb4ed69;
 assign w16 = v732d31;
 assign w17 = ve81325;
 v49d51e_ve4e0df ve4e0df (
  .o(w0),
  .i1(w1),
  .i0(w2),
  .i2(w3),
  .i3(w4),
  .i4(w5),
  .i7(w6),
  .i6(w7),
  .i5(w8),
  .i8(w9),
  .i9(w10),
  .i10(w11),
  .i11(w12),
  .i12(w13),
  .i13(w14),
  .i14(w15),
  .i15(w16),
  .s(w17)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux-16-1- 8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 16 a 1 de 8 bits
/*-------------------------------------------------*/

module v49d51e_ve4e0df (
 input [7:0] i15,
 input [7:0] i14,
 input [7:0] i13,
 input [7:0] i12,
 input [7:0] i11,
 input [7:0] i10,
 input [7:0] i9,
 input [7:0] i8,
 input [7:0] i7,
 input [7:0] i6,
 input [7:0] i5,
 input [7:0] i4,
 input [7:0] i3,
 input [7:0] i2,
 input [7:0] i1,
 input [7:0] i0,
 input [3:0] s,
 output [7:0] o
);
 //-- Multiplexor de 16 a 1, 
 //-- de 8 bits
 
 assign o = (s == 4'h0) ? i0 :
            (s == 4'h1) ? i1 :
            (s == 4'h2) ? i2 : 
            (s == 4'h3) ? i3 :
            (s == 4'h4) ? i4 :
            (s == 4'h5) ? i5 :
            (s == 4'h6) ? i6 :
            (s == 4'h7) ? i7 :
            (s == 4'h8) ? i8 :
            (s == 4'h9) ? i9 :
            (s == 4'ha) ? i10 : 
            (s == 4'hb) ? i11 :
            (s == 4'hc) ? i12 :
            (s == 4'hd) ? i13 :
            (s == 4'he) ? i14 :
            (s == 4'hf) ? i15 :
            4'h0;
            
 
 
endmodule
//---- Top entity
module v73403c (
 input [7:0] v595263,
 output [3:0] vf9119c,
 output [3:0] v85accc
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 assign vf9119c = w0;
 assign v85accc = w1;
 assign w2 = v595263;
 v73403c_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 8-bits en buses de 4 bits
/*-------------------------------------------------*/

module v73403c_v9a2a06 (
 input [7:0] i,
 output [3:0] o1,
 output [3:0] o0
);
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module v70125e (
 input [7:0] vbdd51f,
 input [7:0] v21e136,
 input [7:0] v062092,
 input [7:0] v3d1227,
 input [1:0] ve57f84,
 output [7:0] v3fb88b
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:1] w5;
 assign v3fb88b = w0;
 assign w1 = v3d1227;
 assign w2 = v062092;
 assign w3 = v21e136;
 assign w4 = vbdd51f;
 assign w5 = ve57f84;
 v70125e_ve4e0df ve4e0df (
  .o(w0),
  .i0(w1),
  .i1(w2),
  .i2(w3),
  .i3(w4),
  .s(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- 8bits-Mux-4-1-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 4 a 1 de 8 bits
/*-------------------------------------------------*/

module v70125e_ve4e0df (
 input [7:0] i3,
 input [7:0] i2,
 input [7:0] i1,
 input [7:0] i0,
 input [1:0] s,
 output [7:0] o
);
 //-- Multiplexor de 4 a 1, 
 //-- de 8 bits
 
 assign o = (s == 2'b00) ? i0 :
            (s == 2'b01) ? i1 :
            (s == 2'b10) ? i2 : i3;
 
 
endmodule
//---- Top entity
module v18cbcb (
 input [3:0] v930b03,
 output [1:0] v0daf7d,
 output [1:0] v735395
);
 wire [0:1] w0;
 wire [0:1] w1;
 wire [0:3] w2;
 assign v0daf7d = w0;
 assign v735395 = w1;
 assign w2 = v930b03;
 v18cbcb_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 4-bits en buses de 2 bits
/*-------------------------------------------------*/

module v18cbcb_v9a2a06 (
 input [3:0] i,
 output [1:0] o1,
 output [1:0] o0
);
 assign o1 = i[3:2];
 assign o0 = i[1:0];
endmodule
//---- Top entity
module v9f8856 (
 input [5:0] v7c0b91,
 input [1:0] v276bb9,
 output [7:0] va191ad
);
 wire [0:7] w0;
 wire [0:1] w1;
 wire [0:5] w2;
 assign va191ad = w0;
 assign w1 = v276bb9;
 assign w2 = v7c0b91;
 v9f8856_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus-6-2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 2 buses de 6 y 2-bits a bus de 8-bits
/*-------------------------------------------------*/

module v9f8856_v9a2a06 (
 input [5:0] i1,
 input [1:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vd63ed5 (
 input [7:0] vea7b5b,
 input [7:0] vc96239,
 output [7:0] v274c22
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w0 = vea7b5b;
 assign v274c22 = w1;
 assign w2 = vc96239;
 vd63ed5_vce9fab vce9fab (
  .a(w0),
  .o(w1),
  .b(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- OR-8  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- OR bit a bit entre dos buses de 8 bits
/*-------------------------------------------------*/

module vd63ed5_vce9fab (
 input [7:0] a,
 input [7:0] b,
 output [7:0] o
);
 assign o = a | b;
 
endmodule
//---- Top entity
module v147de6 (
 input [3:0] v930b03,
 output [2:0] vf96989,
 output v9ffacd
);
 wire [0:3] w0;
 wire [0:2] w1;
 wire w2;
 assign w0 = v930b03;
 assign vf96989 = w1;
 assign v9ffacd = w2;
 v147de6_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 4-bits en bus de 3 bits y cable
/*-------------------------------------------------*/

module v147de6_v9a2a06 (
 input [3:0] i,
 output [2:0] o1,
 output o0
);
 assign o1 = i[3:1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v448035 (
 input [2:0] v31c84d,
 output [7:0] v84546f
);
 wire [0:2] w0;
 wire [0:7] w1;
 assign w0 = v31c84d;
 assign v84546f = w1;
 v448035_v3d7f3a v3d7f3a (
  .y(w0),
  .i(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Decodificador-3-8-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Decodificador de 3 a 8, con salida en bus
/*-------------------------------------------------*/

module v448035_v3d7f3a (
 input [2:0] y,
 output [7:0] i
);
 assign i = 1 << y;
                        
 
endmodule
//---- Top entity
module v10466b #(
 parameter v16d6b8 = 1
) (
 input [7:0] v633638,
 output v18e78c
);
 localparam p1 = v16d6b8;
 wire w0;
 wire [0:7] w2;
 assign v18e78c = w0;
 assign w2 = v633638;
 v10466b_vd75681 #(
  .B(p1)
 ) vd75681 (
  .eq(w0),
  .a(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mayor-que-1-op  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comparador mayor que, de un operando de 8 bits
/*-------------------------------------------------*/

module v10466b_vd75681 #(
 parameter B = 0
) (
 input [7:0] a,
 output eq
);
 assign eq = (a > B);
endmodule
//---- Top entity
module vdc50be (
 input [7:0] vea7b5b,
 input v76af38,
 output [7:0] v274c22
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w0 = v76af38;
 assign w1 = vea7b5b;
 assign v274c22 = w2;
 vdc50be_vce9fab vce9fab (
  .b(w0),
  .a(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND-8-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Habilitación de bus de 8 bits
/*-------------------------------------------------*/

module vdc50be_vce9fab (
 input [7:0] a,
 input b,
 output [7:0] o
);
 assign o[0] = a[0] & b;
 assign o[1] = a[1] & b;
 assign o[2] = a[2] & b;
 assign o[3] = a[3] & b;
 assign o[4] = a[4] & b;
 assign o[5] = a[5] & b;
 assign o[6] = a[6] & b;
 assign o[7] = a[7] & b;
endmodule
//---- Top entity
module v30a3ea (
 input [3:0] v930b03,
 output v9ffacd,
 output [2:0] vf96989
);
 wire [0:3] w0;
 wire [0:2] w1;
 wire w2;
 assign w0 = v930b03;
 assign vf96989 = w1;
 assign v9ffacd = w2;
 v30a3ea_v9a2a06 v9a2a06 (
  .i(w0),
  .o0(w1),
  .o1(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus-1-3  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 4-bits en buses de 1 bits y 3 bits
/*-------------------------------------------------*/

module v30a3ea_v9a2a06 (
 input [3:0] i,
 output o1,
 output [2:0] o0
);
 assign o1 = i[3];
 assign o0 = i[2:0];
endmodule
