// Code generated by Icestudio 0.7.0

`default_nettype none

//---- Top entity
module main #(
 parameter v27a8d5 = "v27a8d5.list",
 parameter v169d65 = 20
) (
 input v4a48f8,
 input vb61f9c,
 input vd71040,
 output [7:0] v29e050,
 output [7:0] v6a9212,
 output [7:0] v862b7e
);
 localparam p6 = v27a8d5;
 localparam p9 = v169d65;
 wire w0;
 wire w1;
 wire [0:7] w2;
 wire [0:1] w3;
 wire w4;
 wire w5;
 wire w7;
 wire w8;
 wire [0:7] w10;
 wire [0:7] w11;
 wire [0:7] w12;
 wire [0:7] w13;
 wire [0:7] w14;
 wire w15;
 wire [0:31] w16;
 wire [0:31] w17;
 wire [0:7] w18;
 wire [0:7] w19;
 wire [0:7] w20;
 wire [0:31] w21;
 wire w22;
 wire [0:7] w23;
 wire [0:7] w24;
 wire [0:7] w25;
 wire w26;
 wire w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 wire w34;
 wire w35;
 wire w36;
 wire w37;
 wire w38;
 assign w7 = v4a48f8;
 assign w8 = vb61f9c;
 assign w22 = vd71040;
 assign v862b7e = w23;
 assign v29e050 = w24;
 assign v6a9212 = w25;
 assign w26 = vd71040;
 assign w27 = vd71040;
 assign w19 = w14;
 assign w20 = w13;
 assign w21 = w16;
 assign w26 = w22;
 assign w27 = w22;
 assign w27 = w26;
 assign w29 = w28;
 assign w30 = w28;
 assign w30 = w29;
 assign w31 = w28;
 assign w31 = w29;
 assign w31 = w30;
 assign w32 = w28;
 assign w32 = w29;
 assign w32 = w30;
 assign w32 = w31;
 assign w33 = w28;
 assign w33 = w29;
 assign w33 = w30;
 assign w33 = w31;
 assign w33 = w32;
 assign w34 = w28;
 assign w34 = w29;
 assign w34 = w30;
 assign w34 = w31;
 assign w34 = w32;
 assign w34 = w33;
 assign w35 = w28;
 assign w35 = w29;
 assign w35 = w30;
 assign w35 = w31;
 assign w35 = w32;
 assign w35 = w33;
 assign w35 = w34;
 assign w36 = w28;
 assign w36 = w29;
 assign w36 = w30;
 assign w36 = w31;
 assign w36 = w32;
 assign w36 = w33;
 assign w36 = w34;
 assign w36 = w35;
 assign w37 = w28;
 assign w37 = w29;
 assign w37 = w30;
 assign w37 = w31;
 assign w37 = w32;
 assign w37 = w33;
 assign w37 = w34;
 assign w37 = w35;
 assign w37 = w36;
 assign w38 = w28;
 assign w38 = w29;
 assign w38 = w30;
 assign w38 = w31;
 assign w38 = w32;
 assign w38 = w33;
 assign w38 = w34;
 assign w38 = w35;
 assign w38 = w36;
 assign w38 = w37;
 v05e8eb v45c5c8 (
  .v23dc54(w4),
  .va136b0(w5),
  .vba32a6(w11),
  .v157610(w12),
  .vcc2c4f(w14),
  .v922e3d(w28)
 );
 v05e8eb #(
  .v5a4ee6(p6)
 ) vcf223b (
  .v23dc54(w0),
  .va136b0(w1),
  .vcc2c4f(w2),
  .vba32a6(w10),
  .v157610(w18),
  .v922e3d(w30)
 );
 v21cfcc v2579ea (
  .v9fb85f(w0)
 );
 v725b7e v5d9e3c (
  .v9fb85f(w1)
 );
 v3bf99b vb80b32 (
  .vb096dc(w2)
 );
 v7404e6 v0ef5e7 (
  .vd7d1f4(w3),
  .v595263(w13)
 );
 vfc9dac v3c0180 (
  .v8b19dd(w3),
  .v3f8943(w4),
  .v64d863(w5)
 );
 vcfd9ba vbc7573 (
  .v6a82dd(w7),
  .vd4e5d7(w15),
  .v444878(w26)
 );
 v6f058b v0591fa (
  .v2ebc76(w21),
  .vd65308(w23),
  .v6b375c(w24),
  .v0d81e4(w25)
 );
 v5cc6ec v4a3762 (
  .v50d6c6(w8),
  .v381ebf(w15),
  .vb186da(w22),
  .vc93bbe(w28)
 );
 v0e64bc #(
  .v207e0d(p9)
 ) v8e1000 (
  .v531e20(w27)
 );
 ve0c76e vaaffe8 (
  .vfc5572(w10),
  .v21ec4d(w11),
  .v7c37d9(w12),
  .vfd9d0f(w13),
  .ve6d7e4(w14),
  .v234fbd(w16),
  .v1bfd13(w17)
 );
 v7263b9 vdedaf5 (
  .ve5ee9d(w31),
  .v21d803(w32),
  .v1b2099(w33),
  .v15c355(w34),
  .vf0dd0a(w35),
  .v737e15(w36),
  .v858373(w37),
  .v7fcaae(w38)
 );
 v157cb8 vae9ccb (
  .v961ee9(w16),
  .vd115bb(w17),
  .v84ec18(w18),
  .vbfdb97(w19),
  .vc2ef4f(w20),
  .v78b22f(w29)
 );
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v05e8eb #(
 parameter v5a4ee6 = "v5a4ee6.list"
) (
 input v922e3d,
 input [7:0] v157610,
 input [7:0] vcc2c4f,
 input v23dc54,
 input va136b0,
 output [7:0] vba32a6
);
 localparam p5 = v5a4ee6;
 wire [0:7] w0;
 wire [0:7] w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:7] w6;
 assign vba32a6 = w0;
 assign w1 = vcc2c4f;
 assign w2 = v922e3d;
 assign w3 = va136b0;
 assign w4 = v23dc54;
 assign w6 = v157610;
 v05e8eb_vbaa912 #(
  .ROMF(p5)
 ) vbaa912 (
  .data_out(w0),
  .data_in(w1),
  .clk(w2),
  .cs(w3),
  .wr(w4),
  .addr(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- Memory-256B  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 256 bytes memory
/*-------------------------------------------------*/

module v05e8eb_vbaa912 #(
 parameter ROMF = 0
) (
 input clk,
 input [7:0] addr,
 input [7:0] data_in,
 input wr,
 input cs,
 output [7:0] data_out
);
 //-- Anchura del bus de direcciones
 localparam ADDR_WIDTH = 8;
 
 //-- Tamano de la memoria
 localparam TAM = 1 << ADDR_WIDTH;
 
 //-- NO inicializar!
 //-- Si se inicializa a 0 o cualquier otro
 //-- valor no se infiere una RAM
 reg data_out;
 
 //-- Array para la memoria
 reg [7:0] mem_8 [0:TAM-1];
 
 //-- Puerto de lectura
 //-- Para que se infiera una RAM
 //-- debe ser una lectura sincrona
 always @(posedge clk)
 begin
     //-- Puerto de lectura
     if (cs & !wr) data_out <= mem_8[addr];
     
     //-- Puerto de escritura
     if (cs & wr) mem_8[addr] <= data_in;
 end
 
 
 //-- Inicializacion de la memoria
 initial begin
   
   if (ROMF)
     $readmemh(ROMF, mem_8, 0, TAM-1);
   
 end
 
 
 
 
endmodule
//---- Top entity
module v21cfcc (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v21cfcc_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 0  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 0
/*-------------------------------------------------*/

module v21cfcc_vb2eccd (
 output q
);
 //-- Bit constante a 0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module v725b7e (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v725b7e_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 1
/*-------------------------------------------------*/

module v725b7e_vb2eccd (
 output q
);
 //-- Bit constante a 1
 assign q = 1'b1;
 
 
endmodule
//---- Top entity
module v3bf99b #(
 parameter vfffc23 = 0
) (
 output [7:0] vb096dc
);
 localparam p0 = vfffc23;
 wire [0:7] w1;
 assign vb096dc = w1;
 v5ad97e #(
  .vc5c8ea(p0)
 ) v68b2cc (
  .v26dbdb(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_0_8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 0 para bus de 8 bits
/*-------------------------------------------------*/
//---- Top entity
module v5ad97e #(
 parameter vc5c8ea = 0
) (
 output [7:0] v26dbdb
);
 localparam p0 = vc5c8ea;
 wire [0:7] w1;
 assign v26dbdb = w1;
 v5ad97e_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Constante-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor genérico constante, de 8 bits. Su valor se introduce como parámetro. Por defecto vale 0
/*-------------------------------------------------*/

module v5ad97e_v465065 #(
 parameter VALUE = 0
) (
 output [7:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module v7404e6 (
 input [7:0] v595263,
 output [1:0] vd7d1f4,
 output [5:0] v4ce39b
);
 wire [0:7] w0;
 wire [0:1] w1;
 wire [0:5] w2;
 assign w0 = v595263;
 assign vd7d1f4 = w1;
 assign v4ce39b = w2;
 v7404e6_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus-2-6  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 8-bits en 2 buses de 2 y 6 bits
/*-------------------------------------------------*/

module v7404e6_v9a2a06 (
 input [7:0] i,
 output [1:0] o1,
 output [5:0] o0
);
 assign o1 = i[7:6];
 assign o0 = i[5:0];
endmodule
//---- Top entity
module vfc9dac (
 input [1:0] v8b19dd,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign w2 = v8b19dd;
 vfc9dac_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 2-bits en dos cables
/*-------------------------------------------------*/

module vfc9dac_v9a2a06 (
 input [1:0] i,
 output o1,
 output o0
);
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module vcfd9ba (
 input v444878,
 input v6a82dd,
 output vd4e5d7
);
 wire w0;
 wire w1;
 wire w2;
 assign vd4e5d7 = w0;
 assign w1 = v444878;
 assign w2 = v6a82dd;
 vcfd9ba_va7041c va7041c (
  .out(w0),
  .clk(w1),
  .in(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Debouncer  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Remove the rebound on a mechanical switch
/*-------------------------------------------------*/

module vcfd9ba_va7041c (
 input clk,
 input in,
 output out
);
 //-- Debouncer Circuit
 //-- It produces a stable output when the
 //-- input signal is bouncing
 
 reg btn_prev = 0;
 reg btn_out_r = 0;
 
 reg [16:0] counter = 0;
 
 
 always @(posedge clk) begin
 
   //-- If btn_prev and btn_in are differents
   if (btn_prev ^ in == 1'b1) begin
     
       //-- Reset the counter
       counter <= 0;
       
       //-- Capture the button status
       btn_prev <= in;
   end
     
   //-- If no timeout, increase the counter
   else if (counter[16] == 1'b0)
       counter <= counter + 1;
       
   else
     //-- Set the output to the stable value
     btn_out_r <= btn_prev;
 
 end
 
 assign out = btn_out_r;
 
endmodule
//---- Top entity
module v6f058b (
 input [31:0] v2ebc76,
 output [7:0] v4a41db,
 output [7:0] v0d81e4,
 output [7:0] v6b375c,
 output [7:0] vd65308
);
 wire [0:31] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 assign w0 = v2ebc76;
 assign vd65308 = w1;
 assign v6b375c = w2;
 assign v0d81e4 = w3;
 assign v4a41db = w4;
 v6f058b_v9a2a06 v9a2a06 (
  .i(w0),
  .o0(w1),
  .o1(w2),
  .o2(w3),
  .o3(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 32-bits en 4 buses de 8 bits
/*-------------------------------------------------*/

module v6f058b_v9a2a06 (
 input [31:0] i,
 output [7:0] o3,
 output [7:0] o2,
 output [7:0] o1,
 output [7:0] o0
);
 assign o3 = i[31:24];
 assign o2 = i[23:16];
 assign o1 = i[15:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module v5cc6ec (
 input vb186da,
 input v381ebf,
 input v50d6c6,
 output vc93bbe
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w0 = v50d6c6;
 assign vc93bbe = w1;
 assign w2 = v381ebf;
 assign w3 = vb186da;
 v5cc6ec_ve4e0df ve4e0df (
  .sel(w0),
  .o(w1),
  .i0(w2),
  .i1(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux 2 a 1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 2 a 1
/*-------------------------------------------------*/

module v5cc6ec_ve4e0df (
 input i1,
 input i0,
 input sel,
 output o
);
 //-- Multiplexor de 2 a 1, 
 //-- de 8 bits
 
 reg _o;
 
 always @(*) begin
     case(sel)
         0: _o = i0;
         1: _o = i1;
         default: _o = i0;
     endcase
 end
 
 assign o = _o;
 
endmodule
//---- Top entity
module v0e64bc #(
 parameter v207e0d = 1
) (
 input v531e20,
 output v8337bc
);
 localparam p2 = v207e0d;
 wire w0;
 wire w1;
 assign v8337bc = w0;
 assign w1 = v531e20;
 v0e64bc_v94c6d7 #(
  .HZ(p2)
 ) v94c6d7 (
  .clk_o(w0),
  .clk(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Corazon_Hz  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Corazon genérico para bombear bits a la frecuencia fijada en Hz (por defecto 1Hz)
/*-------------------------------------------------*/

module v0e64bc_v94c6d7 #(
 parameter HZ = 0
) (
 input clk,
 output clk_o
);
 
 //parameter HZ=1;
 
 //-- Constante para dividir y obtener una frecuencia de 1Hz
 localparam M = 12000000/HZ;
 
 //-- Calcular el numero de bits para almacenar M
 localparam N = $clog2(M);
 
 //-- Registro del divisor
 reg [N-1:0] divcounter;
 
 //-- Temporal clock
 reg clk_t = 0;
 
 //-- Se usa un contador modulo M/2 para luego
 //-- pasarlo por un biestable T y dividir la frecuencia
 //-- entre 2, para que el ciclo de trabajo sea del 50%
 always @(posedge clk)
     if (divcounter == M/2) begin
       clk_t <= 1;
       divcounter = 0;
     end 
     else begin
       divcounter <=  divcounter + 1;
       clk_t = 0;
     end 
   
 reg clk_o = 0;  
     
 //-- Biestable T para obtener ciclo de trabajo del 50%
 always @(posedge clk)
   if (clk_t)
     clk_o <= ~clk_o;
 
endmodule
//---- Top entity
module ve0c76e #(
 parameter v7dcc91 = 44,
 parameter vc7e15e = 16,
 parameter vcb8c66 = 16,
 parameter v9ba8e8 = 0,
 parameter vb4c034 = 32,
 parameter v4ecf88 = 80,
 parameter v70f00e = 192,
 parameter v824f7d = 16,
 parameter v76b36f = 36
) (
 input [31:0] v234fbd,
 input [31:0] v1bfd13,
 input [7:0] vfc5572,
 input [7:0] v21ec4d,
 output [7:0] ve6d7e4,
 output [7:0] vfd9d0f,
 output [7:0] v7c37d9
);
 localparam p25 = vb4c034;
 localparam p26 = v4ecf88;
 localparam p27 = v70f00e;
 localparam p31 = v824f7d;
 localparam p39 = vcb8c66;
 localparam p43 = v7dcc91;
 localparam p44 = vc7e15e;
 localparam p47 = v76b36f;
 localparam p50 = v9ba8e8;
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:6] w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire [0:7] w10;
 wire [0:3] w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire [0:7] w20;
 wire [0:7] w21;
 wire [0:7] w22;
 wire [0:7] w23;
 wire [0:7] w24;
 wire [0:7] w28;
 wire [0:7] w29;
 wire [0:7] w30;
 wire [0:7] w32;
 wire [0:7] w33;
 wire [0:7] w34;
 wire [0:7] w35;
 wire [0:7] w36;
 wire [0:7] w37;
 wire [0:7] w38;
 wire [0:7] w40;
 wire [0:7] w41;
 wire w42;
 wire [0:7] w45;
 wire [0:7] w46;
 wire [0:7] w48;
 wire [0:7] w49;
 wire [0:7] w51;
 wire [0:2] w52;
 wire [0:7] w53;
 wire [0:31] w54;
 wire [0:31] w55;
 wire [0:1] w56;
 wire [0:1] w57;
 wire [0:5] w58;
 wire w59;
 wire [0:6] w60;
 wire w61;
 wire w62;
 wire w63;
 wire [0:7] w64;
 wire [0:7] w65;
 wire [0:7] w66;
 wire [0:7] w67;
 wire [0:7] w68;
 wire [0:7] w69;
 wire [0:7] w70;
 wire [0:7] w71;
 wire [0:7] w72;
 wire [0:7] w73;
 wire [0:7] w74;
 wire [0:7] w75;
 wire [0:7] w76;
 wire [0:7] w77;
 wire [0:7] w78;
 wire [0:7] w79;
 wire [0:7] w80;
 wire [0:7] w81;
 wire [0:7] w82;
 wire [0:7] w83;
 wire [0:7] w84;
 wire [0:7] w85;
 wire [0:7] w86;
 wire [0:7] w87;
 wire [0:7] w88;
 wire [0:7] w89;
 wire [0:7] w90;
 wire [0:7] w91;
 wire [0:7] w92;
 wire [0:7] w93;
 wire [0:7] w94;
 wire [0:7] w95;
 wire [0:7] w96;
 wire [0:7] w97;
 wire [0:7] w98;
 wire [0:7] w99;
 wire [0:3] w100;
 wire [0:3] w101;
 wire [0:3] w102;
 wire [0:3] w103;
 wire [0:3] w104;
 wire [0:3] w105;
 wire [0:7] w106;
 wire [0:7] w107;
 wire [0:7] w108;
 wire [0:7] w109;
 assign w21 = vfc5572;
 assign ve6d7e4 = w22;
 assign vfd9d0f = w53;
 assign w54 = v234fbd;
 assign w55 = v1bfd13;
 assign w72 = v21ec4d;
 assign v7c37d9 = w77;
 assign w7 = w4;
 assign w8 = w4;
 assign w8 = w7;
 assign w9 = w5;
 assign w12 = w5;
 assign w12 = w9;
 assign w14 = w4;
 assign w14 = w7;
 assign w14 = w8;
 assign w16 = w6;
 assign w18 = w17;
 assign w19 = w17;
 assign w19 = w18;
 assign w23 = w20;
 assign w30 = w24;
 assign w33 = w32;
 assign w34 = w32;
 assign w34 = w33;
 assign w35 = w32;
 assign w35 = w33;
 assign w35 = w34;
 assign w36 = w32;
 assign w36 = w33;
 assign w36 = w34;
 assign w36 = w35;
 assign w37 = w32;
 assign w37 = w33;
 assign w37 = w34;
 assign w37 = w35;
 assign w37 = w36;
 assign w38 = w32;
 assign w38 = w33;
 assign w38 = w34;
 assign w38 = w35;
 assign w38 = w36;
 assign w38 = w37;
 assign w65 = w64;
 assign w66 = w64;
 assign w66 = w65;
 assign w67 = w64;
 assign w67 = w65;
 assign w67 = w66;
 assign w68 = w64;
 assign w68 = w65;
 assign w68 = w66;
 assign w68 = w67;
 assign w69 = w64;
 assign w69 = w65;
 assign w69 = w66;
 assign w69 = w67;
 assign w69 = w68;
 assign w70 = w64;
 assign w70 = w65;
 assign w70 = w66;
 assign w70 = w67;
 assign w70 = w68;
 assign w70 = w69;
 assign w71 = w64;
 assign w71 = w65;
 assign w71 = w66;
 assign w71 = w67;
 assign w71 = w68;
 assign w71 = w69;
 assign w71 = w70;
 assign w74 = w73;
 assign w75 = w73;
 assign w75 = w74;
 assign w76 = w73;
 assign w76 = w74;
 assign w76 = w75;
 assign w77 = w73;
 assign w77 = w74;
 assign w77 = w75;
 assign w77 = w76;
 assign w78 = w73;
 assign w78 = w74;
 assign w78 = w75;
 assign w78 = w76;
 assign w78 = w77;
 assign w79 = w73;
 assign w79 = w74;
 assign w79 = w75;
 assign w79 = w76;
 assign w79 = w77;
 assign w79 = w78;
 assign w80 = w73;
 assign w80 = w74;
 assign w80 = w75;
 assign w80 = w76;
 assign w80 = w77;
 assign w80 = w78;
 assign w80 = w79;
 assign w81 = w73;
 assign w81 = w74;
 assign w81 = w75;
 assign w81 = w76;
 assign w81 = w77;
 assign w81 = w78;
 assign w81 = w79;
 assign w81 = w80;
 assign w82 = w73;
 assign w82 = w74;
 assign w82 = w75;
 assign w82 = w76;
 assign w82 = w77;
 assign w82 = w78;
 assign w82 = w79;
 assign w82 = w80;
 assign w82 = w81;
 assign w90 = w89;
 assign w91 = w89;
 assign w91 = w90;
 assign w92 = w89;
 assign w92 = w90;
 assign w92 = w91;
 assign w101 = w100;
 assign w103 = w102;
 assign w104 = w102;
 assign w104 = w103;
 assign w105 = w102;
 assign w105 = w103;
 assign w105 = w104;
 assign w109 = w108;
 v36136f v2c9959 (
  .v593755(w66),
  .v5be714(w75),
  .vd006e6(w99)
 );
 v323be2 v8bf8fe (
  .v3515d4(w0),
  .v9bea93(w65)
 );
 v7d7474 vb06c37 (
  .ve41da3(w0),
  .v9c083a(w1)
 );
 v36136f vf52c15 (
  .v593755(w1),
  .v5be714(w74),
  .vd006e6(w97)
 );
 v85651a vc31643 (
  .vc96239(w68),
  .vea7b5b(w78),
  .v274c22(w94)
 );
 v323be2 v760dc4 (
  .v9bea93(w2),
  .v3515d4(w93)
 );
 v85651a vd0cd61 (
  .v274c22(w2),
  .vc96239(w67),
  .vea7b5b(w76)
 );
 vaf6fc9 v7d8ceb (
  .vb61f66(w60),
  .va191ad(w87)
 );
 v6348d5 v2201b2 (
  .vcff9d0(w3),
  .v869a97(w88)
 );
 vc80943 va17d28 (
  .v1ec852(w3),
  .v595263(w90)
 );
 v27fd6d vb1a3a7 (
  .v18e78c(w5),
  .v9f69ad(w70),
  .v9892c7(w80)
 );
 va21ae0 v538e54 (
  .v18e78c(w4),
  .v40cb98(w69),
  .v4145bb(w79)
 );
 v24496a v75955a (
  .v0e28cb(w4),
  .v3ca442(w5),
  .vcbab45(w6)
 );
 v528969 v7d7539 (
  .v0e28cb(w6),
  .v3ca442(w7),
  .vcbab45(w15)
 );
 v528969 v7e0594 (
  .v0e28cb(w8),
  .v3ca442(w9),
  .vcbab45(w13)
 );
 v36136f v90000b (
  .v593755(w10),
  .v5be714(w89),
  .vd006e6(w96)
 );
 v917222 vd81517 (
  .va191ad(w10),
  .v285646(w11),
  .v766044(w102)
 );
 va0b8df ve9245a (
  .va50a91(w11)
 );
 v7263b9 v74e9a4 (
  .v737e15(w12),
  .vf0dd0a(w13),
  .v15c355(w14),
  .v1b2099(w15),
  .ve5ee9d(w16),
  .v7fcaae(w17),
  .v858373(w18),
  .v21d803(w19),
  .va191ad(w83)
 );
 v21cfcc v214df7 (
  .v9fb85f(w17)
 );
 v49d51e vd141a5 (
  .vbdd51f(w20),
  .v3fb88b(w22),
  .vb4ed69(w23),
  .vd48707(w64),
  .vb6bab2(w72),
  .v3f3f35(w73),
  .vcd2a33(w83),
  .v31c944(w85),
  .v06410a(w86),
  .v71c62f(w87),
  .va541fd(w88),
  .v9b8a50(w93),
  .v30db33(w94),
  .v21e136(w96),
  .v062092(w97),
  .v3d1227(w99),
  .ve81325(w100)
 );
 v3bf99b vb4fc85 (
  .vb096dc(w20)
 );
 v73403c v068e8c (
  .v595263(w21),
  .vf9119c(w100),
  .v85accc(w102)
 );
 v70125e vfcd93f (
  .ve57f84(w56),
  .v21e136(w71),
  .v062092(w81),
  .vbdd51f(w84),
  .v3fb88b(w86),
  .v3d1227(w92)
 );
 v18cbcb v5bc727 (
  .v0daf7d(w56),
  .v735395(w57),
  .v930b03(w103)
 );
 v49d51e v325b10 (
  .vcd2a33(w24),
  .vb6bab2(w28),
  .vd48707(w29),
  .vb4ed69(w30),
  .v3d1227(w32),
  .v062092(w33),
  .v21e136(w34),
  .v30db33(w35),
  .v9b8a50(w36),
  .va541fd(w37),
  .v71c62f(w38),
  .v3fb88b(w53),
  .ve81325(w101),
  .v3f3f35(w106),
  .v31c944(w107),
  .v06410a(w108),
  .vbdd51f(w109)
 );
 v5ad97e #(
  .vc5c8ea(p25)
 ) v04d8fd (
  .v26dbdb(w24)
 );
 v5ad97e #(
  .vc5c8ea(p26)
 ) v4cc0bc (
  .v26dbdb(w28)
 );
 v5ad97e #(
  .vc5c8ea(p27)
 ) vf72751 (
  .v26dbdb(w29)
 );
 v5ad97e #(
  .vc5c8ea(p31)
 ) v32e16a (
  .v26dbdb(w32)
 );
 v5ad97e #(
  .vc5c8ea(p39)
 ) v8898d4 (
  .v26dbdb(w41)
 );
 v9f8856 ve26ac1 (
  .va191ad(w40),
  .v276bb9(w57)
 );
 vd63ed5 v7cd2a6 (
  .vea7b5b(w40),
  .vc96239(w41),
  .v274c22(w108)
 );
 v147de6 v17015d (
  .v9ffacd(w42),
  .v930b03(w104)
 );
 v359a55 v44a780 (
  .v50d6c6(w42),
  .v02d898(w82),
  .vf24dba(w85),
  .vd6b984(w95)
 );
 v359a55 ve65d04 (
  .vd6b984(w45),
  .v02d898(w46),
  .vf24dba(w107)
 );
 v5ad97e #(
  .vc5c8ea(p43)
 ) v38cf94 (
  .v26dbdb(w46)
 );
 v5ad97e #(
  .vc5c8ea(p44)
 ) vca1782 (
  .v26dbdb(w45)
 );
 v5ad97e #(
  .vc5c8ea(p47)
 ) v2438f7 (
  .v26dbdb(w51)
 );
 v448035 v2610ac (
  .v84546f(w48),
  .v31c84d(w52)
 );
 v85651a vd41a3f (
  .vc96239(w48),
  .v274c22(w49),
  .vea7b5b(w98)
 );
 v10466b #(
  .v16d6b8(p50)
 ) vfb5f49 (
  .v633638(w49),
  .v18e78c(w62)
 );
 vdc50be v2ac06e (
  .vea7b5b(w51),
  .v76af38(w63),
  .v274c22(w106)
 );
 v30a3ea v00f83d (
  .vf96989(w52),
  .v9ffacd(w61),
  .v930b03(w105)
 );
 v6f058b v240f1c (
  .v2ebc76(w54),
  .v0d81e4(w64),
  .v6b375c(w73),
  .v4a41db(w84),
  .vd65308(w89)
 );
 v6f058b ve0edfa (
  .v2ebc76(w55),
  .v0d81e4(w95),
  .vd65308(w98)
 );
 ve493b2 v544c21 (
 
 );
 v7107c6 vb2a685 (
  .ve83d32(w58),
  .v2c4c48(w59),
  .v595263(w91)
 );
 v80fc29 v4ea14d (
  .vf39709(w58),
  .v14ddcc(w59),
  .v1a0366(w60)
 );
 v816138 vf03905 (
  .v3ca442(w61),
  .v0e28cb(w62),
  .vcbab45(w63)
 );
endmodule

/*-------------------------------------------------*/
/*-- alu1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v36136f (
 input [7:0] v5be714,
 input [7:0] v593755,
 output v654087,
 output [7:0] vd006e6
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 assign v654087 = w0;
 assign w1 = v593755;
 assign vd006e6 = w2;
 assign w3 = v5be714;
 v36136f_va0c26a va0c26a (
  .c(w0),
  .b(w1),
  .s(w2),
  .a(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- sum-2p-8bits-carry  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sumador  de 8 bits, con acarreo
/*-------------------------------------------------*/

module v36136f_va0c26a (
 input [7:0] a,
 input [7:0] b,
 output c,
 output [7:0] s
);
 wire [8:0] temp;
 assign temp = {1'b0, a} + {1'b0, b};
 assign s = temp[7:0];
 assign c = temp[8];
 //--test
endmodule
//---- Top entity
module v323be2 (
 input [7:0] v9bea93,
 output [7:0] v3515d4
);
 wire [0:7] w0;
 wire [0:7] w1;
 assign w0 = v9bea93;
 assign v3515d4 = w1;
 v323be2_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOT-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta NOT para bus de 8 bits
/*-------------------------------------------------*/

module v323be2_vd54ca1 (
 input [7:0] a,
 output [7:0] c
);
 //-- Puerta NOT
 
 //-- module (input wire a, output wire c);
 
 
 assign c = ~a;
 
 
 //-- endmodule
 
endmodule
//---- Top entity
module v7d7474 #(
 parameter v8d305c = 1
) (
 input [7:0] ve41da3,
 output [7:0] v9c083a
);
 localparam p0 = v8d305c;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w1 = ve41da3;
 assign v9c083a = w2;
 v7d7474_va0c26a #(
  .k(p0)
 ) va0c26a (
  .a(w1),
  .s(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- sum-1op-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sumador de un operando de 8 bits con una constante pasada como parámetro (No hay accarreo)
/*-------------------------------------------------*/

module v7d7474_va0c26a #(
 parameter k = 0
) (
 input [7:0] a,
 output [7:0] s
);
 assign s = a + k;
endmodule
//---- Top entity
module v85651a (
 input [7:0] vea7b5b,
 input [7:0] vc96239,
 output [7:0] v274c22
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w0 = vea7b5b;
 assign v274c22 = w1;
 assign w2 = vc96239;
 v85651a_vce9fab vce9fab (
  .a(w0),
  .o(w1),
  .b(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND-8  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- AND bit a bit entre dos buses de 8 bits
/*-------------------------------------------------*/

module v85651a_vce9fab (
 input [7:0] a,
 input [7:0] b,
 output [7:0] o
);
 assign o = a & b;
 
endmodule
//---- Top entity
module vaf6fc9 (
 input v4ef985,
 input [6:0] vb61f66,
 output [7:0] va191ad
);
 wire [0:6] w0;
 wire w1;
 wire [0:7] w2;
 assign w0 = vb61f66;
 assign w1 = v4ef985;
 assign va191ad = w2;
 vaf6fc9_v9a2a06 v9a2a06 (
  .i0(w0),
  .i1(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 1 cable y un bus de 7-bits a bus de 8-bits
/*-------------------------------------------------*/

module vaf6fc9_v9a2a06 (
 input i1,
 input [6:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v6348d5 (
 input [6:0] vcff9d0,
 input v428b2b,
 output [7:0] v869a97
);
 wire [0:6] w0;
 wire w1;
 wire [0:7] w2;
 assign w0 = vcff9d0;
 assign w1 = v428b2b;
 assign v869a97 = w2;
 v6348d5_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de un bus de 7 bits y un cable a bus de 8-bits
/*-------------------------------------------------*/

module v6348d5_v9a2a06 (
 input [6:0] i1,
 input i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vc80943 (
 input [7:0] v595263,
 output v57076f,
 output [6:0] v1ec852
);
 wire [0:7] w0;
 wire w1;
 wire [0:6] w2;
 assign w0 = v595263;
 assign v57076f = w1;
 assign v1ec852 = w2;
 vc80943_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus-1-7  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 8-bits en 2 buses de 1 y 7 bits
/*-------------------------------------------------*/

module vc80943_v9a2a06 (
 input [7:0] i,
 output o1,
 output [6:0] o0
);
 assign o1 = i[7];
 assign o0 = i[6:0];
endmodule
//---- Top entity
module v27fd6d (
 input [7:0] v9892c7,
 input [7:0] v9f69ad,
 output v18e78c
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign v18e78c = w0;
 assign w1 = v9f69ad;
 assign w2 = v9892c7;
 v27fd6d_vd75681 vd75681 (
  .eq(w0),
  .b(w1),
  .a(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Menor-que-2-op  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comparador menor que, de dos operandos de 8 bits
/*-------------------------------------------------*/

module v27fd6d_vd75681 (
 input [7:0] a,
 input [7:0] b,
 output eq
);
 assign eq = (a < b);
endmodule
//---- Top entity
module va21ae0 (
 input [7:0] v4145bb,
 input [7:0] v40cb98,
 output v18e78c
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign v18e78c = w0;
 assign w1 = v40cb98;
 assign w2 = v4145bb;
 va21ae0_vd75681 vd75681 (
  .eq(w0),
  .b(w1),
  .a(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Comparador de dos operandos  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comparador de dos operandos de 8 bits
/*-------------------------------------------------*/

module va21ae0_vd75681 (
 input [7:0] a,
 input [7:0] b,
 output eq
);
 assign eq = (a == b);
endmodule
//---- Top entity
module v24496a (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v24496a_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOR  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- NOR logic gate
/*-------------------------------------------------*/

module v24496a_vf4938a (
 input a,
 input b,
 output c
);
 // NOR logic gate
 
 assign c = ~(a | b);
endmodule
//---- Top entity
module v528969 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v528969_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- OR  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- OR logic gate
/*-------------------------------------------------*/

module v528969_vf4938a (
 input a,
 input b,
 output c
);
 // OR logic gate
 
 assign c = a | b;
endmodule
//---- Top entity
module v917222 (
 input [3:0] v285646,
 input [3:0] v766044,
 output [7:0] va191ad
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 assign w0 = v766044;
 assign w1 = v285646;
 assign va191ad = w2;
 v917222_v9a2a06 v9a2a06 (
  .i0(w0),
  .i1(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 2 buses de 4-bits a bus de 8-bits
/*-------------------------------------------------*/

module v917222_v9a2a06 (
 input [3:0] i1,
 input [3:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module va0b8df #(
 parameter vfffc23 = 0
) (
 output [3:0] va50a91
);
 localparam p0 = vfffc23;
 wire [0:3] w1;
 assign va50a91 = w1;
 v9274d3 #(
  .vc5c8ea(p0)
 ) v8800c6 (
  .v00a92d(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_0_4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 0 para bus de 4 bits
/*-------------------------------------------------*/
//---- Top entity
module v9274d3 #(
 parameter vc5c8ea = 0
) (
 output [3:0] v00a92d
);
 localparam p1 = vc5c8ea;
 wire [0:3] w0;
 assign v00a92d = w0;
 v9274d3_v465065 #(
  .VALUE(p1)
 ) v465065 (
  .k(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- Constante-4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor genérico constante, de 4 bits. Su valor se introduce como parámetro. Por defecto vale 0
/*-------------------------------------------------*/

module v9274d3_v465065 #(
 parameter VALUE = 0
) (
 output [3:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module v7263b9 (
 input v7fcaae,
 input v858373,
 input v21d803,
 input ve5ee9d,
 input v1b2099,
 input v15c355,
 input vf0dd0a,
 input v737e15,
 output [7:0] va191ad
);
 wire [0:7] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 assign va191ad = w0;
 assign w1 = v7fcaae;
 assign w2 = v858373;
 assign w3 = v21d803;
 assign w4 = ve5ee9d;
 assign w5 = v1b2099;
 assign w6 = v15c355;
 assign w7 = vf0dd0a;
 assign w8 = v737e15;
 v7263b9_v9a2a06 v9a2a06 (
  .o(w0),
  .i7(w1),
  .i6(w2),
  .i5(w3),
  .i4(w4),
  .i3(w5),
  .i2(w6),
  .i1(w7),
  .i0(w8)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 8 cables de 1-bit a bus de 8-bits
/*-------------------------------------------------*/

module v7263b9_v9a2a06 (
 input i7,
 input i6,
 input i5,
 input i4,
 input i3,
 input i2,
 input i1,
 input i0,
 output [7:0] o
);
 assign o = {i7, i6, i5, i4, i3, i2, i1, i0};
 
endmodule
//---- Top entity
module v49d51e (
 input [7:0] v732d31,
 input [7:0] vb4ed69,
 input [7:0] vd48707,
 input [7:0] vb6bab2,
 input [7:0] v3f3f35,
 input [7:0] vcd2a33,
 input [7:0] v31c944,
 input [7:0] v06410a,
 input [7:0] v71c62f,
 input [7:0] va541fd,
 input [7:0] v9b8a50,
 input [7:0] v30db33,
 input [7:0] vbdd51f,
 input [7:0] v21e136,
 input [7:0] v062092,
 input [7:0] v3d1227,
 input [3:0] ve81325,
 output [7:0] v3fb88b
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:7] w5;
 wire [0:7] w6;
 wire [0:7] w7;
 wire [0:7] w8;
 wire [0:7] w9;
 wire [0:7] w10;
 wire [0:7] w11;
 wire [0:7] w12;
 wire [0:7] w13;
 wire [0:7] w14;
 wire [0:7] w15;
 wire [0:7] w16;
 wire [0:3] w17;
 assign v3fb88b = w0;
 assign w1 = v062092;
 assign w2 = v3d1227;
 assign w3 = v21e136;
 assign w4 = vbdd51f;
 assign w5 = v30db33;
 assign w6 = v71c62f;
 assign w7 = va541fd;
 assign w8 = v9b8a50;
 assign w9 = v06410a;
 assign w10 = v31c944;
 assign w11 = vcd2a33;
 assign w12 = v3f3f35;
 assign w13 = vb6bab2;
 assign w14 = vd48707;
 assign w15 = vb4ed69;
 assign w16 = v732d31;
 assign w17 = ve81325;
 v49d51e_ve4e0df ve4e0df (
  .o(w0),
  .i1(w1),
  .i0(w2),
  .i2(w3),
  .i3(w4),
  .i4(w5),
  .i7(w6),
  .i6(w7),
  .i5(w8),
  .i8(w9),
  .i9(w10),
  .i10(w11),
  .i11(w12),
  .i12(w13),
  .i13(w14),
  .i14(w15),
  .i15(w16),
  .s(w17)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux-16-1- 8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 16 a 1 de 8 bits
/*-------------------------------------------------*/

module v49d51e_ve4e0df (
 input [7:0] i15,
 input [7:0] i14,
 input [7:0] i13,
 input [7:0] i12,
 input [7:0] i11,
 input [7:0] i10,
 input [7:0] i9,
 input [7:0] i8,
 input [7:0] i7,
 input [7:0] i6,
 input [7:0] i5,
 input [7:0] i4,
 input [7:0] i3,
 input [7:0] i2,
 input [7:0] i1,
 input [7:0] i0,
 input [3:0] s,
 output [7:0] o
);
 //-- Multiplexor de 16 a 1, 
 //-- de 8 bits
 
 assign o = (s == 4'h0) ? i0 :
            (s == 4'h1) ? i1 :
            (s == 4'h2) ? i2 : 
            (s == 4'h3) ? i3 :
            (s == 4'h4) ? i4 :
            (s == 4'h5) ? i5 :
            (s == 4'h6) ? i6 :
            (s == 4'h7) ? i7 :
            (s == 4'h8) ? i8 :
            (s == 4'h9) ? i9 :
            (s == 4'ha) ? i10 : 
            (s == 4'hb) ? i11 :
            (s == 4'hc) ? i12 :
            (s == 4'hd) ? i13 :
            (s == 4'he) ? i14 :
            (s == 4'hf) ? i15 :
            4'h0;
            
 
 
endmodule
//---- Top entity
module v73403c (
 input [7:0] v595263,
 output [3:0] vf9119c,
 output [3:0] v85accc
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 assign vf9119c = w0;
 assign v85accc = w1;
 assign w2 = v595263;
 v73403c_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 8-bits en buses de 4 bits
/*-------------------------------------------------*/

module v73403c_v9a2a06 (
 input [7:0] i,
 output [3:0] o1,
 output [3:0] o0
);
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module v70125e (
 input [7:0] vbdd51f,
 input [7:0] v21e136,
 input [7:0] v062092,
 input [7:0] v3d1227,
 input [1:0] ve57f84,
 output [7:0] v3fb88b
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:1] w5;
 assign v3fb88b = w0;
 assign w1 = v3d1227;
 assign w2 = v062092;
 assign w3 = v21e136;
 assign w4 = vbdd51f;
 assign w5 = ve57f84;
 v70125e_ve4e0df ve4e0df (
  .o(w0),
  .i0(w1),
  .i1(w2),
  .i2(w3),
  .i3(w4),
  .s(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- 8bits-Mux-4-1-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 4 a 1 de 8 bits
/*-------------------------------------------------*/

module v70125e_ve4e0df (
 input [7:0] i3,
 input [7:0] i2,
 input [7:0] i1,
 input [7:0] i0,
 input [1:0] s,
 output [7:0] o
);
 //-- Multiplexor de 4 a 1, 
 //-- de 8 bits
 
 assign o = (s == 2'b00) ? i0 :
            (s == 2'b01) ? i1 :
            (s == 2'b10) ? i2 : i3;
 
 
endmodule
//---- Top entity
module v18cbcb (
 input [3:0] v930b03,
 output [1:0] v0daf7d,
 output [1:0] v735395
);
 wire [0:1] w0;
 wire [0:1] w1;
 wire [0:3] w2;
 assign v0daf7d = w0;
 assign v735395 = w1;
 assign w2 = v930b03;
 v18cbcb_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 4-bits en buses de 2 bits
/*-------------------------------------------------*/

module v18cbcb_v9a2a06 (
 input [3:0] i,
 output [1:0] o1,
 output [1:0] o0
);
 assign o1 = i[3:2];
 assign o0 = i[1:0];
endmodule
//---- Top entity
module v9f8856 (
 input [5:0] v7c0b91,
 input [1:0] v276bb9,
 output [7:0] va191ad
);
 wire [0:7] w0;
 wire [0:1] w1;
 wire [0:5] w2;
 assign va191ad = w0;
 assign w1 = v276bb9;
 assign w2 = v7c0b91;
 v9f8856_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus-6-2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 2 buses de 6 y 2-bits a bus de 8-bits
/*-------------------------------------------------*/

module v9f8856_v9a2a06 (
 input [5:0] i1,
 input [1:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vd63ed5 (
 input [7:0] vea7b5b,
 input [7:0] vc96239,
 output [7:0] v274c22
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w0 = vea7b5b;
 assign v274c22 = w1;
 assign w2 = vc96239;
 vd63ed5_vce9fab vce9fab (
  .a(w0),
  .o(w1),
  .b(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- OR-8  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- OR bit a bit entre dos buses de 8 bits
/*-------------------------------------------------*/

module vd63ed5_vce9fab (
 input [7:0] a,
 input [7:0] b,
 output [7:0] o
);
 assign o = a | b;
 
endmodule
//---- Top entity
module v147de6 (
 input [3:0] v930b03,
 output [2:0] vf96989,
 output v9ffacd
);
 wire [0:3] w0;
 wire [0:2] w1;
 wire w2;
 assign w0 = v930b03;
 assign vf96989 = w1;
 assign v9ffacd = w2;
 v147de6_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 4-bits en bus de 3 bits y cable
/*-------------------------------------------------*/

module v147de6_v9a2a06 (
 input [3:0] i,
 output [2:0] o1,
 output o0
);
 assign o1 = i[3:1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v359a55 (
 input [7:0] v02d898,
 input [7:0] vd6b984,
 input v50d6c6,
 output [7:0] vf24dba
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 assign w0 = v50d6c6;
 assign w1 = vd6b984;
 assign w2 = v02d898;
 assign vf24dba = w3;
 v359a55_ve4e0df ve4e0df (
  .sel(w0),
  .i0(w1),
  .i1(w2),
  .o(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux 2 a 1 de 8 bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 2 a 1 de 8 bits
/*-------------------------------------------------*/

module v359a55_ve4e0df (
 input [7:0] i1,
 input [7:0] i0,
 input sel,
 output [7:0] o
);
 //-- Multiplexor de 2 a 1, 
 //-- de 8 bits
 
 reg [7:0] o;
 
 always @(*) begin
     case(sel)
         0: o = i0;
         1: o = i1;
         default: o = i0;
     endcase
 end
 
 
endmodule
//---- Top entity
module v448035 (
 input [2:0] v31c84d,
 output [7:0] v84546f
);
 wire [0:2] w0;
 wire [0:7] w1;
 assign w0 = v31c84d;
 assign v84546f = w1;
 v448035_v3d7f3a v3d7f3a (
  .y(w0),
  .i(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Decodificador-3-8-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Decodificador de 3 a 8, con salida en bus
/*-------------------------------------------------*/

module v448035_v3d7f3a (
 input [2:0] y,
 output [7:0] i
);
 assign i = 1 << y;
                        
 
endmodule
//---- Top entity
module v10466b #(
 parameter v16d6b8 = 1
) (
 input [7:0] v633638,
 output v18e78c
);
 localparam p1 = v16d6b8;
 wire w0;
 wire [0:7] w2;
 assign v18e78c = w0;
 assign w2 = v633638;
 v10466b_vd75681 #(
  .B(p1)
 ) vd75681 (
  .eq(w0),
  .a(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mayor-que-1-op  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comparador mayor que, de un operando de 8 bits
/*-------------------------------------------------*/

module v10466b_vd75681 #(
 parameter B = 0
) (
 input [7:0] a,
 output eq
);
 assign eq = (a > B);
endmodule
//---- Top entity
module vdc50be (
 input [7:0] vea7b5b,
 input v76af38,
 output [7:0] v274c22
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w0 = v76af38;
 assign w1 = vea7b5b;
 assign v274c22 = w2;
 vdc50be_vce9fab vce9fab (
  .b(w0),
  .a(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND-8-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Habilitación de bus de 8 bits
/*-------------------------------------------------*/

module vdc50be_vce9fab (
 input [7:0] a,
 input b,
 output [7:0] o
);
 assign o[0] = a[0] & b;
 assign o[1] = a[1] & b;
 assign o[2] = a[2] & b;
 assign o[3] = a[3] & b;
 assign o[4] = a[4] & b;
 assign o[5] = a[5] & b;
 assign o[6] = a[6] & b;
 assign o[7] = a[7] & b;
endmodule
//---- Top entity
module v30a3ea (
 input [3:0] v930b03,
 output v9ffacd,
 output [2:0] vf96989
);
 wire [0:3] w0;
 wire [0:2] w1;
 wire w2;
 assign w0 = v930b03;
 assign vf96989 = w1;
 assign v9ffacd = w2;
 v30a3ea_v9a2a06 v9a2a06 (
  .i(w0),
  .o0(w1),
  .o1(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus-1-3  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 4-bits en buses de 1 bits y 3 bits
/*-------------------------------------------------*/

module v30a3ea_v9a2a06 (
 input [3:0] i,
 output o1,
 output [2:0] o0
);
 assign o1 = i[3];
 assign o0 = i[2:0];
endmodule
//---- Top entity
module ve493b2 #(
 parameter vaf1d6e = 0
) (
 input [7:0] vdf5b7a,
 input vb6a1db,
 output [7:0] v2cc258
);
 localparam p0 = vaf1d6e;
 wire [0:7] w1;
 wire [0:7] w2;
 wire w3;
 assign w1 = vdf5b7a;
 assign v2cc258 = w2;
 assign w3 = vb6a1db;
 ve493b2_vd80544 #(
  .BIT(p0)
 ) vd80544 (
  .i(w1),
  .o(w2),
  .a(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Insert-1-bit  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Inyectar el valor de un cable por el bit indicado de un bus
/*-------------------------------------------------*/

module ve493b2_vd80544 #(
 parameter BIT = 0
) (
 input [7:0] i,
 input a,
 output [7:0] o
);
 reg [7:0] o;
 
 always @(*) begin
 
  o[7:0] = i[7:0];
  o[BIT] = a;
  
 end
endmodule
//---- Top entity
module v7107c6 (
 input [7:0] v595263,
 output [7:2] ve83d32,
 output v2c4c48,
 output v2b13a4
);
 wire [0:7] w0;
 wire w1;
 wire w2;
 wire [0:5] w3;
 assign w0 = v595263;
 assign v2c4c48 = w1;
 assign v2b13a4 = w2;
 assign ve83d32 = w3;
 v7107c6_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2),
  .o2(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus-6-1-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 8-bits en 1 buses de 6 bits y dos cables sueltos
/*-------------------------------------------------*/

module v7107c6_v9a2a06 (
 input [7:0] i,
 output [7:2] o2,
 output o1,
 output o0
);
 assign o2 = i[7:2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v80fc29 (
 input [5:0] vf39709,
 input v14ddcc,
 output [6:0] v1a0366
);
 wire w0;
 wire [0:6] w1;
 wire [0:5] w2;
 assign w0 = v14ddcc;
 assign v1a0366 = w1;
 assign w2 = vf39709;
 v80fc29_v9a2a06 v9a2a06 (
  .i0(w0),
  .o(w1),
  .i1(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- 7bits-bus-joiner-6-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Join a 6-bit bus and 1 one into a 7-bits bus
/*-------------------------------------------------*/

module v80fc29_v9a2a06 (
 input [5:0] i1,
 input i0,
 output [6:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v816138 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v816138_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- OR  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta OR
/*-------------------------------------------------*/

module v816138_vf4938a (
 input a,
 input b,
 output c
);
 //-- Puerta OR
 
 //-- module and (input wire a, input wire b,
 //--             output wire c);
 
 assign c = a | b;
 
 //-- endmodule
endmodule
//---- Top entity
module v157cb8 (
 input [7:0] vbfdb97,
 input [7:0] vc2ef4f,
 input v78b22f,
 output [31:0] v961ee9,
 output [31:0] vd115bb,
 output [7:0] v84ec18
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire [0:5] w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire [0:3] w15;
 wire [0:3] w16;
 wire [0:1] w17;
 wire [0:1] w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire [0:3] w25;
 wire [0:3] w26;
 wire [0:7] w27;
 wire [0:7] w28;
 wire [0:7] w29;
 wire w30;
 wire w31;
 wire [0:7] w32;
 wire [0:7] w33;
 wire [0:7] w34;
 wire [0:7] w35;
 wire [0:7] w36;
 wire [0:31] w37;
 wire [0:31] w38;
 wire [0:7] w39;
 wire [0:7] w40;
 wire [0:7] w41;
 wire [0:7] w42;
 wire [0:7] w43;
 wire w44;
 wire w45;
 wire [0:7] w46;
 wire [0:7] w47;
 wire [0:7] w48;
 wire [0:7] w49;
 wire [0:7] w50;
 wire [0:7] w51;
 wire [0:7] w52;
 wire [0:7] w53;
 assign w3 = v78b22f;
 assign w4 = v78b22f;
 assign w5 = v78b22f;
 assign w6 = v78b22f;
 assign w7 = v78b22f;
 assign w8 = v78b22f;
 assign w9 = v78b22f;
 assign w27 = vc2ef4f;
 assign v961ee9 = w37;
 assign vd115bb = w38;
 assign v84ec18 = w43;
 assign w44 = v78b22f;
 assign w46 = vbfdb97;
 assign w47 = vbfdb97;
 assign w48 = vbfdb97;
 assign w49 = vbfdb97;
 assign w50 = vbfdb97;
 assign w51 = vbfdb97;
 assign w52 = vbfdb97;
 assign w53 = vbfdb97;
 assign w4 = w3;
 assign w5 = w3;
 assign w5 = w4;
 assign w6 = w3;
 assign w6 = w4;
 assign w6 = w5;
 assign w7 = w3;
 assign w7 = w4;
 assign w7 = w5;
 assign w7 = w6;
 assign w8 = w3;
 assign w8 = w4;
 assign w8 = w5;
 assign w8 = w6;
 assign w8 = w7;
 assign w9 = w3;
 assign w9 = w4;
 assign w9 = w5;
 assign w9 = w6;
 assign w9 = w7;
 assign w9 = w8;
 assign w40 = w29;
 assign w43 = w29;
 assign w43 = w40;
 assign w44 = w3;
 assign w44 = w4;
 assign w44 = w5;
 assign w44 = w6;
 assign w44 = w7;
 assign w44 = w8;
 assign w44 = w9;
 assign w47 = w46;
 assign w48 = w46;
 assign w48 = w47;
 assign w49 = w46;
 assign w49 = w47;
 assign w49 = w48;
 assign w50 = w46;
 assign w50 = w47;
 assign w50 = w48;
 assign w50 = w49;
 assign w51 = w46;
 assign w51 = w47;
 assign w51 = w48;
 assign w51 = w49;
 assign w51 = w50;
 assign w52 = w46;
 assign w52 = w47;
 assign w52 = w48;
 assign w52 = w49;
 assign w52 = w50;
 assign w52 = w51;
 assign w53 = w46;
 assign w53 = w47;
 assign w53 = w48;
 assign w53 = w49;
 assign w53 = w50;
 assign w53 = w51;
 assign w53 = w52;
 v89d234 v00cf70 (
  .v41eb95(w3),
  .vf892a0(w21),
  .vb1c024(w33),
  .v39f831(w46)
 );
 v89d234 v52e8e8 (
  .v41eb95(w4),
  .vf892a0(w22),
  .vb1c024(w34),
  .v39f831(w47)
 );
 v89d234 v3a923a (
  .v41eb95(w5),
  .vf892a0(w23),
  .vb1c024(w35),
  .v39f831(w48)
 );
 v89d234 v5a42b0 (
  .v41eb95(w6),
  .vf892a0(w24),
  .vb1c024(w36),
  .v39f831(w49)
 );
 v89d234 vc3d5eb (
  .vf892a0(w0),
  .v41eb95(w7),
  .vb1c024(w39),
  .v39f831(w50)
 );
 v89d234 v3b4bcb (
  .vb1c024(w29),
  .vf892a0(w30),
  .v39f831(w32),
  .v41eb95(w45)
 );
 v89d234 vdb2ed9 (
  .vf892a0(w1),
  .v41eb95(w8),
  .vb1c024(w41),
  .v39f831(w52)
 );
 v89d234 ve77b64 (
  .vf892a0(w2),
  .v41eb95(w9),
  .vb1c024(w42),
  .v39f831(w53)
 );
 v45c913 v46cbae (
  .v593f43(w0),
  .vc90115(w1),
  .v5b73e8(w2),
  .v930b03(w26),
  .v2812a7(w31)
 );
 v7404e6 v9184a8 (
  .v4ce39b(w10),
  .v595263(w27)
 );
 vd4bd04 v776aa2 (
  .v03aaf0(w11),
  .vee8a83(w12),
  .v67a3fc(w18)
 );
 vd4bd04 v474d28 (
  .v03aaf0(w13),
  .vee8a83(w14),
  .v67a3fc(w17)
 );
 vfd8998 v289c22 (
  .vbb390a(w10),
  .v45ab8c(w11),
  .vb85197(w12),
  .v8f149e(w13),
  .v7c37b3(w14),
  .ve0c1b4(w19),
  .v2c9812(w20)
 );
 v1c4cc4 va801cf (
  .v9c304b(w16),
  .v827425(w17)
 );
 v13d09a ve0ffcc (
  .vd317b3(w16),
  .v76af38(w20),
  .ve2642f(w26)
 );
 v1c4cc4 va6e1f2 (
  .v9c304b(w15),
  .v827425(w18)
 );
 v13d09a v81f649 (
  .vd317b3(w15),
  .v76af38(w19),
  .ve2642f(w25)
 );
 v45c913 v3f14be (
  .v593f43(w21),
  .v2812a7(w22),
  .vc90115(w23),
  .v5b73e8(w24),
  .v930b03(w25)
 );
 v359a55 ve3d83e (
  .vd6b984(w28),
  .v50d6c6(w31),
  .vf24dba(w32),
  .v02d898(w51)
 );
 v7d7474 v973e98 (
  .v9c083a(w28),
  .ve41da3(w29)
 );
 v725b7e v1dca89 (
  .v9fb85f(w30)
 );
 vb6ddba vc7c352 (
  .v9999de(w33),
  .v63d71a(w34),
  .v32ad8d(w35),
  .v7a6a68(w36),
  .v2eef2f(w37)
 );
 vb6ddba v72b1e4 (
  .v2eef2f(w38),
  .v9999de(w39),
  .v63d71a(w40),
  .v32ad8d(w41),
  .v7a6a68(w42)
 );
 v96f098 v81616d (
  .v0e28cb(w44),
  .vcbab45(w45)
 );
endmodule

/*-------------------------------------------------*/
/*-- reg1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v89d234 #(
 parameter v422d28 = 0
) (
 input v41eb95,
 input [7:0] v39f831,
 input vf892a0,
 output [7:0] vb1c024
);
 localparam p0 = v422d28;
 wire [0:7] w1;
 wire [0:7] w2;
 wire w3;
 wire w4;
 assign vb1c024 = w1;
 assign w2 = v39f831;
 assign w3 = vf892a0;
 assign w4 = v41eb95;
 v89d234_v9148cb #(
  .INI(p0)
 ) v9148cb (
  .q(w1),
  .d(w2),
  .load(w3),
  .clk(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Registro  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Registro de 8 bits
/*-------------------------------------------------*/

module v89d234_v9148cb #(
 parameter INI = 0
) (
 input clk,
 input [7:0] d,
 input load,
 output [7:0] q
);
 localparam N = 8;
 
 reg [N-1:0] q = INI;
 
 always @(posedge clk)
   if (load)
     q <= d;
endmodule
//---- Top entity
module v45c913 (
 input [3:0] v930b03,
 output v5b73e8,
 output vc90115,
 output v2812a7,
 output v593f43
);
 wire [0:3] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v930b03;
 assign v2812a7 = w1;
 assign v593f43 = w2;
 assign vc90115 = w3;
 assign v5b73e8 = w4;
 v45c913_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2),
  .o2(w3),
  .o3(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 4-bits en 4 cables
/*-------------------------------------------------*/

module v45c913_v9a2a06 (
 input [3:0] i,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module vd4bd04 (
 input vee8a83,
 input v03aaf0,
 output [1:0] v67a3fc
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign v67a3fc = w2;
 vd4bd04_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 2 cables en un bus de 2-bits
/*-------------------------------------------------*/

module vd4bd04_v9a2a06 (
 input i1,
 input i0,
 output [1:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vfd8998 (
 input [5:0] vbb390a,
 output v2c9812,
 output ve0c1b4,
 output v7c37b3,
 output v8f149e,
 output vb85197,
 output v45ab8c
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:5] w6;
 assign v2c9812 = w0;
 assign ve0c1b4 = w1;
 assign v7c37b3 = w2;
 assign v8f149e = w3;
 assign vb85197 = w4;
 assign v45ab8c = w5;
 assign w6 = vbb390a;
 vfd8998_v9a2a06 v9a2a06 (
  .o5(w0),
  .o4(w1),
  .o3(w2),
  .o2(w3),
  .o1(w4),
  .o0(w5),
  .i(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 6-bits en 6 cables
/*-------------------------------------------------*/

module vfd8998_v9a2a06 (
 input [5:0] i,
 output o5,
 output o4,
 output o3,
 output o2,
 output o1,
 output o0
);
 
 
 assign o5 = i[5];
 assign o4 = i[4];
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v1c4cc4 (
 input [1:0] v827425,
 output [3:0] v9c304b
);
 wire [0:1] w0;
 wire [0:3] w1;
 assign w0 = v827425;
 assign v9c304b = w1;
 v1c4cc4_v3d7f3a v3d7f3a (
  .y(w0),
  .i(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Decodificador-2-4-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Decodificador de 2 a 4, con salida en bus
/*-------------------------------------------------*/

module v1c4cc4_v3d7f3a (
 input [1:0] y,
 output [3:0] i
);
 assign i = 1 << y;
                        
 
endmodule
//---- Top entity
module v13d09a (
 input [3:0] vd317b3,
 input v76af38,
 output [3:0] ve2642f
);
 wire w0;
 wire [0:3] w1;
 wire [0:3] w2;
 assign w0 = v76af38;
 assign w1 = vd317b3;
 assign ve2642f = w2;
 v13d09a_vce9fab vce9fab (
  .b(w0),
  .a(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND-4-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta AND de dos operandos, de 1 y 4 bits
/*-------------------------------------------------*/

module v13d09a_vce9fab (
 input [3:0] a,
 input b,
 output [3:0] o
);
 assign o[3] = a[3] & b;
 assign o[2] = a[2] & b;
 assign o[1] = a[1] & b;
 assign o[0] = a[0] & b;
endmodule
//---- Top entity
module vb6ddba (
 input [7:0] v7a6a68,
 input [7:0] v32ad8d,
 input [7:0] v63d71a,
 input [7:0] v9999de,
 output [31:0] v2eef2f
);
 wire [0:31] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 assign v2eef2f = w0;
 assign w1 = v9999de;
 assign w2 = v63d71a;
 assign w3 = v32ad8d;
 assign w4 = v7a6a68;
 vb6ddba_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2),
  .i2(w3),
  .i3(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 4 buses en un bus de 32-bits
/*-------------------------------------------------*/

module vb6ddba_v9a2a06 (
 input [7:0] i3,
 input [7:0] i2,
 input [7:0] i1,
 input [7:0] i0,
 output [31:0] o
);
 assign o = {i3,i2, i1, i0};
 
endmodule
//---- Top entity
module v96f098 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v96f098_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOT  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- NOT logic gate
/*-------------------------------------------------*/

module v96f098_vd54ca1 (
 input a,
 output c
);
 // NOT logic gate
 
 assign c = ~ a;
endmodule
