// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main #(
 parameter v0601c7 = 10,
 parameter v07c337 = "v07c337.list",
 parameter v0d69e6 = "v0d69e6.list",
 parameter v3b75fc = 19000,
 parameter v96af80 = 17000
) (
 input ve88b73,
 input v269f01,
 input v6c71a3,
 input [1:0] v9b2b58,
 output [7:0] v92d4a0,
 output [7:0] vdb224a,
 output [7:0] v9a0d87,
 output [1:0] vd2dad5
);
 localparam p0 = v0601c7;
 localparam p15 = v0d69e6;
 localparam p16 = v07c337;
 localparam p30 = v96af80;
 localparam p31 = v3b75fc;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:1] w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire [0:31] w13;
 wire [0:31] w14;
 wire [0:1] w17;
 wire [0:7] w18;
 wire w19;
 wire w20;
 wire w21;
 wire [0:1] w22;
 wire w23;
 wire [0:1] w24;
 wire [0:7] w25;
 wire [0:1] w26;
 wire [0:1] w27;
 wire [0:1] w28;
 wire [0:7] w29;
 wire w32;
 wire w33;
 wire w34;
 wire w35;
 wire w36;
 wire w37;
 wire w38;
 wire w39;
 assign w3 = ve88b73;
 assign w8 = v269f01;
 assign w9 = v6c71a3;
 assign w17 = v9b2b58;
 assign vd2dad5 = w26;
 assign v9a0d87 = w29;
 assign w32 = ve88b73;
 assign w33 = ve88b73;
 assign w34 = ve88b73;
 assign w35 = ve88b73;
 assign w36 = ve88b73;
 assign w37 = ve88b73;
 assign w38 = ve88b73;
 assign w39 = ve88b73;
 assign w32 = w3;
 assign w33 = w3;
 assign w33 = w32;
 assign w34 = w3;
 assign w34 = w32;
 assign w34 = w33;
 assign w35 = w3;
 assign w35 = w32;
 assign w35 = w33;
 assign w35 = w34;
 assign w36 = w3;
 assign w36 = w32;
 assign w36 = w33;
 assign w36 = w34;
 assign w36 = w35;
 assign w37 = w3;
 assign w37 = w32;
 assign w37 = w33;
 assign w37 = w34;
 assign w37 = w35;
 assign w37 = w36;
 assign w38 = w3;
 assign w38 = w32;
 assign w38 = w33;
 assign w38 = w34;
 assign w38 = w35;
 assign w38 = w36;
 assign w38 = w37;
 assign w39 = w3;
 assign w39 = w32;
 assign w39 = w33;
 assign w39 = w34;
 assign w39 = w35;
 assign w39 = w36;
 assign w39 = w37;
 assign w39 = w38;
 vcfd9ba v701866 (
  .vd4e5d7(w1),
  .v6a82dd(w8),
  .v444878(w32)
 );
 v0e64bc #(
  .v207e0d(p0)
 ) vffbfa3 (
  .v8337bc(w2),
  .v531e20(w33)
 );
 v28cfaa v2a6eeb (
  .vb186da(w1),
  .v7e70ae(w2),
  .vd7f8af(w3),
  .vc13c07(w4),
  .v9b870f(w5),
  .v381ebf(w7),
  .vc93bbe(w12)
 );
 vfc9dac v7fd77a (
  .v3f8943(w4),
  .v64d863(w5),
  .v8b19dd(w6)
 );
 v2254c0 v9e6800 (
  .ve54597(w6),
  .vd47d8c(w10),
  .vfdbd5b(w34)
 );
 v21cfcc v3d5c88 (
  .v9fb85f(w7)
 );
 vcfd9ba v2ad512 (
  .v6a82dd(w9),
  .vd4e5d7(w11),
  .v444878(w35)
 );
 v8e2728 vfe3d48 (
  .v2dffca(w10),
  .v10eedb(w11),
  .v0884a0(w36)
 );
 v6f058b v02dd4a (
  .v2ebc76(w13)
 );
 v6f058b v61bcb6 (
  .v2ebc76(w14)
 );
 v9f8856 v2d5778 (
  .v276bb9(w17),
  .va191ad(w18)
 );
 vceff2d v5bee0e (
  .v2978f0(w28)
 );
 v945b25 v31a17b (
  .v76af38(w20),
  .vfa2135(w22),
  .v6a6ead(w27)
 );
 v945b25 v284af6 (
  .v76af38(w19),
  .vfa2135(w24),
  .v6a6ead(w28)
 );
 vd3fb4e vb02027 (
  .v2978f0(w27)
 );
 vd4bd04 v6fe3a8 (
  .vee8a83(w21),
  .v03aaf0(w23),
  .v67a3fc(w26)
 );
 v7107c6 v1bce63 (
  .v2b13a4(w19),
  .v2c4c48(w20),
  .v595263(w25)
 );
 v67b82c #(
  .vd2e60e(p15),
  .v27a8d5(p16)
 ) v36af84 (
  .v919ee7(w12),
  .v92d32d(w13),
  .v8ff487(w14),
  .v8cc488(w18),
  .v575022(w25),
  .v72dc50(w29)
 );
 v96655b vbab132 (
  .vfdbd5b(w37)
 );
 v28f89a #(
  .v421b6f(p30)
 ) vc09ef0 (
  .ve9490c(w21),
  .vf79cbe(w22),
  .vc08bbf(w38)
 );
 v28f89a #(
  .v8a2420(p31)
 ) v8d0f6a (
  .ve9490c(w23),
  .vf79cbe(w24),
  .vc08bbf(w39)
 );
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module vcfd9ba (
 input v444878,
 input v6a82dd,
 output vd4e5d7
);
 wire w0;
 wire w1;
 wire w2;
 assign vd4e5d7 = w0;
 assign w1 = v444878;
 assign w2 = v6a82dd;
 vcfd9ba_va7041c va7041c (
  .out(w0),
  .clk(w1),
  .in(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Debouncer  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Remove the rebound on a mechanical switch
/*-------------------------------------------------*/

module vcfd9ba_va7041c (
 input clk,
 input in,
 output out
);
 //-- Debouncer Circuit
 //-- It produces a stable output when the
 //-- input signal is bouncing
 
 reg btn_prev = 0;
 reg btn_out_r = 0;
 
 reg [16:0] counter = 0;
 
 
 always @(posedge clk) begin
 
   //-- If btn_prev and btn_in are differents
   if (btn_prev ^ in == 1'b1) begin
     
       //-- Reset the counter
       counter <= 0;
       
       //-- Capture the button status
       btn_prev <= in;
   end
     
   //-- If no timeout, increase the counter
   else if (counter[16] == 1'b0)
       counter <= counter + 1;
       
   else
     //-- Set the output to the stable value
     btn_out_r <= btn_prev;
 
 end
 
 assign out = btn_out_r;
 
endmodule
//---- Top entity
module v0e64bc #(
 parameter v207e0d = 1
) (
 input v531e20,
 output v8337bc
);
 localparam p2 = v207e0d;
 wire w0;
 wire w1;
 assign v8337bc = w0;
 assign w1 = v531e20;
 v0e64bc_v94c6d7 #(
  .HZ(p2)
 ) v94c6d7 (
  .clk_o(w0),
  .clk(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Corazon_Hz  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Corazon genérico para bombear bits a la frecuencia fijada en Hz (por defecto 1Hz)
/*-------------------------------------------------*/

module v0e64bc_v94c6d7 #(
 parameter HZ = 0
) (
 input clk,
 output clk_o
);
 
 //parameter HZ=1;
 
 //-- Constante para dividir y obtener una frecuencia de 1Hz
 localparam M = 12000000/HZ;
 
 //-- Calcular el numero de bits para almacenar M
 localparam N = $clog2(M);
 
 //-- Registro del divisor
 reg [N-1:0] divcounter;
 
 //-- Temporal clock
 reg clk_t = 0;
 
 //-- Se usa un contador modulo M/2 para luego
 //-- pasarlo por un biestable T y dividir la frecuencia
 //-- entre 2, para que el ciclo de trabajo sea del 50%
 always @(posedge clk)
     if (divcounter == M/2) begin
       clk_t <= 1;
       divcounter = 0;
     end 
     else begin
       divcounter <=  divcounter + 1;
       clk_t = 0;
     end 
   
 reg clk_o = 0;  
     
 //-- Biestable T para obtener ciclo de trabajo del 50%
 always @(posedge clk)
   if (clk_t)
     clk_o <= ~clk_o;
 
endmodule
//---- Top entity
module v28cfaa (
 input vd7f8af,
 input v7e70ae,
 input vb186da,
 input v381ebf,
 input vc13c07,
 input v9b870f,
 output vc93bbe
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign vc93bbe = w0;
 assign w1 = v381ebf;
 assign w2 = vb186da;
 assign w3 = v7e70ae;
 assign w4 = vd7f8af;
 assign w5 = v9b870f;
 assign w6 = vc13c07;
 v28cfaa_ve4e0df ve4e0df (
  .o(w0),
  .i0(w1),
  .i1(w2),
  .i2(w3),
  .i3(w4),
  .s0(w5),
  .s1(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux 4 a 1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 4 a 1. Implementado en verilog
/*-------------------------------------------------*/

module v28cfaa_ve4e0df (
 input i3,
 input i2,
 input i1,
 input i0,
 input s1,
 input s0,
 output o
);
 wire [1:0] sel = {s1, s0};
 
 assign o = (sel == 2'b00) ? i0 :
            (sel == 2'b01) ? i1 :
            (sel == 2'b10) ? i2 : i3;
 
 
endmodule
//---- Top entity
module vfc9dac (
 input [1:0] v8b19dd,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign w2 = v8b19dd;
 vfc9dac_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 2-bits en dos cables
/*-------------------------------------------------*/

module vfc9dac_v9a2a06 (
 input [1:0] i,
 output o1,
 output o0
);
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v2254c0 #(
 parameter vdd0290 = 0,
 parameter vc96add = 1
) (
 input vfdbd5b,
 input vd47d8c,
 output [1:0] ve54597
);
 localparam p0 = vc96add;
 localparam p3 = vdd0290;
 wire w1;
 wire w2;
 wire [0:1] w4;
 assign w1 = vfdbd5b;
 assign w2 = vd47d8c;
 assign ve54597 = w4;
 v2254c0_vf093da #(
  .INC(p0),
  .INI(p3)
 ) vf093da (
  .clk(w1),
  .cnt(w2),
  .q(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Contador-basic  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Contador básico, de 2 bits
/*-------------------------------------------------*/

module v2254c0_vf093da #(
 parameter INI = 0,
 parameter INC = 0
) (
 input clk,
 input cnt,
 output [1:0] q
);
 //-- Número de bits del contador
 
 localparam N = 2;
 
 reg [N-1:0] q = INI;
 
 always @(posedge clk)
   if (cnt)
     q <= q + INC;
endmodule
//---- Top entity
module v21cfcc (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v21cfcc_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 0  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 0
/*-------------------------------------------------*/

module v21cfcc_vb2eccd (
 output q
);
 //-- Bit constante a 0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module v8e2728 (
 input v0884a0,
 input v10eedb,
 output v2dffca
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v10eedb;
 assign v2dffca = w1;
 assign w2 = v0884a0;
 v8e2728_v115ffb v115ffb (
  .i(w0),
  .o(w1),
  .clk(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Subida  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Detector de flanco de subida. Emite un tic cuando detecta un flanco ascendente
/*-------------------------------------------------*/

module v8e2728_v115ffb (
 input clk,
 input i,
 output o
);
 reg q = 0;
 
 always @(posedge clk)
   q <= i;
   
 assign o = (~q & i);  
endmodule
//---- Top entity
module v6f058b (
 input [31:0] v2ebc76,
 output [7:0] v4a41db,
 output [7:0] v0d81e4,
 output [7:0] v6b375c,
 output [7:0] vd65308
);
 wire [0:31] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 assign w0 = v2ebc76;
 assign vd65308 = w1;
 assign v6b375c = w2;
 assign v0d81e4 = w3;
 assign v4a41db = w4;
 v6f058b_v9a2a06 v9a2a06 (
  .i(w0),
  .o0(w1),
  .o1(w2),
  .o2(w3),
  .o3(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 32-bits en 4 buses de 8 bits
/*-------------------------------------------------*/

module v6f058b_v9a2a06 (
 input [31:0] i,
 output [7:0] o3,
 output [7:0] o2,
 output [7:0] o1,
 output [7:0] o0
);
 assign o3 = i[31:24];
 assign o2 = i[23:16];
 assign o1 = i[15:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module v9f8856 (
 input [5:0] v7c0b91,
 input [1:0] v276bb9,
 output [7:0] va191ad
);
 wire [0:7] w0;
 wire [0:1] w1;
 wire [0:5] w2;
 assign va191ad = w0;
 assign w1 = v276bb9;
 assign w2 = v7c0b91;
 v9f8856_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus-6-2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 2 buses de 6 y 2-bits a bus de 8-bits
/*-------------------------------------------------*/

module v9f8856_v9a2a06 (
 input [5:0] i1,
 input [1:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vceff2d #(
 parameter vfffc23 = 3
) (
 output [1:0] v2978f0
);
 localparam p1 = vfffc23;
 wire [0:1] w0;
 assign v2978f0 = w0;
 v157753 #(
  .vc5c8ea(p1)
 ) v2208c0 (
  .v4ffce0(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_3_2bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 3 para bus de 2 bits
/*-------------------------------------------------*/
//---- Top entity
module v157753 #(
 parameter vc5c8ea = 0
) (
 output [1:0] v4ffce0
);
 localparam p1 = vc5c8ea;
 wire [0:1] w0;
 assign v4ffce0 = w0;
 v157753_v465065 #(
  .VALUE(p1)
 ) v465065 (
  .k(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- Constante-2bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor genérico constante, de 2 bits. Su valor se introduce como parámetro. Por defecto vale 0
/*-------------------------------------------------*/

module v157753_v465065 #(
 parameter VALUE = 0
) (
 output [1:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module v945b25 (
 input [1:0] v6a6ead,
 input v76af38,
 output [1:0] vfa2135
);
 wire [0:1] w0;
 wire w1;
 wire [0:1] w2;
 assign w0 = v6a6ead;
 assign w1 = v76af38;
 assign vfa2135 = w2;
 v945b25_vce9fab vce9fab (
  .a(w0),
  .b(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND-2-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Habilitación de bus de 2 bits
/*-------------------------------------------------*/

module v945b25_vce9fab (
 input [1:0] a,
 input b,
 output [1:0] o
);
 assign o[0] = a[0] & b;
 assign o[1] = a[1] & b;
endmodule
//---- Top entity
module vd3fb4e #(
 parameter vfffc23 = 1
) (
 output [1:0] v2978f0
);
 localparam p1 = vfffc23;
 wire [0:1] w0;
 assign v2978f0 = w0;
 v157753 #(
  .vc5c8ea(p1)
 ) v335745 (
  .v4ffce0(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_1_2bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 1 para bus de 2 bits
/*-------------------------------------------------*/
//---- Top entity
module vd4bd04 (
 input vee8a83,
 input v03aaf0,
 output [1:0] v67a3fc
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign v67a3fc = w2;
 vd4bd04_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 2 cables en un bus de 2-bits
/*-------------------------------------------------*/

module vd4bd04_v9a2a06 (
 input i1,
 input i0,
 output [1:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v7107c6 (
 input [7:0] v595263,
 output [7:2] ve83d32,
 output v2c4c48,
 output v2b13a4
);
 wire [0:7] w0;
 wire w1;
 wire w2;
 wire [0:5] w3;
 assign w0 = v595263;
 assign v2c4c48 = w1;
 assign v2b13a4 = w2;
 assign ve83d32 = w3;
 v7107c6_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2),
  .o2(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus-6-1-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 8-bits en 1 buses de 6 bits y dos cables sueltos
/*-------------------------------------------------*/

module v7107c6_v9a2a06 (
 input [7:0] i,
 output [7:2] o2,
 output o1,
 output o0
);
 assign o2 = i[7:2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v67b82c #(
 parameter v27a8d5 = "v27a8d5.list",
 parameter vd2e60e = "vd2e60e.list"
) (
 input v919ee7,
 input [7:0] v8cc488,
 output [31:0] v92d32d,
 output [31:0] v8ff487,
 output [7:0] v72dc50,
 output [7:0] v575022
);
 localparam p6 = v27a8d5;
 localparam p12 = vd2e60e;
 wire w0;
 wire w1;
 wire [0:7] w2;
 wire [0:1] w3;
 wire w4;
 wire w5;
 wire [0:7] w7;
 wire [0:7] w8;
 wire [0:7] w9;
 wire [0:7] w10;
 wire [0:7] w11;
 wire [0:31] w13;
 wire [0:31] w14;
 wire [0:7] w15;
 wire [0:7] w16;
 wire [0:7] w17;
 wire w18;
 wire [0:31] w19;
 wire [0:31] w20;
 wire [0:4] w21;
 wire [0:4] w22;
 wire [0:3] w23;
 wire [0:3] w24;
 wire [0:7] w25;
 wire [0:4] w26;
 wire [0:4] w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 wire w34;
 wire w35;
 wire [0:7] w36;
 wire [0:31] w37;
 wire [0:31] w38;
 wire [0:7] w39;
 wire [0:7] w40;
 wire w41;
 wire w42;
 wire w43;
 wire w44;
 wire w45;
 assign v72dc50 = w36;
 assign v92d32d = w37;
 assign v8ff487 = w38;
 assign w39 = v8cc488;
 assign v575022 = w40;
 assign w41 = v919ee7;
 assign w42 = v919ee7;
 assign w43 = v919ee7;
 assign w44 = v919ee7;
 assign w45 = v919ee7;
 assign w15 = w11;
 assign w16 = w10;
 assign w19 = w13;
 assign w20 = w14;
 assign w36 = w7;
 assign w37 = w13;
 assign w37 = w19;
 assign w38 = w14;
 assign w38 = w20;
 assign w42 = w41;
 assign w43 = w41;
 assign w43 = w42;
 assign w44 = w41;
 assign w44 = w42;
 assign w44 = w43;
 assign w45 = w41;
 assign w45 = w42;
 assign w45 = w43;
 assign w45 = w44;
 v05e8eb #(
  .v5a4ee6(p12)
 ) v45c5c8 (
  .v23dc54(w4),
  .va136b0(w5),
  .vba32a6(w8),
  .v157610(w9),
  .vcc2c4f(w11),
  .v922e3d(w18)
 );
 v05e8eb #(
  .v5a4ee6(p6)
 ) vcf223b (
  .v23dc54(w0),
  .va136b0(w1),
  .vcc2c4f(w2),
  .vba32a6(w7),
  .v157610(w17),
  .v922e3d(w45)
 );
 v21cfcc v2579ea (
  .v9fb85f(w0)
 );
 v725b7e v5d9e3c (
  .v9fb85f(w1)
 );
 v3bf99b vb80b32 (
  .vb096dc(w2)
 );
 v7404e6 v0ef5e7 (
  .vd7d1f4(w3),
  .v595263(w10)
 );
 vfc9dac v3c0180 (
  .v8b19dd(w3),
  .v3f8943(w4),
  .v64d863(w5)
 );
 v6f058b v0591fa (
  .v2ebc76(w19)
 );
 v96f098 v90bf86 (
  .vcbab45(w18),
  .v0e28cb(w43)
 );
 v6f058b v344276 (
  .v2ebc76(w20),
  .v4a41db(w40)
 );
 v19932d v329735 (
  .vfc5572(w7),
  .v21ec4d(w8),
  .v7c37d9(w9),
  .vfd9d0f(w10),
  .ve6d7e4(w11),
  .v234fbd(w13),
  .v1bfd13(w14)
 );
 v53e049 vd9a295 (
  .v961ee9(w13),
  .vd115bb(w14),
  .vbfdb97(w15),
  .vc2ef4f(w16),
  .v84ec18(w17),
  .v19261f(w25),
  .v78b22f(w44)
 );
 vfecebd vb0e791 (
  .v825bba(w22),
  .vc8abec(w27),
  .v717e81(w41)
 );
 vfecebd vdbafef (
  .v825bba(w21),
  .vc8abec(w26),
  .v717e81(w42)
 );
 v96c459 v1bce48 (
  .va69925(w21),
  .vca2ec8(w24)
 );
 v96c459 v0f87f2 (
  .va69925(w22),
  .vca2ec8(w23)
 );
 v78e2e0 v876930 (
  .ve80e46(w26),
  .va67d83(w28),
  .v03635b(w29),
  .v21c02e(w30),
  .vc5775e(w31)
 );
 v917222 vaa35b4 (
  .v285646(w23),
  .v766044(w24),
  .va191ad(w25)
 );
 v78e2e0 v5201dd (
  .ve80e46(w27),
  .va67d83(w32),
  .v03635b(w33),
  .v21c02e(w34),
  .vc5775e(w35)
 );
 vbc6704 v2f75e2 (
  .v45ab8c(w28),
  .vb85197(w29),
  .v8f149e(w30),
  .v7c37b3(w31),
  .ve0c1b4(w32),
  .v2c9812(w33),
  .v7ada3f(w34),
  .vc85478(w35),
  .v595263(w39)
 );
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v05e8eb #(
 parameter v5a4ee6 = "v5a4ee6.list"
) (
 input v922e3d,
 input [7:0] v157610,
 input [7:0] vcc2c4f,
 input v23dc54,
 input va136b0,
 output [7:0] vba32a6
);
 localparam p5 = v5a4ee6;
 wire [0:7] w0;
 wire [0:7] w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:7] w6;
 assign vba32a6 = w0;
 assign w1 = vcc2c4f;
 assign w2 = v922e3d;
 assign w3 = va136b0;
 assign w4 = v23dc54;
 assign w6 = v157610;
 v05e8eb_vbaa912 #(
  .ROMF(p5)
 ) vbaa912 (
  .data_out(w0),
  .data_in(w1),
  .clk(w2),
  .cs(w3),
  .wr(w4),
  .addr(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- Memory-256B  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 256 bytes memory
/*-------------------------------------------------*/

module v05e8eb_vbaa912 #(
 parameter ROMF = 0
) (
 input clk,
 input [7:0] addr,
 input [7:0] data_in,
 input wr,
 input cs,
 output [7:0] data_out
);
 //-- Anchura del bus de direcciones
 localparam ADDR_WIDTH = 8;
 
 //-- Tamano de la memoria
 localparam TAM = 1 << ADDR_WIDTH;
 
 //-- NO inicializar!
 //-- Si se inicializa a 0 o cualquier otro
 //-- valor no se infiere una RAM
 reg data_out;
 
 //-- Array para la memoria
 reg [7:0] mem_8 [0:TAM-1];
 
 //-- Puerto de lectura
 //-- Para que se infiera una RAM
 //-- debe ser una lectura sincrona
 always @(posedge clk)
 begin
     //-- Puerto de lectura
     if (cs & !wr) data_out <= mem_8[addr];
     
     //-- Puerto de escritura
     if (cs & wr) mem_8[addr] <= data_in;
 end
 
 
 //-- Inicializacion de la memoria
 initial begin
   
   if (ROMF)
     $readmemh(ROMF, mem_8, 0, TAM-1);
   
 end
 
 
 
 
endmodule
//---- Top entity
module v725b7e (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v725b7e_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 1
/*-------------------------------------------------*/

module v725b7e_vb2eccd (
 output q
);
 //-- Bit constante a 1
 assign q = 1'b1;
 
 
endmodule
//---- Top entity
module v3bf99b #(
 parameter vfffc23 = 0
) (
 output [7:0] vb096dc
);
 localparam p0 = vfffc23;
 wire [0:7] w1;
 assign vb096dc = w1;
 v5ad97e #(
  .vc5c8ea(p0)
 ) v68b2cc (
  .v26dbdb(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_0_8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 0 para bus de 8 bits
/*-------------------------------------------------*/
//---- Top entity
module v5ad97e #(
 parameter vc5c8ea = 0
) (
 output [7:0] v26dbdb
);
 localparam p0 = vc5c8ea;
 wire [0:7] w1;
 assign v26dbdb = w1;
 v5ad97e_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Constante-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor genérico constante, de 8 bits. Su valor se introduce como parámetro. Por defecto vale 0
/*-------------------------------------------------*/

module v5ad97e_v465065 #(
 parameter VALUE = 0
) (
 output [7:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module v7404e6 (
 input [7:0] v595263,
 output [1:0] vd7d1f4,
 output [5:0] v4ce39b
);
 wire [0:7] w0;
 wire [0:1] w1;
 wire [0:5] w2;
 assign w0 = v595263;
 assign vd7d1f4 = w1;
 assign v4ce39b = w2;
 v7404e6_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus-2-6  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 8-bits en 2 buses de 2 y 6 bits
/*-------------------------------------------------*/

module v7404e6_v9a2a06 (
 input [7:0] i,
 output [1:0] o1,
 output [5:0] o0
);
 assign o1 = i[7:6];
 assign o0 = i[5:0];
endmodule
//---- Top entity
module v96f098 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v96f098_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOT  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- NOT logic gate
/*-------------------------------------------------*/

module v96f098_vd54ca1 (
 input a,
 output c
);
 // NOT logic gate
 
 assign c = ~ a;
endmodule
//---- Top entity
module v19932d #(
 parameter v7dcc91 = 44,
 parameter vc7e15e = 16,
 parameter vcb8c66 = 16,
 parameter v9ba8e8 = 0,
 parameter vb4c034 = 32,
 parameter v4ecf88 = 80,
 parameter v70f00e = 192,
 parameter v824f7d = 16,
 parameter v76b36f = 36
) (
 input [31:0] v234fbd,
 input [31:0] v1bfd13,
 input [7:0] vfc5572,
 input [7:0] v21ec4d,
 output [7:0] ve6d7e4,
 output [7:0] vfd9d0f,
 output [7:0] v7c37d9
);
 localparam p25 = vb4c034;
 localparam p26 = v4ecf88;
 localparam p27 = v70f00e;
 localparam p31 = v824f7d;
 localparam p39 = vcb8c66;
 localparam p43 = v7dcc91;
 localparam p44 = vc7e15e;
 localparam p47 = v76b36f;
 localparam p50 = v9ba8e8;
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:6] w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire [0:7] w10;
 wire [0:3] w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire [0:7] w20;
 wire [0:7] w21;
 wire [0:7] w22;
 wire [0:7] w23;
 wire [0:7] w24;
 wire [0:7] w28;
 wire [0:7] w29;
 wire [0:7] w30;
 wire [0:7] w32;
 wire [0:7] w33;
 wire [0:7] w34;
 wire [0:7] w35;
 wire [0:7] w36;
 wire [0:7] w37;
 wire [0:7] w38;
 wire [0:7] w40;
 wire [0:7] w41;
 wire w42;
 wire [0:7] w45;
 wire [0:7] w46;
 wire [0:7] w48;
 wire [0:7] w49;
 wire [0:7] w51;
 wire [0:2] w52;
 wire [0:7] w53;
 wire [0:31] w54;
 wire [0:31] w55;
 wire [0:1] w56;
 wire [0:1] w57;
 wire [0:5] w58;
 wire w59;
 wire [0:6] w60;
 wire w61;
 wire w62;
 wire w63;
 wire w64;
 wire [0:7] w65;
 wire [0:7] w66;
 wire [0:7] w67;
 wire [0:7] w68;
 wire [0:7] w69;
 wire [0:7] w70;
 wire [0:7] w71;
 wire [0:7] w72;
 wire [0:7] w73;
 wire [0:7] w74;
 wire [0:7] w75;
 wire [0:7] w76;
 wire [0:7] w77;
 wire [0:7] w78;
 wire [0:7] w79;
 wire [0:7] w80;
 wire [0:7] w81;
 wire [0:7] w82;
 wire [0:7] w83;
 wire [0:7] w84;
 wire [0:7] w85;
 wire [0:7] w86;
 wire [0:7] w87;
 wire [0:7] w88;
 wire [0:7] w89;
 wire [0:7] w90;
 wire [0:7] w91;
 wire [0:7] w92;
 wire [0:7] w93;
 wire [0:7] w94;
 wire [0:7] w95;
 wire [0:7] w96;
 wire [0:7] w97;
 wire [0:7] w98;
 wire [0:7] w99;
 wire [0:7] w100;
 wire [0:3] w101;
 wire [0:3] w102;
 wire [0:3] w103;
 wire [0:3] w104;
 wire [0:3] w105;
 wire [0:3] w106;
 wire [0:7] w107;
 wire [0:7] w108;
 wire [0:7] w109;
 wire [0:7] w110;
 assign w21 = vfc5572;
 assign ve6d7e4 = w22;
 assign vfd9d0f = w53;
 assign w54 = v234fbd;
 assign w55 = v1bfd13;
 assign w73 = v21ec4d;
 assign v7c37d9 = w78;
 assign w7 = w4;
 assign w8 = w4;
 assign w8 = w7;
 assign w9 = w5;
 assign w12 = w5;
 assign w12 = w9;
 assign w14 = w4;
 assign w14 = w7;
 assign w14 = w8;
 assign w16 = w6;
 assign w18 = w17;
 assign w19 = w17;
 assign w19 = w18;
 assign w23 = w20;
 assign w30 = w24;
 assign w33 = w32;
 assign w34 = w32;
 assign w34 = w33;
 assign w35 = w32;
 assign w35 = w33;
 assign w35 = w34;
 assign w36 = w32;
 assign w36 = w33;
 assign w36 = w34;
 assign w36 = w35;
 assign w37 = w32;
 assign w37 = w33;
 assign w37 = w34;
 assign w37 = w35;
 assign w37 = w36;
 assign w38 = w32;
 assign w38 = w33;
 assign w38 = w34;
 assign w38 = w35;
 assign w38 = w36;
 assign w38 = w37;
 assign w64 = w42;
 assign w66 = w65;
 assign w67 = w65;
 assign w67 = w66;
 assign w68 = w65;
 assign w68 = w66;
 assign w68 = w67;
 assign w69 = w65;
 assign w69 = w66;
 assign w69 = w67;
 assign w69 = w68;
 assign w70 = w65;
 assign w70 = w66;
 assign w70 = w67;
 assign w70 = w68;
 assign w70 = w69;
 assign w71 = w65;
 assign w71 = w66;
 assign w71 = w67;
 assign w71 = w68;
 assign w71 = w69;
 assign w71 = w70;
 assign w72 = w65;
 assign w72 = w66;
 assign w72 = w67;
 assign w72 = w68;
 assign w72 = w69;
 assign w72 = w70;
 assign w72 = w71;
 assign w75 = w74;
 assign w76 = w74;
 assign w76 = w75;
 assign w77 = w74;
 assign w77 = w75;
 assign w77 = w76;
 assign w78 = w74;
 assign w78 = w75;
 assign w78 = w76;
 assign w78 = w77;
 assign w79 = w74;
 assign w79 = w75;
 assign w79 = w76;
 assign w79 = w77;
 assign w79 = w78;
 assign w80 = w74;
 assign w80 = w75;
 assign w80 = w76;
 assign w80 = w77;
 assign w80 = w78;
 assign w80 = w79;
 assign w81 = w74;
 assign w81 = w75;
 assign w81 = w76;
 assign w81 = w77;
 assign w81 = w78;
 assign w81 = w79;
 assign w81 = w80;
 assign w82 = w74;
 assign w82 = w75;
 assign w82 = w76;
 assign w82 = w77;
 assign w82 = w78;
 assign w82 = w79;
 assign w82 = w80;
 assign w82 = w81;
 assign w90 = w89;
 assign w91 = w89;
 assign w91 = w90;
 assign w92 = w89;
 assign w92 = w90;
 assign w92 = w91;
 assign w93 = w89;
 assign w93 = w90;
 assign w93 = w91;
 assign w93 = w92;
 assign w102 = w101;
 assign w104 = w103;
 assign w105 = w103;
 assign w105 = w104;
 assign w106 = w103;
 assign w106 = w104;
 assign w106 = w105;
 assign w110 = w109;
 v36136f v2c9959 (
  .v593755(w67),
  .v5be714(w76),
  .vd006e6(w100)
 );
 v323be2 v8bf8fe (
  .v3515d4(w0),
  .v9bea93(w66)
 );
 v7d7474 vb06c37 (
  .ve41da3(w0),
  .v9c083a(w1)
 );
 v36136f vf52c15 (
  .v593755(w1),
  .v5be714(w75),
  .vd006e6(w98)
 );
 v85651a vc31643 (
  .vc96239(w69),
  .vea7b5b(w79),
  .v274c22(w95)
 );
 v323be2 v760dc4 (
  .v9bea93(w2),
  .v3515d4(w94)
 );
 v85651a vd0cd61 (
  .v274c22(w2),
  .vc96239(w68),
  .vea7b5b(w77)
 );
 vaf6fc9 v7d8ceb (
  .vb61f66(w60),
  .va191ad(w87)
 );
 v6348d5 v2201b2 (
  .vcff9d0(w3),
  .v869a97(w88)
 );
 vc80943 va17d28 (
  .v1ec852(w3),
  .v595263(w90)
 );
 v27fd6d vb1a3a7 (
  .v18e78c(w5),
  .v9f69ad(w71),
  .v9892c7(w81)
 );
 va21ae0 v538e54 (
  .v18e78c(w4),
  .v40cb98(w70),
  .v4145bb(w80)
 );
 v24496a v75955a (
  .v0e28cb(w4),
  .v3ca442(w5),
  .vcbab45(w6)
 );
 v528969 v7d7539 (
  .v0e28cb(w6),
  .v3ca442(w7),
  .vcbab45(w15)
 );
 v528969 v7e0594 (
  .v0e28cb(w8),
  .v3ca442(w9),
  .vcbab45(w13)
 );
 v36136f v90000b (
  .v593755(w10),
  .v5be714(w89),
  .vd006e6(w97)
 );
 v917222 vd81517 (
  .va191ad(w10),
  .v285646(w11),
  .v766044(w103)
 );
 va0b8df ve9245a (
  .va50a91(w11)
 );
 v7263b9 v74e9a4 (
  .v737e15(w12),
  .vf0dd0a(w13),
  .v15c355(w14),
  .v1b2099(w15),
  .ve5ee9d(w16),
  .v7fcaae(w17),
  .v858373(w18),
  .v21d803(w19),
  .va191ad(w83)
 );
 v21cfcc v214df7 (
  .v9fb85f(w17)
 );
 v49d51e vd141a5 (
  .vbdd51f(w20),
  .v3fb88b(w22),
  .vb4ed69(w23),
  .vd48707(w65),
  .vb6bab2(w73),
  .v3f3f35(w74),
  .vcd2a33(w83),
  .v31c944(w85),
  .v06410a(w86),
  .v71c62f(w87),
  .va541fd(w88),
  .v9b8a50(w94),
  .v30db33(w95),
  .v21e136(w97),
  .v062092(w98),
  .v3d1227(w100),
  .ve81325(w101)
 );
 v3bf99b vb4fc85 (
  .vb096dc(w20)
 );
 v73403c v068e8c (
  .v595263(w21),
  .vf9119c(w101),
  .v85accc(w103)
 );
 v70125e vfcd93f (
  .ve57f84(w56),
  .v21e136(w72),
  .v062092(w82),
  .vbdd51f(w84),
  .v3fb88b(w86),
  .v3d1227(w92)
 );
 v18cbcb v5bc727 (
  .v0daf7d(w56),
  .v735395(w57),
  .v930b03(w104)
 );
 v49d51e v325b10 (
  .vcd2a33(w24),
  .vb6bab2(w28),
  .vd48707(w29),
  .vb4ed69(w30),
  .v3d1227(w32),
  .v062092(w33),
  .v21e136(w34),
  .v30db33(w35),
  .v9b8a50(w36),
  .va541fd(w37),
  .v71c62f(w38),
  .v3fb88b(w53),
  .ve81325(w102),
  .v3f3f35(w107),
  .v31c944(w108),
  .v06410a(w109),
  .vbdd51f(w110)
 );
 v5ad97e #(
  .vc5c8ea(p25)
 ) v04d8fd (
  .v26dbdb(w24)
 );
 v5ad97e #(
  .vc5c8ea(p26)
 ) v4cc0bc (
  .v26dbdb(w28)
 );
 v5ad97e #(
  .vc5c8ea(p27)
 ) vf72751 (
  .v26dbdb(w29)
 );
 v5ad97e #(
  .vc5c8ea(p31)
 ) v32e16a (
  .v26dbdb(w32)
 );
 v5ad97e #(
  .vc5c8ea(p39)
 ) v8898d4 (
  .v26dbdb(w41)
 );
 v9f8856 ve26ac1 (
  .va191ad(w40),
  .v276bb9(w57)
 );
 vd63ed5 v7cd2a6 (
  .vea7b5b(w40),
  .vc96239(w41),
  .v274c22(w109)
 );
 v147de6 v17015d (
  .v9ffacd(w42),
  .v930b03(w105)
 );
 v359a55 v44a780 (
  .v50d6c6(w42),
  .vf24dba(w85),
  .v02d898(w93),
  .vd6b984(w96)
 );
 v359a55 ve65d04 (
  .vd6b984(w45),
  .v02d898(w46),
  .v50d6c6(w64),
  .vf24dba(w108)
 );
 v5ad97e #(
  .vc5c8ea(p43)
 ) v38cf94 (
  .v26dbdb(w46)
 );
 v5ad97e #(
  .vc5c8ea(p44)
 ) vca1782 (
  .v26dbdb(w45)
 );
 v5ad97e #(
  .vc5c8ea(p47)
 ) v2438f7 (
  .v26dbdb(w51)
 );
 v448035 v2610ac (
  .v84546f(w48),
  .v31c84d(w52)
 );
 v85651a vd41a3f (
  .vc96239(w48),
  .v274c22(w49),
  .vea7b5b(w99)
 );
 v10466b #(
  .v16d6b8(p50)
 ) vfb5f49 (
  .v633638(w49),
  .v18e78c(w62)
 );
 vdc50be v2ac06e (
  .vea7b5b(w51),
  .v76af38(w63),
  .v274c22(w107)
 );
 v30a3ea v00f83d (
  .vf96989(w52),
  .v9ffacd(w61),
  .v930b03(w106)
 );
 v6f058b v240f1c (
  .v2ebc76(w54),
  .v0d81e4(w65),
  .v6b375c(w74),
  .v4a41db(w84),
  .vd65308(w89)
 );
 v6f058b ve0edfa (
  .v2ebc76(w55),
  .v0d81e4(w96),
  .vd65308(w99)
 );
 ve493b2 v544c21 (
 
 );
 v7107c6 vb2a685 (
  .ve83d32(w58),
  .v2c4c48(w59),
  .v595263(w91)
 );
 v80fc29 v4ea14d (
  .vf39709(w58),
  .v14ddcc(w59),
  .v1a0366(w60)
 );
 v816138 vf03905 (
  .v3ca442(w61),
  .v0e28cb(w62),
  .vcbab45(w63)
 );
endmodule

/*-------------------------------------------------*/
/*-- alu1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v36136f (
 input [7:0] v5be714,
 input [7:0] v593755,
 output v654087,
 output [7:0] vd006e6
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 assign v654087 = w0;
 assign w1 = v593755;
 assign vd006e6 = w2;
 assign w3 = v5be714;
 v36136f_va0c26a va0c26a (
  .c(w0),
  .b(w1),
  .s(w2),
  .a(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- sum-2p-8bits-carry  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sumador  de 8 bits, con acarreo
/*-------------------------------------------------*/

module v36136f_va0c26a (
 input [7:0] a,
 input [7:0] b,
 output c,
 output [7:0] s
);
 wire [8:0] temp;
 assign temp = {1'b0, a} + {1'b0, b};
 assign s = temp[7:0];
 assign c = temp[8];
 //--test
endmodule
//---- Top entity
module v323be2 (
 input [7:0] v9bea93,
 output [7:0] v3515d4
);
 wire [0:7] w0;
 wire [0:7] w1;
 assign w0 = v9bea93;
 assign v3515d4 = w1;
 v323be2_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOT-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta NOT para bus de 8 bits
/*-------------------------------------------------*/

module v323be2_vd54ca1 (
 input [7:0] a,
 output [7:0] c
);
 //-- Puerta NOT
 
 //-- module (input wire a, output wire c);
 
 
 assign c = ~a;
 
 
 //-- endmodule
 
endmodule
//---- Top entity
module v7d7474 #(
 parameter v8d305c = 1
) (
 input [7:0] ve41da3,
 output [7:0] v9c083a
);
 localparam p0 = v8d305c;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w1 = ve41da3;
 assign v9c083a = w2;
 v7d7474_va0c26a #(
  .k(p0)
 ) va0c26a (
  .a(w1),
  .s(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- sum-1op-8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sumador de un operando de 8 bits con una constante pasada como parámetro (No hay accarreo)
/*-------------------------------------------------*/

module v7d7474_va0c26a #(
 parameter k = 0
) (
 input [7:0] a,
 output [7:0] s
);
 assign s = a + k;
endmodule
//---- Top entity
module v85651a (
 input [7:0] vea7b5b,
 input [7:0] vc96239,
 output [7:0] v274c22
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w0 = vea7b5b;
 assign v274c22 = w1;
 assign w2 = vc96239;
 v85651a_vce9fab vce9fab (
  .a(w0),
  .o(w1),
  .b(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND-8  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- AND bit a bit entre dos buses de 8 bits
/*-------------------------------------------------*/

module v85651a_vce9fab (
 input [7:0] a,
 input [7:0] b,
 output [7:0] o
);
 assign o = a & b;
 
endmodule
//---- Top entity
module vaf6fc9 (
 input v4ef985,
 input [6:0] vb61f66,
 output [7:0] va191ad
);
 wire [0:6] w0;
 wire w1;
 wire [0:7] w2;
 assign w0 = vb61f66;
 assign w1 = v4ef985;
 assign va191ad = w2;
 vaf6fc9_v9a2a06 v9a2a06 (
  .i0(w0),
  .i1(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 1 cable y un bus de 7-bits a bus de 8-bits
/*-------------------------------------------------*/

module vaf6fc9_v9a2a06 (
 input i1,
 input [6:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v6348d5 (
 input [6:0] vcff9d0,
 input v428b2b,
 output [7:0] v869a97
);
 wire [0:6] w0;
 wire w1;
 wire [0:7] w2;
 assign w0 = vcff9d0;
 assign w1 = v428b2b;
 assign v869a97 = w2;
 v6348d5_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de un bus de 7 bits y un cable a bus de 8-bits
/*-------------------------------------------------*/

module v6348d5_v9a2a06 (
 input [6:0] i1,
 input i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module vc80943 (
 input [7:0] v595263,
 output v57076f,
 output [6:0] v1ec852
);
 wire [0:7] w0;
 wire w1;
 wire [0:6] w2;
 assign w0 = v595263;
 assign v57076f = w1;
 assign v1ec852 = w2;
 vc80943_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus-1-7  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 8-bits en 2 buses de 1 y 7 bits
/*-------------------------------------------------*/

module vc80943_v9a2a06 (
 input [7:0] i,
 output o1,
 output [6:0] o0
);
 assign o1 = i[7];
 assign o0 = i[6:0];
endmodule
//---- Top entity
module v27fd6d (
 input [7:0] v9892c7,
 input [7:0] v9f69ad,
 output v18e78c
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign v18e78c = w0;
 assign w1 = v9f69ad;
 assign w2 = v9892c7;
 v27fd6d_vd75681 vd75681 (
  .eq(w0),
  .b(w1),
  .a(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Menor-que-2-op  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comparador menor que, de dos operandos de 8 bits
/*-------------------------------------------------*/

module v27fd6d_vd75681 (
 input [7:0] a,
 input [7:0] b,
 output eq
);
 assign eq = (a < b);
endmodule
//---- Top entity
module va21ae0 (
 input [7:0] v4145bb,
 input [7:0] v40cb98,
 output v18e78c
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign v18e78c = w0;
 assign w1 = v40cb98;
 assign w2 = v4145bb;
 va21ae0_vd75681 vd75681 (
  .eq(w0),
  .b(w1),
  .a(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Comparador de dos operandos  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comparador de dos operandos de 8 bits
/*-------------------------------------------------*/

module va21ae0_vd75681 (
 input [7:0] a,
 input [7:0] b,
 output eq
);
 assign eq = (a == b);
endmodule
//---- Top entity
module v24496a (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v24496a_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOR  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- NOR logic gate
/*-------------------------------------------------*/

module v24496a_vf4938a (
 input a,
 input b,
 output c
);
 // NOR logic gate
 
 assign c = ~(a | b);
endmodule
//---- Top entity
module v528969 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v528969_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- OR  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- OR logic gate
/*-------------------------------------------------*/

module v528969_vf4938a (
 input a,
 input b,
 output c
);
 // OR logic gate
 
 assign c = a | b;
endmodule
//---- Top entity
module v917222 (
 input [3:0] v285646,
 input [3:0] v766044,
 output [7:0] va191ad
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 assign w0 = v766044;
 assign w1 = v285646;
 assign va191ad = w2;
 v917222_v9a2a06 v9a2a06 (
  .i0(w0),
  .i1(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 2 buses de 4-bits a bus de 8-bits
/*-------------------------------------------------*/

module v917222_v9a2a06 (
 input [3:0] i1,
 input [3:0] i0,
 output [7:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module va0b8df #(
 parameter vfffc23 = 0
) (
 output [3:0] va50a91
);
 localparam p0 = vfffc23;
 wire [0:3] w1;
 assign va50a91 = w1;
 v9274d3 #(
  .vc5c8ea(p0)
 ) v8800c6 (
  .v00a92d(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_0_4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 0 para bus de 4 bits
/*-------------------------------------------------*/
//---- Top entity
module v9274d3 #(
 parameter vc5c8ea = 0
) (
 output [3:0] v00a92d
);
 localparam p1 = vc5c8ea;
 wire [0:3] w0;
 assign v00a92d = w0;
 v9274d3_v465065 #(
  .VALUE(p1)
 ) v465065 (
  .k(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- Constante-4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor genérico constante, de 4 bits. Su valor se introduce como parámetro. Por defecto vale 0
/*-------------------------------------------------*/

module v9274d3_v465065 #(
 parameter VALUE = 0
) (
 output [3:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module v7263b9 (
 input v7fcaae,
 input v858373,
 input v21d803,
 input ve5ee9d,
 input v1b2099,
 input v15c355,
 input vf0dd0a,
 input v737e15,
 output [7:0] va191ad
);
 wire [0:7] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 assign va191ad = w0;
 assign w1 = v7fcaae;
 assign w2 = v858373;
 assign w3 = v21d803;
 assign w4 = ve5ee9d;
 assign w5 = v1b2099;
 assign w6 = v15c355;
 assign w7 = vf0dd0a;
 assign w8 = v737e15;
 v7263b9_v9a2a06 v9a2a06 (
  .o(w0),
  .i7(w1),
  .i6(w2),
  .i5(w3),
  .i4(w4),
  .i3(w5),
  .i2(w6),
  .i1(w7),
  .i0(w8)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 8 cables de 1-bit a bus de 8-bits
/*-------------------------------------------------*/

module v7263b9_v9a2a06 (
 input i7,
 input i6,
 input i5,
 input i4,
 input i3,
 input i2,
 input i1,
 input i0,
 output [7:0] o
);
 assign o = {i7, i6, i5, i4, i3, i2, i1, i0};
 
endmodule
//---- Top entity
module v49d51e (
 input [7:0] v732d31,
 input [7:0] vb4ed69,
 input [7:0] vd48707,
 input [7:0] vb6bab2,
 input [7:0] v3f3f35,
 input [7:0] vcd2a33,
 input [7:0] v31c944,
 input [7:0] v06410a,
 input [7:0] v71c62f,
 input [7:0] va541fd,
 input [7:0] v9b8a50,
 input [7:0] v30db33,
 input [7:0] vbdd51f,
 input [7:0] v21e136,
 input [7:0] v062092,
 input [7:0] v3d1227,
 input [3:0] ve81325,
 output [7:0] v3fb88b
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:7] w5;
 wire [0:7] w6;
 wire [0:7] w7;
 wire [0:7] w8;
 wire [0:7] w9;
 wire [0:7] w10;
 wire [0:7] w11;
 wire [0:7] w12;
 wire [0:7] w13;
 wire [0:7] w14;
 wire [0:7] w15;
 wire [0:7] w16;
 wire [0:3] w17;
 assign v3fb88b = w0;
 assign w1 = v062092;
 assign w2 = v3d1227;
 assign w3 = v21e136;
 assign w4 = vbdd51f;
 assign w5 = v30db33;
 assign w6 = v71c62f;
 assign w7 = va541fd;
 assign w8 = v9b8a50;
 assign w9 = v06410a;
 assign w10 = v31c944;
 assign w11 = vcd2a33;
 assign w12 = v3f3f35;
 assign w13 = vb6bab2;
 assign w14 = vd48707;
 assign w15 = vb4ed69;
 assign w16 = v732d31;
 assign w17 = ve81325;
 v49d51e_ve4e0df ve4e0df (
  .o(w0),
  .i1(w1),
  .i0(w2),
  .i2(w3),
  .i3(w4),
  .i4(w5),
  .i7(w6),
  .i6(w7),
  .i5(w8),
  .i8(w9),
  .i9(w10),
  .i10(w11),
  .i11(w12),
  .i12(w13),
  .i13(w14),
  .i14(w15),
  .i15(w16),
  .s(w17)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux-16-1- 8bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 16 a 1 de 8 bits
/*-------------------------------------------------*/

module v49d51e_ve4e0df (
 input [7:0] i15,
 input [7:0] i14,
 input [7:0] i13,
 input [7:0] i12,
 input [7:0] i11,
 input [7:0] i10,
 input [7:0] i9,
 input [7:0] i8,
 input [7:0] i7,
 input [7:0] i6,
 input [7:0] i5,
 input [7:0] i4,
 input [7:0] i3,
 input [7:0] i2,
 input [7:0] i1,
 input [7:0] i0,
 input [3:0] s,
 output [7:0] o
);
 //-- Multiplexor de 16 a 1, 
 //-- de 8 bits
 
 assign o = (s == 4'h0) ? i0 :
            (s == 4'h1) ? i1 :
            (s == 4'h2) ? i2 : 
            (s == 4'h3) ? i3 :
            (s == 4'h4) ? i4 :
            (s == 4'h5) ? i5 :
            (s == 4'h6) ? i6 :
            (s == 4'h7) ? i7 :
            (s == 4'h8) ? i8 :
            (s == 4'h9) ? i9 :
            (s == 4'ha) ? i10 : 
            (s == 4'hb) ? i11 :
            (s == 4'hc) ? i12 :
            (s == 4'hd) ? i13 :
            (s == 4'he) ? i14 :
            (s == 4'hf) ? i15 :
            4'h0;
            
 
 
endmodule
//---- Top entity
module v73403c (
 input [7:0] v595263,
 output [3:0] vf9119c,
 output [3:0] v85accc
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 assign vf9119c = w0;
 assign v85accc = w1;
 assign w2 = v595263;
 v73403c_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 8-bits en buses de 4 bits
/*-------------------------------------------------*/

module v73403c_v9a2a06 (
 input [7:0] i,
 output [3:0] o1,
 output [3:0] o0
);
 assign o1 = i[7:4];
 assign o0 = i[3:0];
endmodule
//---- Top entity
module v70125e (
 input [7:0] vbdd51f,
 input [7:0] v21e136,
 input [7:0] v062092,
 input [7:0] v3d1227,
 input [1:0] ve57f84,
 output [7:0] v3fb88b
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 wire [0:1] w5;
 assign v3fb88b = w0;
 assign w1 = v3d1227;
 assign w2 = v062092;
 assign w3 = v21e136;
 assign w4 = vbdd51f;
 assign w5 = ve57f84;
 v70125e_ve4e0df ve4e0df (
  .o(w0),
  .i0(w1),
  .i1(w2),
  .i2(w3),
  .i3(w4),
  .s(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- 8bits-Mux-4-1-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 4 a 1 de 8 bits
/*-------------------------------------------------*/

module v70125e_ve4e0df (
 input [7:0] i3,
 input [7:0] i2,
 input [7:0] i1,
 input [7:0] i0,
 input [1:0] s,
 output [7:0] o
);
 //-- Multiplexor de 4 a 1, 
 //-- de 8 bits
 
 assign o = (s == 2'b00) ? i0 :
            (s == 2'b01) ? i1 :
            (s == 2'b10) ? i2 : i3;
 
 
endmodule
//---- Top entity
module v18cbcb (
 input [3:0] v930b03,
 output [1:0] v0daf7d,
 output [1:0] v735395
);
 wire [0:1] w0;
 wire [0:1] w1;
 wire [0:3] w2;
 assign v0daf7d = w0;
 assign v735395 = w1;
 assign w2 = v930b03;
 v18cbcb_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 4-bits en buses de 2 bits
/*-------------------------------------------------*/

module v18cbcb_v9a2a06 (
 input [3:0] i,
 output [1:0] o1,
 output [1:0] o0
);
 assign o1 = i[3:2];
 assign o0 = i[1:0];
endmodule
//---- Top entity
module vd63ed5 (
 input [7:0] vea7b5b,
 input [7:0] vc96239,
 output [7:0] v274c22
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w0 = vea7b5b;
 assign v274c22 = w1;
 assign w2 = vc96239;
 vd63ed5_vce9fab vce9fab (
  .a(w0),
  .o(w1),
  .b(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- OR-8  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- OR bit a bit entre dos buses de 8 bits
/*-------------------------------------------------*/

module vd63ed5_vce9fab (
 input [7:0] a,
 input [7:0] b,
 output [7:0] o
);
 assign o = a | b;
 
endmodule
//---- Top entity
module v147de6 (
 input [3:0] v930b03,
 output [2:0] vf96989,
 output v9ffacd
);
 wire [0:3] w0;
 wire [0:2] w1;
 wire w2;
 assign w0 = v930b03;
 assign vf96989 = w1;
 assign v9ffacd = w2;
 v147de6_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 4-bits en bus de 3 bits y cable
/*-------------------------------------------------*/

module v147de6_v9a2a06 (
 input [3:0] i,
 output [2:0] o1,
 output o0
);
 assign o1 = i[3:1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v359a55 (
 input [7:0] v02d898,
 input [7:0] vd6b984,
 input v50d6c6,
 output [7:0] vf24dba
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 assign w0 = v50d6c6;
 assign w1 = vd6b984;
 assign w2 = v02d898;
 assign vf24dba = w3;
 v359a55_ve4e0df ve4e0df (
  .sel(w0),
  .i0(w1),
  .i1(w2),
  .o(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux 2 a 1 de 8 bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 2 a 1 de 8 bits
/*-------------------------------------------------*/

module v359a55_ve4e0df (
 input [7:0] i1,
 input [7:0] i0,
 input sel,
 output [7:0] o
);
 //-- Multiplexor de 2 a 1, 
 //-- de 8 bits
 
 reg [7:0] o;
 
 always @(*) begin
     case(sel)
         0: o = i0;
         1: o = i1;
         default: o = i0;
     endcase
 end
 
 
endmodule
//---- Top entity
module v448035 (
 input [2:0] v31c84d,
 output [7:0] v84546f
);
 wire [0:2] w0;
 wire [0:7] w1;
 assign w0 = v31c84d;
 assign v84546f = w1;
 v448035_v3d7f3a v3d7f3a (
  .y(w0),
  .i(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Decodificador-3-8-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Decodificador de 3 a 8, con salida en bus
/*-------------------------------------------------*/

module v448035_v3d7f3a (
 input [2:0] y,
 output [7:0] i
);
 assign i = 1 << y;
                        
 
endmodule
//---- Top entity
module v10466b #(
 parameter v16d6b8 = 1
) (
 input [7:0] v633638,
 output v18e78c
);
 localparam p1 = v16d6b8;
 wire w0;
 wire [0:7] w2;
 assign v18e78c = w0;
 assign w2 = v633638;
 v10466b_vd75681 #(
  .B(p1)
 ) vd75681 (
  .eq(w0),
  .a(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mayor-que-1-op  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comparador mayor que, de un operando de 8 bits
/*-------------------------------------------------*/

module v10466b_vd75681 #(
 parameter B = 0
) (
 input [7:0] a,
 output eq
);
 assign eq = (a > B);
endmodule
//---- Top entity
module vdc50be (
 input [7:0] vea7b5b,
 input v76af38,
 output [7:0] v274c22
);
 wire w0;
 wire [0:7] w1;
 wire [0:7] w2;
 assign w0 = v76af38;
 assign w1 = vea7b5b;
 assign v274c22 = w2;
 vdc50be_vce9fab vce9fab (
  .b(w0),
  .a(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND-8-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Habilitación de bus de 8 bits
/*-------------------------------------------------*/

module vdc50be_vce9fab (
 input [7:0] a,
 input b,
 output [7:0] o
);
 assign o[0] = a[0] & b;
 assign o[1] = a[1] & b;
 assign o[2] = a[2] & b;
 assign o[3] = a[3] & b;
 assign o[4] = a[4] & b;
 assign o[5] = a[5] & b;
 assign o[6] = a[6] & b;
 assign o[7] = a[7] & b;
endmodule
//---- Top entity
module v30a3ea (
 input [3:0] v930b03,
 output v9ffacd,
 output [2:0] vf96989
);
 wire [0:3] w0;
 wire [0:2] w1;
 wire w2;
 assign w0 = v930b03;
 assign vf96989 = w1;
 assign v9ffacd = w2;
 v30a3ea_v9a2a06 v9a2a06 (
  .i(w0),
  .o0(w1),
  .o1(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus-1-3  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 4-bits en buses de 1 bits y 3 bits
/*-------------------------------------------------*/

module v30a3ea_v9a2a06 (
 input [3:0] i,
 output o1,
 output [2:0] o0
);
 assign o1 = i[3];
 assign o0 = i[2:0];
endmodule
//---- Top entity
module ve493b2 #(
 parameter vaf1d6e = 0
) (
 input [7:0] vdf5b7a,
 input vb6a1db,
 output [7:0] v2cc258
);
 localparam p0 = vaf1d6e;
 wire [0:7] w1;
 wire [0:7] w2;
 wire w3;
 assign w1 = vdf5b7a;
 assign v2cc258 = w2;
 assign w3 = vb6a1db;
 ve493b2_vd80544 #(
  .BIT(p0)
 ) vd80544 (
  .i(w1),
  .o(w2),
  .a(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Insert-1-bit  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Inyectar el valor de un cable por el bit indicado de un bus
/*-------------------------------------------------*/

module ve493b2_vd80544 #(
 parameter BIT = 0
) (
 input [7:0] i,
 input a,
 output [7:0] o
);
 reg [7:0] o;
 
 always @(*) begin
 
  o[7:0] = i[7:0];
  o[BIT] = a;
  
 end
endmodule
//---- Top entity
module v80fc29 (
 input [5:0] vf39709,
 input v14ddcc,
 output [6:0] v1a0366
);
 wire w0;
 wire [0:6] w1;
 wire [0:5] w2;
 assign w0 = v14ddcc;
 assign v1a0366 = w1;
 assign w2 = vf39709;
 v80fc29_v9a2a06 v9a2a06 (
  .i0(w0),
  .o(w1),
  .i1(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- 7bits-bus-joiner-6-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Join a 6-bit bus and 1 one into a 7-bits bus
/*-------------------------------------------------*/

module v80fc29_v9a2a06 (
 input [5:0] i1,
 input i0,
 output [6:0] o
);
 assign o = {i1, i0};
 
endmodule
//---- Top entity
module v816138 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v816138_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- OR  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta OR
/*-------------------------------------------------*/

module v816138_vf4938a (
 input a,
 input b,
 output c
);
 //-- Puerta OR
 
 //-- module and (input wire a, input wire b,
 //--             output wire c);
 
 assign c = a | b;
 
 //-- endmodule
endmodule
//---- Top entity
module v53e049 (
 input [7:0] vbfdb97,
 input [7:0] vc2ef4f,
 input v78b22f,
 input [7:0] v19261f,
 output [31:0] v961ee9,
 output [31:0] vd115bb,
 output [7:0] v84ec18
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire [0:5] w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire [0:3] w14;
 wire [0:3] w15;
 wire [0:1] w16;
 wire [0:1] w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire [0:3] w24;
 wire [0:3] w25;
 wire [0:7] w26;
 wire [0:7] w27;
 wire [0:7] w28;
 wire w29;
 wire w30;
 wire [0:7] w31;
 wire [0:7] w32;
 wire [0:7] w33;
 wire [0:7] w34;
 wire [0:7] w35;
 wire [0:31] w36;
 wire [0:31] w37;
 wire [0:7] w38;
 wire [0:7] w39;
 wire [0:7] w40;
 wire [0:7] w41;
 wire w42;
 wire w43;
 wire [0:7] w44;
 wire w45;
 wire [0:7] w46;
 wire [0:7] w47;
 wire [0:7] w48;
 wire [0:7] w49;
 wire [0:7] w50;
 wire [0:7] w51;
 wire [0:7] w52;
 wire [0:7] w53;
 assign w2 = v78b22f;
 assign w3 = v78b22f;
 assign w4 = v78b22f;
 assign w5 = v78b22f;
 assign w6 = v78b22f;
 assign w7 = v78b22f;
 assign w8 = v78b22f;
 assign w26 = vc2ef4f;
 assign v961ee9 = w36;
 assign vd115bb = w37;
 assign v84ec18 = w41;
 assign w42 = v78b22f;
 assign w44 = v19261f;
 assign w47 = vbfdb97;
 assign w48 = vbfdb97;
 assign w49 = vbfdb97;
 assign w50 = vbfdb97;
 assign w51 = vbfdb97;
 assign w52 = vbfdb97;
 assign w53 = vbfdb97;
 assign w3 = w2;
 assign w4 = w2;
 assign w4 = w3;
 assign w5 = w2;
 assign w5 = w3;
 assign w5 = w4;
 assign w6 = w2;
 assign w6 = w3;
 assign w6 = w4;
 assign w6 = w5;
 assign w7 = w2;
 assign w7 = w3;
 assign w7 = w4;
 assign w7 = w5;
 assign w7 = w6;
 assign w8 = w2;
 assign w8 = w3;
 assign w8 = w4;
 assign w8 = w5;
 assign w8 = w6;
 assign w8 = w7;
 assign w39 = w28;
 assign w41 = w28;
 assign w41 = w39;
 assign w42 = w2;
 assign w42 = w3;
 assign w42 = w4;
 assign w42 = w5;
 assign w42 = w6;
 assign w42 = w7;
 assign w42 = w8;
 assign w48 = w47;
 assign w49 = w47;
 assign w49 = w48;
 assign w50 = w47;
 assign w50 = w48;
 assign w50 = w49;
 assign w51 = w47;
 assign w51 = w48;
 assign w51 = w49;
 assign w51 = w50;
 assign w52 = w47;
 assign w52 = w48;
 assign w52 = w49;
 assign w52 = w50;
 assign w52 = w51;
 assign w53 = w47;
 assign w53 = w48;
 assign w53 = w49;
 assign w53 = w50;
 assign w53 = w51;
 assign w53 = w52;
 v89d234 v00cf70 (
  .v41eb95(w2),
  .vf892a0(w20),
  .vb1c024(w32),
  .v39f831(w47)
 );
 v89d234 v52e8e8 (
  .v41eb95(w3),
  .vf892a0(w21),
  .vb1c024(w33),
  .v39f831(w48)
 );
 v89d234 v3a923a (
  .v41eb95(w4),
  .vf892a0(w22),
  .vb1c024(w34),
  .v39f831(w49)
 );
 v89d234 v5a42b0 (
  .v41eb95(w5),
  .vf892a0(w23),
  .vb1c024(w35),
  .v39f831(w50)
 );
 v89d234 vc3d5eb (
  .vf892a0(w0),
  .v41eb95(w6),
  .vb1c024(w38),
  .v39f831(w51)
 );
 v89d234 v3b4bcb (
  .vb1c024(w28),
  .vf892a0(w29),
  .v39f831(w31),
  .v41eb95(w43)
 );
 v89d234 vdb2ed9 (
  .v41eb95(w7),
  .v39f831(w44),
  .vf892a0(w45),
  .vb1c024(w46)
 );
 v89d234 ve77b64 (
  .vf892a0(w1),
  .v41eb95(w8),
  .vb1c024(w40),
  .v39f831(w53)
 );
 v45c913 v46cbae (
  .v593f43(w0),
  .v5b73e8(w1),
  .v930b03(w25),
  .v2812a7(w30)
 );
 v7404e6 v9184a8 (
  .v4ce39b(w9),
  .v595263(w26)
 );
 vd4bd04 v776aa2 (
  .v03aaf0(w10),
  .vee8a83(w11),
  .v67a3fc(w17)
 );
 vd4bd04 v474d28 (
  .v03aaf0(w12),
  .vee8a83(w13),
  .v67a3fc(w16)
 );
 vfd8998 v289c22 (
  .vbb390a(w9),
  .v45ab8c(w10),
  .vb85197(w11),
  .v8f149e(w12),
  .v7c37b3(w13),
  .ve0c1b4(w18),
  .v2c9812(w19)
 );
 v1c4cc4 va801cf (
  .v9c304b(w15),
  .v827425(w16)
 );
 v13d09a ve0ffcc (
  .vd317b3(w15),
  .v76af38(w19),
  .ve2642f(w25)
 );
 v1c4cc4 va6e1f2 (
  .v9c304b(w14),
  .v827425(w17)
 );
 v13d09a v81f649 (
  .vd317b3(w14),
  .v76af38(w18),
  .ve2642f(w24)
 );
 v45c913 v3f14be (
  .v593f43(w20),
  .v2812a7(w21),
  .vc90115(w22),
  .v5b73e8(w23),
  .v930b03(w24)
 );
 v359a55 ve3d83e (
  .vd6b984(w27),
  .v50d6c6(w30),
  .vf24dba(w31),
  .v02d898(w52)
 );
 v7d7474 v973e98 (
  .v9c083a(w27),
  .ve41da3(w28)
 );
 v725b7e v1dca89 (
  .v9fb85f(w29)
 );
 vb6ddba vc7c352 (
  .v9999de(w32),
  .v63d71a(w33),
  .v32ad8d(w34),
  .v7a6a68(w35),
  .v2eef2f(w36)
 );
 vb6ddba v72b1e4 (
  .v2eef2f(w37),
  .v9999de(w38),
  .v63d71a(w39),
  .v7a6a68(w40),
  .v32ad8d(w46)
 );
 v96f098 v81616d (
  .v0e28cb(w42),
  .vcbab45(w43)
 );
 v725b7e v3dffcc (
  .v9fb85f(w45)
 );
endmodule

/*-------------------------------------------------*/
/*-- reg1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v89d234 #(
 parameter v422d28 = 0
) (
 input v41eb95,
 input [7:0] v39f831,
 input vf892a0,
 output [7:0] vb1c024
);
 localparam p0 = v422d28;
 wire [0:7] w1;
 wire [0:7] w2;
 wire w3;
 wire w4;
 assign vb1c024 = w1;
 assign w2 = v39f831;
 assign w3 = vf892a0;
 assign w4 = v41eb95;
 v89d234_v9148cb #(
  .INI(p0)
 ) v9148cb (
  .q(w1),
  .d(w2),
  .load(w3),
  .clk(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Registro  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Registro de 8 bits
/*-------------------------------------------------*/

module v89d234_v9148cb #(
 parameter INI = 0
) (
 input clk,
 input [7:0] d,
 input load,
 output [7:0] q
);
 localparam N = 8;
 
 reg [N-1:0] q = INI;
 
 always @(posedge clk)
   if (load)
     q <= d;
endmodule
//---- Top entity
module v45c913 (
 input [3:0] v930b03,
 output v5b73e8,
 output vc90115,
 output v2812a7,
 output v593f43
);
 wire [0:3] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v930b03;
 assign v2812a7 = w1;
 assign v593f43 = w2;
 assign vc90115 = w3;
 assign v5b73e8 = w4;
 v45c913_v9a2a06 v9a2a06 (
  .i(w0),
  .o1(w1),
  .o0(w2),
  .o2(w3),
  .o3(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 4-bits en 4 cables
/*-------------------------------------------------*/

module v45c913_v9a2a06 (
 input [3:0] i,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module vfd8998 (
 input [5:0] vbb390a,
 output v2c9812,
 output ve0c1b4,
 output v7c37b3,
 output v8f149e,
 output vb85197,
 output v45ab8c
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:5] w6;
 assign v2c9812 = w0;
 assign ve0c1b4 = w1;
 assign v7c37b3 = w2;
 assign v8f149e = w3;
 assign vb85197 = w4;
 assign v45ab8c = w5;
 assign w6 = vbb390a;
 vfd8998_v9a2a06 v9a2a06 (
  .o5(w0),
  .o4(w1),
  .o3(w2),
  .o2(w3),
  .o1(w4),
  .o0(w5),
  .i(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 6-bits en 6 cables
/*-------------------------------------------------*/

module vfd8998_v9a2a06 (
 input [5:0] i,
 output o5,
 output o4,
 output o3,
 output o2,
 output o1,
 output o0
);
 
 
 assign o5 = i[5];
 assign o4 = i[4];
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v1c4cc4 (
 input [1:0] v827425,
 output [3:0] v9c304b
);
 wire [0:1] w0;
 wire [0:3] w1;
 assign w0 = v827425;
 assign v9c304b = w1;
 v1c4cc4_v3d7f3a v3d7f3a (
  .y(w0),
  .i(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Decodificador-2-4-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Decodificador de 2 a 4, con salida en bus
/*-------------------------------------------------*/

module v1c4cc4_v3d7f3a (
 input [1:0] y,
 output [3:0] i
);
 assign i = 1 << y;
                        
 
endmodule
//---- Top entity
module v13d09a (
 input [3:0] vd317b3,
 input v76af38,
 output [3:0] ve2642f
);
 wire w0;
 wire [0:3] w1;
 wire [0:3] w2;
 assign w0 = v76af38;
 assign w1 = vd317b3;
 assign ve2642f = w2;
 v13d09a_vce9fab vce9fab (
  .b(w0),
  .a(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND-4-1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta AND de dos operandos, de 1 y 4 bits
/*-------------------------------------------------*/

module v13d09a_vce9fab (
 input [3:0] a,
 input b,
 output [3:0] o
);
 assign o[3] = a[3] & b;
 assign o[2] = a[2] & b;
 assign o[1] = a[1] & b;
 assign o[0] = a[0] & b;
endmodule
//---- Top entity
module vb6ddba (
 input [7:0] v7a6a68,
 input [7:0] v32ad8d,
 input [7:0] v63d71a,
 input [7:0] v9999de,
 output [31:0] v2eef2f
);
 wire [0:31] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:7] w3;
 wire [0:7] w4;
 assign v2eef2f = w0;
 assign w1 = v9999de;
 assign w2 = v63d71a;
 assign w3 = v32ad8d;
 assign w4 = v7a6a68;
 vb6ddba_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2),
  .i2(w3),
  .i3(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 4 buses en un bus de 32-bits
/*-------------------------------------------------*/

module vb6ddba_v9a2a06 (
 input [7:0] i3,
 input [7:0] i2,
 input [7:0] i1,
 input [7:0] i0,
 output [31:0] o
);
 assign o = {i3,i2, i1, i0};
 
endmodule
//---- Top entity
module vfecebd (
 input v717e81,
 input [4:0] vc8abec,
 output [4:0] v825bba
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire [0:4] w10;
 wire [0:4] w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 assign v825bba = w10;
 assign w11 = vc8abec;
 assign w12 = v717e81;
 assign w13 = v717e81;
 assign w14 = v717e81;
 assign w15 = v717e81;
 assign w16 = v717e81;
 assign w13 = w12;
 assign w14 = w12;
 assign w14 = w13;
 assign w15 = w12;
 assign w15 = w13;
 assign w15 = w14;
 assign w16 = w12;
 assign w16 = w13;
 assign w16 = w14;
 assign w16 = w15;
 v78e2e0 v138dbf (
  .v21c02e(w5),
  .va67d83(w6),
  .v03635b(w7),
  .vc5775e(w8),
  .v9bdbdb(w9),
  .ve80e46(w10)
 );
 v3bfe20 v015603 (
  .ve7f5e6(w0),
  .v3c12b5(w9),
  .v717e81(w12)
 );
 v3bfe20 v435a65 (
  .ve7f5e6(w2),
  .v3c12b5(w8),
  .v717e81(w13)
 );
 v3bfe20 v7baf33 (
  .ve7f5e6(w1),
  .v3c12b5(w5),
  .v717e81(w14)
 );
 v3bfe20 v636b62 (
  .ve7f5e6(w3),
  .v3c12b5(w7),
  .v717e81(w15)
 );
 v3bfe20 ved5433 (
  .ve7f5e6(w4),
  .v3c12b5(w6),
  .v717e81(w16)
 );
 vc0bd39 v598e13 (
  .vc7a3dc(w0),
  .vc90115(w1),
  .v5b73e8(w2),
  .v2812a7(w3),
  .v593f43(w4),
  .va69925(w11)
 );
endmodule

/*-------------------------------------------------*/
/*-- Sync-bus5  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sincronizar las entradas de datos con el reloj del sistema, en un bus de 5
/*-------------------------------------------------*/
//---- Top entity
module v78e2e0 (
 input v9bdbdb,
 input vc5775e,
 input v21c02e,
 input v03635b,
 input va67d83,
 output [4:0] ve80e46
);
 wire [0:4] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 assign ve80e46 = w0;
 assign w1 = va67d83;
 assign w2 = v03635b;
 assign w3 = v21c02e;
 assign w4 = vc5775e;
 assign w5 = v9bdbdb;
 v78e2e0_v9a2a06 v9a2a06 (
  .o(w0),
  .i0(w1),
  .i1(w2),
  .i2(w3),
  .i3(w4),
  .i4(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de bus de 5-bits
/*-------------------------------------------------*/

module v78e2e0_v9a2a06 (
 input i4,
 input i3,
 input i2,
 input i1,
 input i0,
 output [4:0] o
);
 assign o = {i4, i3, i2, i1, i0};
 
endmodule
//---- Top entity
module v3bfe20 (
 input v717e81,
 input ve7f5e6,
 output v3c12b5
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = ve7f5e6;
 assign w1 = v717e81;
 assign v3c12b5 = w2;
 v3bfe20_v683a9f v683a9f (
  .i(w0),
  .clk(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Sync  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sincronizar las entradas de datos con el reloj del sistema
/*-------------------------------------------------*/

module v3bfe20_v683a9f (
 input clk,
 input i,
 output o
);
 // Sincronizacion. Evitar 
 // problema de la metaestabilidad
 
 reg d1;
 reg d2;
 
 always @(posedge clk)
  d1 <= i;
  
 always @(posedge clk)
   d2 <= d1;
   
 assign o = d2;
endmodule
//---- Top entity
module vc0bd39 (
 input [4:0] va69925,
 output vc7a3dc,
 output v5b73e8,
 output vc90115,
 output v2812a7,
 output v593f43
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:4] w5;
 assign v2812a7 = w0;
 assign v593f43 = w1;
 assign vc90115 = w2;
 assign v5b73e8 = w3;
 assign vc7a3dc = w4;
 assign w5 = va69925;
 vc0bd39_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .o2(w2),
  .o3(w3),
  .o4(w4),
  .i(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 5-bits en 5 cables
/*-------------------------------------------------*/

module vc0bd39_v9a2a06 (
 input [4:0] i,
 output o4,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o4 = i[4];
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v96c459 (
 input [4:0] va69925,
 output vc7a3dc,
 output [3:0] vca2ec8
);
 wire [0:4] w0;
 wire [0:3] w1;
 wire w2;
 assign w0 = va69925;
 assign vca2ec8 = w1;
 assign vc7a3dc = w2;
 v96c459_v9a2a06 v9a2a06 (
  .i(w0),
  .o(w1),
  .o4(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 5-bits en 1 bit y bus de 4 bits
/*-------------------------------------------------*/

module v96c459_v9a2a06 (
 input [4:0] i,
 output o4,
 output [3:0] o
);
 assign o4 = i[4];
 assign o = i[3:0];
 
endmodule
//---- Top entity
module vbc6704 (
 input [7:0] v595263,
 output vc85478,
 output v7ada3f,
 output v2c9812,
 output ve0c1b4,
 output v7c37b3,
 output v8f149e,
 output vb85197,
 output v45ab8c
);
 wire [0:7] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 assign w0 = v595263;
 assign vc85478 = w1;
 assign v7ada3f = w2;
 assign v2c9812 = w3;
 assign ve0c1b4 = w4;
 assign v7c37b3 = w5;
 assign v8f149e = w6;
 assign vb85197 = w7;
 assign v45ab8c = w8;
 vbc6704_v9a2a06 v9a2a06 (
  .i(w0),
  .o7(w1),
  .o6(w2),
  .o5(w3),
  .o4(w4),
  .o3(w5),
  .o2(w6),
  .o1(w7),
  .o0(w8)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 8-bits en 8 cables
/*-------------------------------------------------*/

module vbc6704_v9a2a06 (
 input [7:0] i,
 output o7,
 output o6,
 output o5,
 output o4,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o7 = i[7];
 assign o6 = i[6];
 assign o5 = i[5];
 assign o4 = i[4];
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v96655b #(
 parameter v4a1b3f = 4
) (
 input vfdbd5b,
 output [1:0] v1a4868,
 output vaf7398
);
 localparam p2 = v4a1b3f;
 wire w0;
 wire [0:1] w1;
 wire w3;
 assign w0 = vfdbd5b;
 assign v1a4868 = w1;
 assign vaf7398 = w3;
 v96655b_vf093da #(
  .M(p2)
 ) vf093da (
  .clk(w0),
  .q(w1),
  .max(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Contador-sistema-max  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Contador del sistema, de 2 bits, con salida de valor máximo alcanzado
/*-------------------------------------------------*/

module v96655b_vf093da #(
 parameter M = 0
) (
 input clk,
 output [1:0] q,
 output max
);
 //-- Número de bits del contador
 localparam N = 2;
 
 reg [N-1:0] q = 0;
 
 always @(posedge clk)
     q <= q + 1;
     
 assign max = (q == M-1);
endmodule
//---- Top entity
module v28f89a #(
 parameter vee8085 = 240000,
 parameter v421b6f = 6000,
 parameter vad13c1 = 18000,
 parameter v8a2420 = 30000
) (
 input vc08bbf,
 input [1:0] vf79cbe,
 output ve9490c
);
 localparam p8 = vee8085;
 localparam p13 = v421b6f;
 localparam p14 = vad13c1;
 localparam p15 = v8a2420;
 wire [0:15] w0;
 wire [0:7] w1;
 wire [0:7] w2;
 wire [0:1] w3;
 wire [0:7] w4;
 wire [0:31] w5;
 wire w6;
 wire w7;
 wire w9;
 wire w10;
 wire [0:5] w11;
 wire [0:7] w12;
 wire [0:31] w16;
 wire [0:31] w17;
 wire [0:31] w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire w24;
 wire w25;
 wire [0:1] w26;
 wire w27;
 wire w28;
 assign ve9490c = w25;
 assign w26 = vf79cbe;
 assign w27 = vc08bbf;
 assign w28 = vc08bbf;
 assign w7 = w6;
 assign w16 = w5;
 assign w17 = w5;
 assign w17 = w16;
 assign w18 = w5;
 assign w18 = w16;
 assign w18 = w17;
 assign w28 = w27;
 v8d4ef5 v3e93b5 (
  .va1a83a(w0),
  .ve61673(w7),
  .v7c533e(w9),
  .v712cd1(w10),
  .vdd729a(w28)
 );
 v725b7e v517441 (
  .v9fb85f(w9)
 );
 ve79148 v092767 (
  .vd76104(w3),
  .ve61673(w6),
  .v7c533e(w10),
  .vdd729a(w27)
 );
 vf9bdaf #(
  .v6b316b(p8)
 ) vd216f2 (
  .ve1f562(w5),
  .v18e78c(w6)
 );
 vb6ddba v9f1ec3 (
  .v63d71a(w1),
  .v9999de(w2),
  .v32ad8d(w4),
  .v2eef2f(w5),
  .v7a6a68(w12)
 );
 v26f57a v6d38b4 (
  .vad1323(w0),
  .vf774e8(w1),
  .v0e9841(w2)
 );
 v9f8856 v8e42bb (
  .v276bb9(w3),
  .va191ad(w4),
  .v7c0b91(w11)
 );
 v127665 #(
  .v16d6b8(p15)
 ) v1860f4 (
  .v229966(w16),
  .v18e78c(w21)
 );
 v356afe vde5aff (
  .va8bac6(w11)
 );
 v3bf99b v060363 (
  .vb096dc(w12)
 );
 v127665 #(
  .v16d6b8(p13)
 ) v56ab85 (
  .v229966(w17),
  .v18e78c(w20)
 );
 v127665 #(
  .v16d6b8(p14)
 ) vf0c6ea (
  .v229966(w18),
  .v18e78c(w19)
 );
 v28cfaa v20aa88 (
  .v7e70ae(w19),
  .vb186da(w20),
  .vd7f8af(w21),
  .v381ebf(w22),
  .vc13c07(w23),
  .v9b870f(w24),
  .vc93bbe(w25)
 );
 v21cfcc ve94aaf (
  .v9fb85f(w22)
 );
 vfc9dac vd12a03 (
  .v3f8943(w23),
  .v64d863(w24),
  .v8b19dd(w26)
 );
endmodule

/*-------------------------------------------------*/
/*-- servo_pwm  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v8d4ef5 #(
 parameter v5e4a03 = 'h10000
) (
 input vdd729a,
 input ve61673,
 input v7c533e,
 output [15:0] va1a83a,
 output v712cd1
);
 localparam p1 = v5e4a03;
 wire w0;
 wire w2;
 wire w3;
 wire w4;
 wire [0:15] w5;
 assign w0 = ve61673;
 assign w2 = v7c533e;
 assign w3 = vdd729a;
 assign v712cd1 = w4;
 assign va1a83a = w5;
 v8d4ef5_vbd6086 #(
  .M(p1)
 ) vbd6086 (
  .rst(w0),
  .cnt(w2),
  .clk(w3),
  .ov(w4),
  .q(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- Contador-16bits-up-rst  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Contador módulo M, ascendente, de 16 bits, con reset 
/*-------------------------------------------------*/

module v8d4ef5_vbd6086 #(
 parameter M = 0
) (
 input clk,
 input rst,
 input cnt,
 output [15:0] q,
 output ov
);
 //-- Numero de bits del contador
 localparam N = 16; 
 
 //-- En contadores de N bits:
 //-- M = 2 ** N
 
 //-- Internamente usamos un bit mas
 //-- (N+1) bits
 reg [N:0] qi = 0;
 
 always @(posedge clk)
   if (rst | ov)
     qi <= 0;
   else
     if (cnt)
       qi <= qi + 1;
       
 assign q = qi;
 
 //-- Comprobar overflow
 assign ov = (qi == M);
     
endmodule
//---- Top entity
module ve79148 #(
 parameter v5e4a03 = 4
) (
 input vdd729a,
 input ve61673,
 input v7c533e,
 output [1:0] vd76104,
 output v712cd1
);
 localparam p2 = v5e4a03;
 wire [0:1] w0;
 wire w1;
 wire w3;
 wire w4;
 wire w5;
 assign vd76104 = w0;
 assign w1 = ve61673;
 assign w3 = v7c533e;
 assign w4 = vdd729a;
 assign v712cd1 = w5;
 ve79148_vbd6086 #(
  .M(p2)
 ) vbd6086 (
  .q(w0),
  .rst(w1),
  .cnt(w3),
  .clk(w4),
  .ov(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- Contador-2bits-up-rst  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Contador módulo M, ascendente, de 2 bits, con reset 
/*-------------------------------------------------*/

module ve79148_vbd6086 #(
 parameter M = 0
) (
 input clk,
 input rst,
 input cnt,
 output [1:0] q,
 output ov
);
 //-- Numero de bits del contador
 localparam N = 2; 
 
 //-- En contadores de N bits:
 //-- M = 2 ** N
 
 //-- Internamente usamos un bit mas
 //-- (N+1) bits
 reg [N:0] qi = 0;
 
 always @(posedge clk)
   if (rst | ov)
     qi <= 2'b00;
   else
     if (cnt)
       qi <= qi + 1;
       
 assign q = qi;
 
 //-- Comprobar overflow
 assign ov = (qi == M);
     
endmodule
//---- Top entity
module vf9bdaf #(
 parameter v6b316b = 0
) (
 input [31:0] ve1f562,
 output v18e78c
);
 localparam p1 = v6b316b;
 wire w0;
 wire [0:31] w2;
 assign v18e78c = w0;
 assign w2 = ve1f562;
 vf9bdaf_vd75681 #(
  .K(p1)
 ) vd75681 (
  .eq(w0),
  .a(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Comparador  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comparador de un operando de 32 bits. Se compara si el operando es igual al parámetro
/*-------------------------------------------------*/

module vf9bdaf_vd75681 #(
 parameter K = 0
) (
 input [31:0] a,
 output eq
);
 assign eq = (a == K);
endmodule
//---- Top entity
module v26f57a (
 input [15:0] vad1323,
 output [7:0] vf774e8,
 output [7:0] v0e9841
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:15] w2;
 assign v0e9841 = w0;
 assign vf774e8 = w1;
 assign w2 = vad1323;
 v26f57a_v9a2a06 v9a2a06 (
  .o0(w0),
  .o1(w1),
  .i(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 16-bits en buses de 8 bits
/*-------------------------------------------------*/

module v26f57a_v9a2a06 (
 input [15:0] i,
 output [7:0] o1,
 output [7:0] o0
);
 assign o1 = i[15:8];
 assign o0 = i[7:0];
endmodule
//---- Top entity
module v127665 #(
 parameter v16d6b8 = 1
) (
 input [31:0] v229966,
 output v18e78c
);
 localparam p1 = v16d6b8;
 wire w0;
 wire [0:31] w2;
 assign v18e78c = w0;
 assign w2 = v229966;
 v127665_vd75681 #(
  .B(p1)
 ) vd75681 (
  .eq(w0),
  .a(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Menor-que-1-op  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comparador menor que, de un operando de 32 bits
/*-------------------------------------------------*/

module v127665_vd75681 #(
 parameter B = 0
) (
 input [31:0] a,
 output eq
);
 assign eq = (a < B);
endmodule
//---- Top entity
module v356afe #(
 parameter vc5c8ea = 0
) (
 output [5:0] va8bac6
);
 localparam p0 = vc5c8ea;
 wire [0:5] w1;
 assign va8bac6 = w1;
 v64e749 #(
  .vc5c8ea(p0)
 ) vd790d1 (
  .va8bac6(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_00_6bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 0, de 6 bits
/*-------------------------------------------------*/
//---- Top entity
module v64e749 #(
 parameter vc5c8ea = 0
) (
 output [5:0] va8bac6
);
 localparam p0 = vc5c8ea;
 wire [0:5] w1;
 assign va8bac6 = w1;
 v64e749_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Constante-6bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor genérico constante, de 6 bits. Su valor se introduce como parámetro. Por defecto vale 0
/*-------------------------------------------------*/

module v64e749_v465065 #(
 parameter VALUE = 0
) (
 output [5:0] k
);
 assign k = VALUE;
endmodule
